Repository sphinx-doc/sphinx, pull requests merged in 2018-10, with the labels that each got.

#5490 latex: add defaults for enumerated list prefix/suffix
  sphinx/writers/latex.py
Labels: bug, latex

#5505 Improve error message when config fails type check
  sphinx/config.py
  tests/test_config.py
Labels: config, proposal

#5475 Deprecate Python2 compat shim sphinx.util.osutil.walk()
  CHANGES
  doc/extdev/index.rst
  sphinx/ext/apidoc.py
  sphinx/util/__init__.py
  sphinx/util/fileutil.py
  sphinx/util/i18n.py
  sphinx/util/osutil.py
Labels: refactoring

#5510 Fix #5492: sphinx-build fails to build docs w/ Python < 3.5.2
  CHANGES
  sphinx/transforms/post_transforms/compat.py
Labels: bug

#5276 Add LaTeXBuilder.get_doc_context(): Build context object for each document
  sphinx/builders/latex/__init__.py
  sphinx/templates/latex/latex.tex_t
  sphinx/util/template.py
  sphinx/util/texescape.py
  sphinx/writers/latex.py
  tests/test_build_latex.py
  tests/test_markup.py
Labels: latex, refactoring

#5513 Fix #3704: (latex) wrong ``\label`` positioning for figures with a legend
  CHANGES
  sphinx/writers/latex.py
  tests/roots/test-latex-labels/index.rst
  tests/test_build_latex.py
Labels: bug, latex

#5512 latex: Separate message catalogs to sphinxmessage.sty
  CHANGES
  sphinx/builders/latex/__init__.py
  sphinx/templates/latex/latex.tex_t
  sphinx/templates/latex/sphinxmessage.sty_t
  sphinx/util/fileutil.py
  sphinx/util/texescape.py
  sphinx/writers/latex.py
Labels: latex, refactoring

#5521 Fix #5493: gettext: crashed with broken template
  CHANGES
  sphinx/builders/gettext.py
Labels: bug, i18n

#5530 Fix #5495: csv-table directive with file option in included file is broken
  CHANGES
  sphinx/directives/other.py
Labels: bug, markup

#5531 Fix #5498: autodoc: unable to find type hints for a ``functools.partial``
  CHANGES
  sphinx/util/inspect.py
  tests/py35/test_autodoc_py35.py
Labels: autodoc, bug

#5511 Remove unused search params: check_keywords, area
  sphinx/themes/agogo/layout.html
  sphinx/themes/basic/opensearch.xml
  sphinx/themes/basic/searchbox.html
Labels: html search, refactoring

#5514 Rename sphinxmessage.sty to sphinxmessages.sty (plural)
  sphinx/builders/latex/__init__.py
  sphinx/templates/latex/latex.tex_t
  sphinx/templates/latex/sphinxmessages.sty_t
Labels: latex, refactoring

#5537 Fix mypy violations
  sphinx/builders/html.py
  sphinx/builders/qthelp.py
  sphinx/cmd/quickstart.py
  sphinx/config.py
  sphinx/domains/c.py
  sphinx/domains/python.py
  sphinx/domains/rst.py
  sphinx/domains/std.py
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/autosummary/generate.py
  sphinx/ext/coverage.py
  sphinx/ext/graphviz.py
  sphinx/ext/imgmath.py
  sphinx/ext/inheritance_diagram.py
  sphinx/ext/napoleon/docstring.py
  sphinx/highlighting.py
  sphinx/locale/__init__.py
  sphinx/pycode/__init__.py
  sphinx/roles.py
  sphinx/search/__init__.py
  sphinx/testing/util.py
  sphinx/util/__init__.py
  sphinx/util/docutils.py
  sphinx/util/logging.py
  sphinx/util/nodes.py
  sphinx/util/rst.py
Labels: refactoring

#5369 Add project object
  CHANGES
  doc/extdev/appapi.rst
  doc/extdev/envapi.rst
  doc/extdev/index.rst
  doc/extdev/projectapi.rst
  sphinx/application.py
  sphinx/environment/__init__.py
  sphinx/project.py
  sphinx/util/__init__.py
  tests/test_environment.py
  tests/test_project.py
Labels: api, proposal, refactoring

#5535 Fix #5480: autodoc: unable to find type hints for unresolvable Forward references
  CHANGES
  sphinx/util/inspect.py
  tests/test_util_inspect.py
  tests/typing_test_data.py
Labels: autodoc, bug

#5542 Update CHANGES (refs: #5438)
  CHANGES
Labels: docs

#5533 autodoc: Respect `member-order` in `autodoc_default_options` as documented
  AUTHORS
  doc/usage/extensions/autodoc.rst
  sphinx/ext/autodoc/directive.py
  tests/test_autodoc.py
Labels: autodoc, proposal

#5543 Add more examples, add missing bracket, clean up URLs
  EXAMPLES
Labels: docs

#5565 doc: Fix typo of "default"
  doc/usage/configuration.rst
Labels: docs

#5564 doc: Fix typo of "restructuredtext"
  doc/usage/configuration.rst
Labels: docs

#5532 Fix #5471: Show appropriate warning for deprecated APIs
  CHANGES
  sphinx/__init__.py
  sphinx/addnodes.py
  sphinx/application.py
  sphinx/builders/__init__.py
  sphinx/builders/html.py
  sphinx/cmdline.py
  sphinx/config.py
  sphinx/deprecation.py
  sphinx/directives/code.py
  sphinx/domains/std.py
  sphinx/environment/__init__.py
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autodoc/inspector.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/intersphinx.py
  sphinx/ext/mathbase.py
  sphinx/ext/viewcode.py
  sphinx/highlighting.py
  sphinx/io.py
  sphinx/locale/__init__.py
  sphinx/make_mode.py
  sphinx/registry.py
  sphinx/search/ja.py
  sphinx/util/__init__.py
  sphinx/util/i18n.py
  sphinx/util/images.py
  sphinx/util/osutil.py
  sphinx/versioning.py
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
Labels: api

#5534 Fix #5419: incompatible math_block node has been generated
  CHANGES
  sphinx/transforms/post_transforms/compat.py
Labels: bug, extensions

#5536 Fix #5497: Do not include MathJax.js and jsmath.js unless it is really needed
  CHANGES
  sphinx/domains/math.py
  sphinx/ext/jsmath.py
  sphinx/ext/mathjax.py
  tests/test_ext_math.py
Labels: bug, extensions

#5545 Refactor loading extensions
  CHANGES
  doc/extdev/index.rst
  doc/extdev/logging.rst
  sphinx/application.py
  sphinx/registry.py
  sphinx/util/logging.py
  tests/test_application.py
  tests/test_util_logging.py
Labels: refactoring

#5546 test: Move autodoc_missing_imports to test-ext-autodoc
  tests/roots/test-ext-autodoc/target/need_mocks.py
  tests/roots/test-root/autodoc.txt
  tests/roots/test-root/conf.py
  tests/test_autodoc.py
  tests/test_build_texinfo.py
Labels: refactoring, test

#5570 test: Give filterwarnings=all by ini file
  setup.cfg
  tox.ini
Labels: test

#5571 Fix #3002: i18n: multiple footnote_references referring same footnote causes duplicated node_ids
  CHANGES
  sphinx/transforms/i18n.py
  tests/roots/test-intl/footnote.po
  tests/roots/test-intl/footnote.txt
  tests/test_intl.py
Labels: bug, i18n

#5574 LaTeX: do not use `-I xelatex` option with xindy (Fix: #5561)
  CHANGES
  sphinx/texinputs/Makefile_t
Labels: bug, latex
