Repository sphinx-doc/sphinx, pull requests merged in 2018-03, with the labels that each got.

#4674 Improve i18n
  CHANGES
  doc/extdev/appapi.rst
  doc/extdev/i18n.rst
  doc/extdev/index.rst
  sphinx/application.py
  sphinx/builders/html.py
  sphinx/cmd/build.py
  sphinx/cmd/quickstart.py
  sphinx/cmdline.py
  sphinx/config.py
  sphinx/domains/c.py
  sphinx/domains/cpp.py
  sphinx/domains/javascript.py
  sphinx/domains/python.py
  sphinx/domains/rst.py
  sphinx/domains/std.py
  sphinx/ext/apidoc.py
  sphinx/ext/autosummary/generate.py
  sphinx/ext/napoleon/__init__.py
  sphinx/locale/__init__.py
  sphinx/testing/util.py
  sphinx/transforms/__init__.py
  sphinx/transforms/i18n.py
  sphinx/writers/latex.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
  tests/roots/test-locale/locale1/en/LC_MESSAGES/myext.mo
  tests/roots/test-locale/locale1/en/LC_MESSAGES/myext.po
  tests/roots/test-locale/locale2/en/LC_MESSAGES/myext.mo
  tests/roots/test-locale/locale2/en/LC_MESSAGES/myext.po
  tests/test_locale.py
Labels: cmdline, i18n, proposal

#4675 doc: Add deprecation list
  CHANGES
  doc/extdev/index.rst
Labels: docs

#4695 Remove the remaining traces of sphinx.pycode.pgen2 module
  LICENSE
  setup.cfg
  setup.py
Labels: refactoring

#4690 doc: Add a reference to awesome-sphinxdoc
  doc/ext/thirdparty.rst
Labels: docs

#4691 Fix infinit loop on make-mode
  sphinx/make_mode.py
Labels: bug, cmdline

#4693 Catch errors on compiling catalogs (refs: #4655)
  setup.py
Labels: bug

#4696 Fix #4685: autosummary emits meaningless warnings
  CHANGES
  sphinx/ext/autosummary/__init__.py
  sphinx/util/docutils.py
  tests/test_ext_autosummary.py
Labels: autodoc, bug

#4697 Move labels
  sphinx/builders/gettext.py
  sphinx/deprecation.py
  sphinx/directives/other.py
  sphinx/domains/python.py
  sphinx/locale/__init__.py
  sphinx/util/nodes.py
Labels: i18n, refactoring

#4698 Make sphinx-* commands translatable
  sphinx/cmd/build.py
  sphinx/cmd/quickstart.py
  sphinx/ext/apidoc.py
  sphinx/ext/autosummary/generate.py
Labels: i18n

#4702 Remove sphinx.ext.pngmath
  CHANGES
  sphinx/ext/pngmath.py
Labels: extensions

#4703 Fix autodoc: crashed when invalid options given
  CHANGES
  sphinx/ext/autodoc/directive.py
Labels: autodoc, bug

#4687 Fix pydomain: always strip parenthesis if empty (refs: #1042)
  CHANGES
  sphinx/domains/python.py
Labels: bug, domains:py

#4704 Use "%r" to stringify exceptions
  sphinx/directives/code.py
  sphinx/environment/collectors/indexentries.py
  sphinx/ext/graphviz.py
Labels: bug, cmdline

#4694 Fix #4689: autosummary: unexpectedly strips docstrings containing "i.e."
  CHANGES
  sphinx/ext/autosummary/__init__.py
  tests/test_ext_autosummary.py
Labels: autodoc, bug

#4709 Fix #4701: viewcode: Misplaced ``<div>`` in viewcode html output
  CHANGES
  sphinx/ext/viewcode.py
  tests/test_ext_viewcode.py
Labels: bug, extensions

#4715 Fix filename of epub (refs: #4611)
  tests/test_build_epub.py
Labels: bug, test

#4719 Relax numref on sections
  CHANGES
  sphinx/domains/std.py
  tests/test_build_html.py
Labels: domains:std, markup

#4728 Fix #4727: Option clash for package textcomp
  CHANGES
  sphinx/templates/latex/latex.tex_t
  sphinx/texinputs/sphinx.sty
Labels: bug, latex

#4730 prevent raising of FutureWarning in regex
  sphinx/util/rst.py
Labels: bug

#4718 Fix #4716: Generation PDF file with TexLive on Windows, file not found error
  CHANGES
  sphinx/make_mode.py
Labels: bug, cmdline

#4729 Fix vertical space before equation in latex (closes: #4574)
  sphinx/ext/mathbase.py
  sphinx/writers/latex.py
  tests/roots/test-latex-equations/conf.py
  tests/roots/test-latex-equations/equations.rst
  tests/roots/test-latex-equations/expects/latex-equations.tex
  tests/test_build_latex.py
Labels: bug, latex

#4741 Update deprecation list
  CHANGES
  doc/extdev/index.rst
Labels: docs

#4748 Fix #4720: message when an image is mismatched for builder is not clear
  CHANGES
  sphinx/builders/__init__.py
  tests/test_build_html.py
  tests/test_build_latex.py
  tests/test_build_texinfo.py
Labels: latex

#4750 4655 fix chinese translations
  CHANGES
  sphinx/locale/zh_CN/LC_MESSAGES/sphinx.mo
  sphinx/locale/zh_CN/LC_MESSAGES/sphinx.po
Labels: bug, i18n

#4753 Update docs (refs: #2307)
  doc/markup/code.rst
Labels: docs

#4752 Fix #2286: Sphinx crashes when error is happens in rendering HTML pages
  CHANGES
  sphinx/builders/html.py
Labels: bug, html theme

#4751 Closes #2157: helper function ``warning()`` for HTML themes is added
  CHANGES
  doc/extdev/index.rst
  doc/templating.rst
  sphinx/builders/html.py
  sphinx/jinja2glue.py
Labels: html theme

#4747 4688 remote image having long url
  CHANGES
  sphinx/transforms/post_transforms/images.py
Labels: bug, builder

#4756 Fix #4754: sphinx/pycode/__init__.py raises AttributeError
  CHANGES
  sphinx/pycode/__init__.py
Labels: bug, test

#4749 Qthelp templates
  CHANGES
  sphinx/builders/qthelp.py
  sphinx/templates/qthelp/project.qhcp
  sphinx/templates/qthelp/project.qhp
  tests/roots/test-need-escaped/bar.rst
  tests/roots/test-need-escaped/baz.rst
  tests/roots/test-need-escaped/conf.py
  tests/roots/test-need-escaped/foo.rst
  tests/roots/test-need-escaped/index.rst
  tests/roots/test-need-escaped/quux.rst
  tests/roots/test-need-escaped/qux.rst
  tests/test_build_qthelp.py
Labels: bug, builder

#4757 test: Suppress DeprecationWarning
  tests/test_autodoc.py
Labels: test

#4758 epub: Fix docTitle elements of toc.ncx is not escaped
  CHANGES
  sphinx/builders/_epub_base.py
  tests/test_build_epub.py
Labels: bug, epub

#4761 Fix invalid __file__ variable is passed to conf.py
  sphinx/application.py
Labels: bug, config

#4759 Reduce the log level of message for add_translator()
  sphinx/registry.py
Labels: cmdline

#4763 Fix existence check for JRE was broken
  tests/test_build_epub.py
  tox.ini
Labels: test

#4762 Fix #4724: doc: an example of autogen is incorrect
  doc/man/sphinx-autogen.rst
Labels: docs

#4764 Fix #4744: Add canonical URL to docs
  doc/_themes/sphinx13/layout.html
Labels: docs

#4766 4520 apidoc
  CHANGES
  sphinx/ext/apidoc.py
  tests/roots/test-apidoc-subpackage-in-toc/parent/__init__.py
  tests/roots/test-apidoc-subpackage-in-toc/parent/child/__init__.py
  tests/roots/test-apidoc-subpackage-in-toc/parent/child/foo.py
  tests/test_ext_apidoc.py
Labels: apidoc, bug

#4742 Refactor enumerable nodes
  CHANGES
  sphinx/domains/__init__.py
  sphinx/domains/std.py
  sphinx/environment/collectors/toctree.py
  sphinx/ext/mathbase.py
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
Labels: api, domain, enhancement

#4768 Minor typo
  doc/setuptools.rst
Labels: docs

#4774 Fix #4769: autodoc loses the first staticmethod parameter
  CHANGES
  sphinx/ext/autodoc/__init__.py
  tests/test_autodoc.py
Labels: autodoc, bug

#4780 Drop typing.TYPE_CHECKING
  sphinx/apidoc.py
  sphinx/ext/extlinks.py
  sphinx/ext/githubpages.py
  sphinx/ext/jsmath.py
  sphinx/ext/mathjax.py
  sphinx/quickstart.py
  sphinx/testing/path.py
Labels: bug

#4781 Deprecate env._nitpick_ignore
  CHANGES
  doc/extdev/index.rst
  sphinx/environment/__init__.py
  sphinx/transforms/post_transforms/__init__.py
Labels: config, environment, refactoring

#4792 Fix autosummary latex table colspec (closes #4790)
  sphinx/ext/autosummary/__init__.py
  tests/test_ext_autosummary.py
Labels: bug, extensions, latex

#4788 Fix #4787: Update docstrings for add_directive()
  sphinx/application.py
Labels: docs

#4760 Add a new keyword argument ``override`` to Application APIs
  CHANGES
  doc/extdev/index.rst
  sphinx/application.py
  sphinx/registry.py
  tests/test_application.py
Labels: api, enhancement

#4796 Fix broken LateX customization via templates (closes: #4795)
  sphinx/writers/latex.py
  tests/roots/test-latex-table/_mytemplates/latex/longtable.tex_t
  tests/test_build_latex.py
Labels: bug, latex
