Repository sphinx-doc/sphinx, pull requests merged in 2018-12, with the labels that each got.

#5692 Fix annotations (in some modules)
  sphinx/application.py
  sphinx/transforms/i18n.py
  sphinx/util/docutils.py
  sphinx/util/inspect.py
  sphinx/util/nodes.py
  sphinx/versioning.py
Labels: refactoring

#5694 Fix annotations for i18n
  sphinx/addnodes.py
  sphinx/domains/std.py
  sphinx/transforms/i18n.py
  sphinx/util/nodes.py
Labels: refactoring

#5695 Fix annotations for Directives (Replace N_co with nodes.Node)
  sphinx/addnodes.py
  sphinx/directives/__init__.py
  sphinx/directives/code.py
  sphinx/directives/other.py
  sphinx/directives/patches.py
  sphinx/domains/__init__.py
  sphinx/domains/changeset.py
  sphinx/domains/cpp.py
  sphinx/domains/javascript.py
  sphinx/domains/python.py
  sphinx/domains/std.py
  sphinx/ext/autodoc/directive.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/doctest.py
  sphinx/ext/graphviz.py
  sphinx/ext/ifconfig.py
  sphinx/ext/inheritance_diagram.py
  sphinx/ext/todo.py
Labels: refactoring

#5696 Refactor docutils manipulation
  sphinx/application.py
  sphinx/directives/__init__.py
  sphinx/util/docutils.py
  sphinx/util/rst.py
Labels: refactoring

#5607 quickstart: Simplify generated conf.py (for texinfo)
  doc/usage/configuration.rst
  sphinx/builders/texinfo.py
  sphinx/templates/quickstart/conf.py_t
  sphinx/util/osutil.py
  tests/roots/test-root/conf.py
  tests/test_build_texinfo.py
  tests/test_quickstart.py
Labels: config, proposal

#5698 quickstart: Simplify generated conf.py (for htmlhelp)
  sphinx/builders/htmlhelp.py
  sphinx/templates/quickstart/conf.py_t
  tests/roots/test-root/conf.py
  tests/test_build_htmlhelp.py
Labels: config, proposal

#5699 quickstart: Simplify generated conf.py (for manpage)
  sphinx/builders/manpage.py
  sphinx/templates/quickstart/conf.py_t
  tests/roots/test-root/conf.py
  tests/test_build_manpage.py
  tests/test_quickstart.py
Labels: config, proposal

#5697 Refactor Toctree Collector
  sphinx/environment/__init__.py
  sphinx/environment/collectors/__init__.py
  sphinx/environment/collectors/asset.py
  sphinx/environment/collectors/dependencies.py
  sphinx/environment/collectors/indexentries.py
  sphinx/environment/collectors/title.py
  sphinx/environment/collectors/toctree.py
Labels: environment, refactoring

#5703 Fix annotations for builders
  sphinx/builders/_epub_base.py
  sphinx/builders/applehelp.py
  sphinx/builders/devhelp.py
  sphinx/builders/epub3.py
  sphinx/builders/html.py
  sphinx/builders/htmlhelp.py
  sphinx/builders/latex/transforms.py
  sphinx/builders/linkcheck.py
  sphinx/builders/qthelp.py
  sphinx/builders/xml.py
  sphinx/ext/mathbase.py
  sphinx/util/nodes.py
  sphinx/writers/latex.py
  sphinx/writers/xml.py
Labels: refactoring

#5704 Fix annotations (minor fixes)
  sphinx/addnodes.py
  sphinx/builders/_epub_base.py
  sphinx/builders/gettext.py
  sphinx/builders/manpage.py
  sphinx/directives/patches.py
  sphinx/domains/cpp.py
  sphinx/domains/std.py
  sphinx/environment/__init__.py
  sphinx/ext/autosectionlabel.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/imgmath.py
  sphinx/ext/linkcode.py
  sphinx/ext/mathbase.py
  sphinx/ext/todo.py
  sphinx/ext/viewcode.py
  sphinx/testing/path.py
  sphinx/transforms/__init__.py
  sphinx/transforms/post_transforms/compat.py
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
Labels: refactoring

#5708 Fix annotations for LaTeX writer
  sphinx/writers/latex.py
Labels: bug

#5705 Fix typehints for settings and memo objects
  sphinx/builders/latex/transforms.py
  sphinx/directives/other.py
Labels: refactoring

#5707 Fix annotations for fileobj in HTML builder
  sphinx/builders/html.py
Labels: refactoring

#5710 Fix typehints for XRefRole
  sphinx/domains/c.py
  sphinx/domains/cpp.py
  sphinx/domains/javascript.py
  sphinx/domains/math.py
  sphinx/domains/std.py
  sphinx/roles.py
Labels: refactoring

#5711 Fix annotations of enumerable_nodes
  sphinx/application.py
  sphinx/domains/__init__.py
  sphinx/domains/std.py
  sphinx/environment/collectors/toctree.py
  sphinx/registry.py
  sphinx/writers/latex.py
Labels: refactoring

#5709 Fix annotations of testing
  sphinx/testing/util.py
  tests/test_roles.py
Labels: refactoring

#5712 Use StringList for params to docutils because of expected
  sphinx/directives/code.py
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autosummary/__init__.py
  sphinx/util/docutils.py
Labels: bug, refactoring

#5713 Fix typehints for cpp domain
  sphinx/domains/__init__.py
  sphinx/domains/cpp.py
  sphinx/util/docfields.py
Labels: refactoring

#5714 refactor figure_wrapper() using state.inline_text()
  sphinx/ext/graphviz.py
  tests/roots/test-ext-graphviz/index.rst
  tests/test_ext_graphviz.py
Labels: extensions, refactoring

#5715 Refactor writers
  CHANGES
  doc/extdev/index.rst
  sphinx/writers/latex.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
Labels: refactoring

#5719 refactor NodeMatcher for mypy friendly
  sphinx/util/nodes.py
Labels: refactoring

#5722 refactor: Use "self.config" accessor to get it simply
  sphinx/builders/latex/transforms.py
Labels: refactoring

#5723 Fix annotations for nested_parse_with_titles()
  sphinx/util/nodes.py
Labels: bug

#5721 Fix annotation of Catalog.add(); it takes an Element object
  sphinx/builders/gettext.py
Labels: bug

#5718 refactor: Use app.add_node() to register Sphinx own nodes
  sphinx/addnodes.py
  sphinx/application.py
Labels: refactoring

#5717 refactor ``mock()`` to based on PEP-451 implementation
  CHANGES
  doc/extdev/index.rst
  sphinx/ext/autodoc/importer.py
  tests/test_ext_autodoc_importer.py
Labels: autodoc, refactoring

#5726 Process prolog and epilog on RSTParser (instead Input component)
  CHANGES
  doc/extdev/index.rst
  sphinx/io.py
  sphinx/parsers.py
  sphinx/util/rst.py
  tests/test_directive_other.py
  tests/test_parser.py
  tests/test_util_rst.py
Labels: refactoring

#5729 Add UnicodeDecodeErrorHandler as a error_handler for open()
  sphinx/io.py
  sphinx/util/__init__.py
Labels: refactoring

#5730 Add DirectiveOption type to an entry of Directive.option_spec
  sphinx/directives/__init__.py
  sphinx/util/typing.py
Labels: refactoring

#5731 Refactor `sphinx.io`: Remove unused codes
  sphinx/io.py
Labels: refactoring

#5732 Remove N_co type (unused)
  sphinx/util/typing.py
Labels: refactoring

#5733 Update type annotations
  sphinx/domains/c.py
  sphinx/domains/changeset.py
  sphinx/domains/rst.py
  sphinx/domains/std.py
  sphinx/environment/__init__.py
  sphinx/environment/adapters/toctree.py
  sphinx/ext/autosummary/__init__.py
  sphinx/writers/manpage.py
Labels: refactoring

#5736 Fix a mypy violation
  sphinx/locale/__init__.py
Labels: bug

#5735 Fix annotations
  sphinx/directives/other.py
  sphinx/environment/adapters/toctree.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/graphviz.py
  sphinx/ext/imgmath.py
  sphinx/ext/napoleon/docstring.py
  sphinx/registry.py
  sphinx/transforms/__init__.py
  sphinx/transforms/i18n.py
  sphinx/transforms/post_transforms/__init__.py
  sphinx/writers/latex.py
  sphinx/writers/texinfo.py
Labels: refactoring

#5737 refactor: special rubric for footnotes
  sphinx/builders/_epub_base.py
  sphinx/writers/latex.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
  tests/test_build_latex.py
  tests/test_build_manpage.py
  tests/test_build_texinfo.py
Labels: refactoring

#5739 Fix annotations (some modules)
  sphinx/domains/c.py
  sphinx/environment/__init__.py
  sphinx/transforms/post_transforms/__init__.py
  sphinx/util/docfields.py
  sphinx/writers/texinfo.py
Labels: refactoring

#5740 Add TextlikeNode type for docfields
  sphinx/domains/python.py
  sphinx/util/docfields.py
  sphinx/util/typing.py
Labels: refactoring

#5744 Correct type signature of set_role_source_info()
  sphinx/roles.py
  sphinx/util/nodes.py
Labels: refactoring

#5746 Deprecate unused and untested sphinx.util functions
  CHANGES
  doc/extdev/index.rst
  sphinx/util/__init__.py
Labels: refactoring

#5741 Use 'dist: xenial' in Travis to simplify configuration
  .travis.yml
Labels: refactoring, test

#5748 Remove Python2 exception type in inheritance_diagram.py
  sphinx/ext/inheritance_diagram.py
Labels: refactoring

#5752 Fix annotations
  sphinx/builders/_epub_base.py
  sphinx/environment/__init__.py
  sphinx/ext/autodoc/directive.py
  sphinx/writers/latex.py
  sphinx/writers/texinfo.py
Labels: refactoring

#5753 Fix annotations for toctree
  sphinx/environment/adapters/toctree.py
Labels: refactoring

#5751 Refactor Autosummary directive by DocumenterBridge
  CHANGES
  doc/extdev/index.rst
  sphinx/ext/autosummary/__init__.py
Labels: refactoring

#5700 quickstart: Simplify generated conf.py (common items)
  sphinx/templates/quickstart/conf.py_t
Labels: config, proposal

#5758 Fix annotaions for docfields
  sphinx/util/docfields.py
Labels: refactoring

#5754 DOC: Fix some minor mistakes in "LaTeX customization"
  doc/latex.rst
Labels: docs, latex

#5761 Fix annotations
  sphinx/locale/__init__.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
Labels: refactoring

#5762 Remove HTML5Translator.should_be_compact_paragraph() (unused)
  sphinx/writers/html5.py
Labels: refactoring

#5763 Remove SphinxTranslator.get_settings()
  sphinx/util/docutils.py
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
Labels: refactoring

#5764 explicitly recommend to inherit CSS via @import
  doc/theming.rst
Labels: docs, html theme

#5765 refactor SphinxSmartQuotes: Override smartquotes_action by str value (instaed of property)
  sphinx/transforms/__init__.py
Labels: refactoring

#5767 Add super method; CPPObject.get_index_text()
  sphinx/domains/cpp.py
Labels: domains:cpp, refactoring

#5769 Use nodes.Element for visitor/departure methods
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
Labels: refactoring

#5768 LaTeX: use ``\small`` fontsize in code-blocks with xelatex and lualatex
  doc/usage/configuration.rst
  sphinx/writers/latex.py
Labels: latex

#5760 Migrate to mypy py3 mode
  setup.cfg
  setup.py
  sphinx/__main__.py
  sphinx/application.py
  sphinx/builders/applehelp.py
  sphinx/builders/changes.py
  sphinx/builders/devhelp.py
  sphinx/builders/gettext.py
  sphinx/builders/html.py
  sphinx/builders/htmlhelp.py
  sphinx/builders/latex/__init__.py
  sphinx/builders/linkcheck.py
  sphinx/builders/qthelp.py
  sphinx/builders/text.py
  sphinx/builders/xml.py
  sphinx/cmd/build.py
  sphinx/cmd/quickstart.py
  sphinx/config.py
  sphinx/directives/code.py
  sphinx/directives/patches.py
  sphinx/domains/changeset.py
  sphinx/domains/cpp.py
  sphinx/domains/python.py
  sphinx/environment/__init__.py
  sphinx/environment/adapters/toctree.py
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autodoc/directive.py
  sphinx/ext/autosummary/generate.py
  sphinx/ext/doctest.py
  sphinx/ext/graphviz.py
  sphinx/ext/imgmath.py
  sphinx/ext/inheritance_diagram.py
  sphinx/ext/intersphinx.py
  sphinx/ext/napoleon/docstring.py
  sphinx/highlighting.py
  sphinx/io.py
  sphinx/locale/__init__.py
  sphinx/parsers.py
  sphinx/pycode/parser.py
  sphinx/registry.py
  sphinx/testing/path.py
  sphinx/testing/util.py
  sphinx/transforms/i18n.py
  sphinx/util/docutils.py
  sphinx/util/fileutil.py
  sphinx/util/i18n.py
  sphinx/util/images.py
  sphinx/util/inspect.py
  sphinx/util/jsdump.py
  sphinx/util/logging.py
  sphinx/util/nodes.py
  sphinx/util/osutil.py
  sphinx/util/pycompat.py
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
  tox.ini
Labels: refactoring

#5776 LaTeX: use Bjarne option of fncychap also if language is set to 'en'
  CHANGES
  doc/usage/configuration.rst
  sphinx/writers/latex.py
Labels: bug, latex

#5780 refactor: Replace six.moves.zip_longest by itertools.zip_longest
  sphinx/versioning.py
Labels: refactoring

#5781 refactor: Drop six.PY2
  tests/test_util.py
Labels: refactoring

#5782 refactor: Replace six.UserString by collections.UserString
  sphinx/locale/__init__.py
  sphinx/util/jsonimpl.py
Labels: refactoring

#5777 Deprecate abbreviation node (refs: #5720)
  CHANGES
  doc/extdev/index.rst
  sphinx/addnodes.py
  sphinx/roles.py
Labels: refactoring

#5785 refactor: Replace six.StringIO by io.StringIO
  sphinx/builders/gettext.py
  sphinx/ext/doctest.py
  sphinx/pycode/__init__.py
  sphinx/setup_command.py
  sphinx/testing/fixtures.py
  sphinx/util/inspect.py
  tests/roots/test-ext-autodoc/target/__init__.py
  tests/roots/test-root/autodoc_target.py
  tests/test_ext_autosummary.py
  tests/test_io.py
  tests/test_quickstart.py
Labels: refactoring

#5784 Refactor hack for py2
  CHANGES
  doc/extdev/index.rst
  sphinx/__init__.py
  sphinx/builders/html.py
  sphinx/deprecation.py
  sphinx/domains/cpp.py
  sphinx/ext/autodoc/__init__.py
  sphinx/util/__init__.py
  sphinx/util/inspect.py
  sphinx/util/requests.py
  sphinx/writers/latex.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
  tests/test_autodoc.py
Labels: refactoring

#5775 Fix #5770: doctest: Follow highlight_language on highlighting doctest block
  CHANGES
  sphinx/ext/doctest.py
  tests/test_ext_doctest.py
Labels: bug, extensions

#5794 Replace pycompat.htmlescape() by html.escape()
  sphinx/builders/applehelp.py
  sphinx/builders/changes.py
  sphinx/builders/html.py
  sphinx/builders/htmlhelp.py
  sphinx/builders/qthelp.py
  sphinx/highlighting.py
  sphinx/search/__init__.py
Labels: refactoring

#5790 Latex turnoff lualatex ligatures
  CHANGES
  doc/usage/configuration.rst
  sphinx/writers/latex.py
Labels: bug, latex

#5792 Deprecate UnicodeMixin
  CHANGES
  doc/extdev/index.rst
  sphinx/domains/cpp.py
  sphinx/ext/napoleon/docstring.py
  sphinx/locale/__init__.py
  sphinx/util/pycompat.py
Labels: refactoring

#5793 Pretty changes
  CHANGES
  doc/extdev/index.rst
  sphinx/writers/latex.py
Labels: refactoring

#5811 LaTeX: allow sphinxVerbatim usage without explicit "hllines" extra setup
  CHANGES
  sphinx/texinputs/sphinx.sty
  sphinx/writers/latex.py
  tests/roots/test-latex-table/expects/longtable_having_verbatim.tex
  tests/roots/test-latex-table/expects/table_having_verbatim.tex
  tests/test_directive_code.py
  tests/test_markup.py
Labels: bug, latex

#5812 C++, fix parsing of floating point literals
  CHANGES
  sphinx/domains/cpp.py
  tests/test_domain_cpp.py
Labels: domains:cpp

#5815 Define Documenter.analyzer as type ModuleAnalyzer
  sphinx/ext/autodoc/__init__.py
Labels: refactoring

#5817 Define a common Inventory type for reuse across modules
  sphinx/ext/intersphinx.py
  sphinx/util/inventory.py
  sphinx/util/typing.py
Labels: refactoring

#5824 Remove absolute_import
  tests/roots/test-ext-viewcode-find/not_a_package/__init__.py
  tests/test_ext_viewcode.py
Labels: refactoring

#5771 Fix regression regarding LaTeX table of contents name (refs: #5683)
  sphinx/writers/latex.py
Labels: bug, regression

#5825 Add comment for Inventory type
  sphinx/util/typing.py
Labels: docs

#5833 Fix annotations of code directives
  sphinx/directives/code.py
Labels: refactoring

#5829 Fix #5724: quickstart: sphinx-quickstart fails when $LC_ALL is empty
  CHANGES
  sphinx/cmd/build.py
  sphinx/cmd/quickstart.py
  sphinx/ext/apidoc.py
  sphinx/ext/autosummary/generate.py
  sphinx/locale/__init__.py
Labels: bug, cmdline

#5828 Reorder the arguments for translators
  CHANGES
  sphinx/util/docutils.py
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
Labels: refactoring

#5783 Replace EnvironmentError and IOError by OSError
  CHANGES
  doc/extdev/index.rst
  sphinx/builders/_epub_base.py
  sphinx/builders/html.py
  sphinx/builders/texinfo.py
  sphinx/builders/text.py
  sphinx/builders/xml.py
  sphinx/directives/code.py
  sphinx/domains/__init__.py
  sphinx/environment/__init__.py
  sphinx/environment/collectors/asset.py
  sphinx/ext/graphviz.py
  sphinx/ext/imgconverter.py
  sphinx/util/osutil.py
  sphinx/versioning.py
Labels: refactoring

#5664 refactor: Initialize template variables for LaTeX in builder; date, logofilename and packages
  CHANGES
  doc/usage/configuration.rst
  sphinx/builders/latex/__init__.py
  sphinx/templates/latex/latex.tex_t
  sphinx/writers/latex.py
Labels: latex, refactoring

#5838 Fix #5834: apidoc: wrong help for --tocfile
  CHANGES
  sphinx/ext/apidoc.py
Labels: apidoc, bug, docs

#5693 LaTeX (doc): explain how to allow Unicode input in math
  doc/usage/configuration.rst
  doc/usage/restructuredtext/directives.rst
Labels: docs, latex

#5848 Fix #5800: todo: crashed if todo is defined in TextElement
  CHANGES
  sphinx/ext/todo.py
  tests/roots/test-ext-todo/foo.rst
  tests/test_ext_todo.py
Labels: bug, extensions

#5843 Replace escape sequence '\u00B6' with literal '¶'
  sphinx/builders/html.py
  sphinx/writers/html.py
  sphinx/writers/html5.py
Labels: refactoring

#5850 LaTeX: ``\sphinxmaketitle`` and optional ``\sphinxbackoftitlepage``
  CHANGES
  doc/latex.rst
  doc/usage/configuration.rst
  sphinx/texinputs/sphinxhowto.cls
  sphinx/texinputs/sphinxmanual.cls
  sphinx/writers/latex.py
Labels: bug, latex

#5852 LaTeX: move some hard-coded re-definitions to user hook for TOC
  CHANGES
  doc/latex.rst
  sphinx/texinputs/sphinxhowto.cls
  sphinx/texinputs/sphinxmanual.cls
Labels: latex

#5842 Move immediate append operation to list literal
  sphinx/util/__init__.py
Labels: refactoring

#5853 [1.8] htmlhelp: convert hex escaping to decimal escaping in .hhc/.hhk files
  CHANGES
  sphinx/builders/htmlhelp.py
  tests/roots/test-build-htmlhelp/conf.py
  tests/roots/test-build-htmlhelp/index.rst
  tests/roots/test-build-htmlhelp/make.bat
  tests/test_build_htmlhelp.py
Labels: bug, builder

#5860 don't generate build files inside /tests/roots/test-build-htmlhelp/
  tests/test_build_htmlhelp.py
Labels: bug, builder, test

#5862 refactor chm_htmlescape()
  CHANGES
  sphinx/builders/htmlhelp.py
  tests/test_build_htmlhelp.py
Labels: refactoring

#5861 #5660 add classes for different version modications
  CHANGES
  sphinx/domains/changeset.py
  tests/test_intl.py
Labels: html, markup

#5806 Replace use of six.text_type with str
  CHANGES
  setup.py
  sphinx/builders/html.py
  sphinx/builders/latex/__init__.py
  sphinx/cmd/build.py
  sphinx/cmd/quickstart.py
  sphinx/config.py
  sphinx/domains/cpp.py
  sphinx/environment/adapters/indexentries.py
  sphinx/environment/collectors/indexentries.py
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/imgmath.py
  sphinx/highlighting.py
  sphinx/locale/__init__.py
  sphinx/pycode/parser.py
  sphinx/search/__init__.py
  sphinx/testing/path.py
  sphinx/transforms/post_transforms/code.py
  sphinx/transforms/post_transforms/images.py
  sphinx/util/__init__.py
  sphinx/util/images.py
  sphinx/util/jsonimpl.py
  sphinx/util/nodes.py
  sphinx/util/pycompat.py
  sphinx/util/typing.py
  sphinx/writers/latex.py
  tests/test_domain_cpp.py
  tests/test_domain_py.py
  tests/test_quickstart.py
Labels: refactoring

#5611 WIP: #5605 fix Chinese search index
  CHANGES
  sphinx/search/zh.py
  tests/roots/test-search/tocitem.rst
  tests/test_search.py
Labels: bug, html search

#5865 Fix various spelling typos
  CHANGES
  doc/extdev/logging.rst
  doc/extdev/tutorial.rst
  doc/man/sphinx-apidoc.rst
  doc/usage/configuration.rst
  doc/usage/extensions/autodoc.rst
  doc/usage/extensions/doctest.rst
  doc/usage/extensions/napoleon.rst
  doc/usage/restructuredtext/directives.rst
  doc/usage/restructuredtext/domains.rst
  sphinx/addnodes.py
  sphinx/application.py
  sphinx/builders/__init__.py
  sphinx/locale/__init__.py
  sphinx/parsers.py
Labels: docs
