Repository sphinx-doc/sphinx, pull requests merged in 2018-04, with the labels that each got.

#4797 Fix #4789: imgconverter: confused by converter.exe of Windows
  CHANGES
  sphinx/ext/imgconverter.py
Labels: bug, extensions

#4800 Drop `document.settings.gettext_compact`
  CHANGES
  doc/extdev/index.rst
  sphinx/environment/__init__.py
  sphinx/transforms/i18n.py
Labels: refactoring

#4808 Fix error handling on imgconverter
  sphinx/ext/imgconverter.py
Labels: bug

#4804 Add SphinxDirective class
  doc/extdev/index.rst
  doc/extdev/utils.rst
  sphinx/directives/__init__.py
  sphinx/directives/code.py
  sphinx/directives/other.py
  sphinx/directives/patches.py
  sphinx/transforms/__init__.py
  sphinx/util/docutils.py
Labels: proposal

#4807 Fix #4783: Sphinx crashed when drives of srcdir and outdir are different
  CHANGES
  sphinx/application.py
  sphinx/builders/__init__.py
  sphinx/builders/gettext.py
  sphinx/environment/__init__.py
  sphinx/ext/doctest.py
  sphinx/testing/util.py
  sphinx/util/i18n.py
  sphinx/util/osutil.py
Labels: bug

#4813 Fix #4812: autodoc ignores type annotated variables
  CHANGES
  sphinx/directives/other.py
  sphinx/pycode/parser.py
  tests/test_pycode_parser.py
Labels: autodoc, bug

#4822 Fix #4543: testcase for partialmethod is failed with py3.6.5
  sphinx/util/inspect.py
  tests/test_autodoc.py
Labels: autodoc, test

#4823 Fix #4817: wrong URLs on warning messages
  CHANGES
  sphinx/templates/quickstart/conf.py_t
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
Labels: bug

#4809 Update package classifiers
  setup.py
Labels: refactoring

#4839 Fix mypy violations
  sphinx/builders/_epub_base.py
  sphinx/theming.py
Labels: refactoring

#4827 Fix #4784: latex_show_urls assigns incorrect footnote numbers
  CHANGES
  sphinx/builders/latex.py
  sphinx/transforms/references.py
  tests/test_build_latex.py
Labels: bug, latex

#4834 Ensure set object descriptions are reproducible.
  AUTHORS
  sphinx/util/inspect.py
  tests/test_util_inspect.py
Labels: autodoc, proposal

#4844 Fix #4767: html: search highlighting breaks mathjax equations
  CHANGES
  sphinx/ext/jsmath.py
  sphinx/ext/mathjax.py
  sphinx/themes/basic/static/doctools.js_t
  tests/test_ext_math.py
Labels: extensions, html search

#4838 Sort .hhp file list
  sphinx/builders/htmlhelp.py
Labels: builder

#4854 Update CHANGES for #4771
  CHANGES
Labels: docs

#4849 Fix toctree directive tries to glob for URL having query_string
  CHANGES
  sphinx/directives/other.py
  tests/roots/test-toctree-glob/index.rst
  tests/test_directive_other.py
Labels: bug, markup, toctree

#4842 Fix #4828: Allow to override numfig_format partially
  CHANGES
  sphinx/config.py
Labels: config, domains:std

#4810 Proposal: Define priority for transforms
  sphinx/application.py
Labels: docs, proposal

#4833 doc: Add ImageConverter to utils
  doc/ext/imgconverter.rst
  doc/extdev/utils.rst
  sphinx/transforms/post_transforms/images.py
Labels: docs

#4871 Fixed the German HTML search again, this time from the 1.7 branch
  sphinx/search/de.py
Labels: bug, html search

#4840 Remove substitution_definition nodes from doctree on reading phase (refs: #4827)
  CHANGES
  sphinx/builders/latex/__init__.py
  sphinx/io.py
  sphinx/transforms/references.py
  sphinx/writers/latex.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
Labels: refactoring

#4876 Fix #4717: latex: Compilation for German docs failed with LuaLaTeX and XeLaTeX
  CHANGES
  sphinx/writers/latex.py
  tests/test_build_latex.py
Labels: bug, latex

#4881 doc: Remove meaningless spaces
  sphinx/transforms/post_transforms/images.py
Labels: docs

#4875 doc: Add a note for dotfiles on html_static_path (refs: #4859)
  doc/config.rst
Labels: docs

#4884 Fix #4873: Adjust word-break of deprecated-APIs table
  doc/_themes/sphinx13/static/sphinx13.css
  doc/extdev/index.rst
Labels: docs

#4821 Improve warning messages during including (refs: #4818)
  CHANGES
  sphinx/directives/other.py
Labels: markup

#4882 #4459: duplicated labels detector does not work well in parallel build
  CHANGES
  sphinx/domains/c.py
  sphinx/domains/javascript.py
  sphinx/domains/python.py
  sphinx/domains/rst.py
  sphinx/domains/std.py
  sphinx/ext/mathbase.py
Labels: bug, domain

#4891 Fix PyPI link in theming docs
  doc/theming.rst
Labels: docs

#4868 proposed enhancement #4830
  sphinx/texinputs/sphinx.sty
  sphinx/writers/latex.py
  tests/test_markup.py
Labels: latex, proposal

#4893 Fix #4885: jsdomain also crashed with duplicated objects
  CHANGES
  sphinx/domains/javascript.py
Labels: bug, domains:js

#4892 Fix #4889: latex: sphinx.writers.latex causes recusrive import
  CHANGES
  sphinx/writers/latex.py
Labels: bug, latex

#4903 Revert #4882; f4f693eff7b081785cc5704a6ff22cf0371355f3
  sphinx/domains/c.py
  sphinx/domains/javascript.py
  sphinx/domains/python.py
  sphinx/domains/rst.py
  sphinx/domains/std.py
  sphinx/ext/mathbase.py
Labels: bug, domain

#4912 Fix typo: remove space before full stop
  sphinx/templates/quickstart/conf.py_t
Labels: config

#4910 Show warnings for deprecated html_search_options
  doc/config.rst
  doc/extdev/index.rst
  sphinx/search/ja.py
Labels: config, html search

#4773 Refactor config
  CHANGES
  doc/extdev/index.rst
  sphinx/application.py
  sphinx/builders/latex/__init__.py
  sphinx/config.py
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/ifconfig.py
  sphinx/ext/jsmath.py
  tests/roots/test-config/conf.py
  tests/roots/test-root/conf.py
  tests/roots/test-root/ext.py
  tests/test_application.py
  tests/test_config.py
  tests/test_directive_code.py
Labels: refactoring

#4879 Let docutils know the location of ``docutils.conf`` for Sphinx
  CHANGES
  sphinx/cmd/build.py
  sphinx/environment/__init__.py
  sphinx/setup_command.py
  sphinx/util/docutils.py
  tests/test_docutilsconf.py
Labels: api, apidoc, autodoc, bug, proposal, refactoring
