Repository sphinx-doc/sphinx, pull requests merged in 2018-11, with the labels that each got.

#5580 Fix #5563: latex: footnote_references generated by extension causes LaTeX builder crashed
  CHANGES
  sphinx/builders/latex/transforms.py
Labels: bug, latex

#5581 Fix #5557: quickstart: --no-batchfile isn't honored
  CHANGES
  sphinx/cmd/quickstart.py
Labels: bug, cmdline

#5515 latex: Move \pageautorefname to sphinxmessage.sty
  CHANGES
  doc/extdev/index.rst
  sphinx/templates/latex/latex.tex_t
  sphinx/templates/latex/sphinxmessages.sty_t
  sphinx/writers/latex.py
  tests/test_build_latex.py
Labels: latex, refactoring

#5587 Remove reference to deprecated easy_install
  doc/intl.rst
Labels: docs

#5586 refactor: Move Makefile for texinfo to templates dir
  sphinx/builders/texinfo.py
  sphinx/templates/texinfo/Makefile
Labels: refactoring, texinfo

#5591 Fix type annotations
  sphinx/application.py
  sphinx/builders/__init__.py
  sphinx/directives/other.py
  sphinx/domains/__init__.py
  sphinx/domains/changeset.py
  sphinx/domains/math.py
  sphinx/domains/std.py
  sphinx/environment/adapters/toctree.py
  sphinx/ext/inheritance_diagram.py
  sphinx/ext/jsmath.py
  sphinx/ext/mathjax.py
  sphinx/io.py
  sphinx/registry.py
  sphinx/util/math.py
  sphinx/util/typing.py
Labels: bug, test

#5525 [1.8] Revert "Builder.build: save env also with only new documents"
  sphinx/builders/__init__.py
Labels: bug

#5583 LaTeX: add styling to general index, similar to domain indices
  sphinx/texinputs/python.ist
  sphinx/texinputs/sphinx.sty
  sphinx/texinputs/sphinx.xdy
  sphinx/writers/latex.py
  tests/test_build_latex.py
Labels: bug, latex

#5600 Fix #3080: multiline rubrics and citations are broken in texinfo builder
  CHANGES
  sphinx/writers/texinfo.py
  tests/roots/test-markup-citation/conf.py
  tests/roots/test-markup-citation/index.rst
  tests/roots/test-markup-rubric/conf.py
  tests/roots/test-markup-rubric/index.rst
  tests/test_build_texinfo.py
Labels: bug, texinfo

#5590 Move language-specific data into a new JS file, language_data.js
  doc/conf.py
  sphinx/builders/html.py
  sphinx/themes/basic/static/documentation_options.js_t
  sphinx/themes/basic/static/language_data.js_t
  sphinx/themes/basic/static/searchtools.js
Labels: bug, html search

#5608 test: Replace call_autodoc() by do_autodoc()
  tests/test_autodoc.py
Labels: refactoring, test

#5612 Remove use six.move module
  sphinx/application.py
  sphinx/builders/linkcheck.py
  sphinx/cmd/quickstart.py
  sphinx/ext/intersphinx.py
  sphinx/util/__init__.py
  sphinx/util/requests.py
  sphinx/versioning.py
Labels: refactoring

#5609 test: Filter warnings on testing
  tests/test_application.py
  tests/test_autodoc.py
  tests/test_util_i18n.py
  tests/test_util_images.py
Labels: refactoring, test

#5625 Remove dead code `or '.'`
  tests/conftest.py
Labels: refactoring

#5624 Correct type annotation to remove 'type: ignore' comment
  sphinx/testing/util.py
Labels: refactoring

#5619 Fix #5614: autodoc: incremental build is broken when builtin modules …
  CHANGES
  sphinx/util/__init__.py
  tests/test_util.py
Labels: autodoc, bug

#5626 Deprecate sphinx.util.pycompat.u
  CHANGES
  doc/extdev/index.rst
  sphinx/util/jsdump.py
  sphinx/util/pycompat.py
Labels: refactoring

#5613 Simplify tox configuration with 'extras' option
  tox.ini
Labels: proposal, test

#5622 Fix "invalid escape sequence" warnings emitted during tests
  tests/test_quickstart.py
Labels: refactoring

#5606 Fix type annotations for RoleFunction
  sphinx/domains/__init__.py
  sphinx/util/typing.py
Labels: bug, refactoring

#5610 Refactor std domain: Add add_object() and add_program_option()
  sphinx/domains/std.py
Labels: domains:std, refactoring

#5632 Use super() in SphinxJSONEncoder
  sphinx/util/jsonimpl.py
Labels: refactoring

#5621 Fix all BytesWarning identified through tests
  sphinx/builders/html.py
  tests/test_setup_command.py
Labels: refactoring

#5628 Fix #5627: index.html missing in QtHelp
  CHANGES
  sphinx/builders/qthelp.py
Labels: bug, builder

#5630 LaTeX: compatibility with caption package
  CHANGES
  sphinx/templates/latex/longtable.tex_t
  sphinx/templates/latex/tabular.tex_t
  sphinx/templates/latex/tabulary.tex_t
  sphinx/texinputs/sphinx.sty
  tests/roots/test-latex-table/expects/longtable_having_caption.tex
  tests/roots/test-latex-table/expects/table_having_caption.tex
Labels: bug, latex

#5642 Drop explicit dependency: typed_ast
  setup.py
Labels: test

#5639 Fix two nits with the TextBuilder class
  sphinx/writers/text.py
Labels: refactoring, text

#5596 Simplify XRefRole constructor
  sphinx/roles.py
Labels: markup, refactoring

#5638 Add a handler to migrate master_doc from "contents" to "index" (refs: #5385)
  sphinx/config.py
Labels: config

#5649 Fix type annotations for LaTeX writer
  sphinx/writers/latex.py
Labels: refactoring

#5651 Add better type annotations to writers
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
Labels: refactoring

#5650 Add IndexEntry class to represent an entry of indices
  sphinx/builders/html.py
  sphinx/domains/__init__.py
  sphinx/domains/python.py
  sphinx/writers/latex.py
  sphinx/writers/texinfo.py
Labels: refactoring

#5655 doc: Add deprecation info to script_files (template variable)
  doc/templating.rst
Labels: bug, docs

#5645 LaTeX: support for Greek and Cyrillic
  CHANGES
  doc/conf.py
  doc/usage/builders/index.rst
  doc/usage/configuration.rst
  sphinx/templates/latex/latex.tex_t
  sphinx/texinputs/sphinx.xdy
  sphinx/texinputs/sphinxcyrillic.sty
  sphinx/util/texescape.py
  sphinx/writers/latex.py
  tests/test_markup.py
Labels: bug, latex

#5663 Fix annotations for registry, roles and util.nodes
  sphinx/registry.py
  sphinx/roles.py
  sphinx/util/nodes.py
Labels: bug

#5667 Fix typehints for domains
  sphinx/domains/__init__.py
  sphinx/domains/c.py
  sphinx/domains/changeset.py
  sphinx/domains/cpp.py
  sphinx/domains/javascript.py
  sphinx/domains/math.py
  sphinx/domains/python.py
  sphinx/domains/rst.py
  sphinx/domains/std.py
Labels: bug

#5672 Fix typehints: sphinx.ext.autodoc
  sphinx/ext/autodoc/directive.py
Labels: refactoring

#5673 Fix annotations of directives.patches
  sphinx/directives/patches.py
Labels: refactoring

#5674 Fix annotations for writers
  Makefile
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
Labels: refactoring

#5671 Fix SphinxBaseReader.get_transform() refers an attribute of subclasses
  sphinx/io.py
Labels: bug

#5669 Fix #5659: linkcheck: crashes for a hyperlink containing multibyte character
  CHANGES
  sphinx/util/__init__.py
  tests/test_util.py
Labels: bug, builder

#5668 Fix #5648: NodeMatcher matches Text node on attribute match
  sphinx/util/nodes.py
  tests/test_util_nodes.py
Labels: bug, i18n

#5676 Fix annotaions for extensions
  sphinx/ext/autosectionlabel.py
  sphinx/ext/doctest.py
  sphinx/ext/graphviz.py
  sphinx/ext/ifconfig.py
  sphinx/ext/imgmath.py
  sphinx/ext/inheritance_diagram.py
  sphinx/ext/intersphinx.py
  sphinx/ext/jsmath.py
  sphinx/ext/mathjax.py
  sphinx/ext/todo.py
  sphinx/ext/viewcode.py
Labels: refactoring

#5682 Fix annotations for directives
  sphinx/directives/__init__.py
  sphinx/directives/code.py
  sphinx/directives/other.py
  sphinx/directives/patches.py
  sphinx/util/typing.py
Labels: refactoring

#5680 Fix annotations for builders
  sphinx/builders/__init__.py
  sphinx/builders/_epub_base.py
  sphinx/builders/epub3.py
  sphinx/builders/html.py
  sphinx/builders/htmlhelp.py
  sphinx/builders/latex/__init__.py
  sphinx/builders/latex/transforms.py
  sphinx/builders/linkcheck.py
  sphinx/builders/manpage.py
  sphinx/builders/texinfo.py
Labels: refactoring

#5686 Fix annotations for writers
  sphinx/writers/html.py
  sphinx/writers/html5.py
Labels: refactoring

#5687 Fix annotations for util
  sphinx/directives/__init__.py
  sphinx/util/__init__.py
  sphinx/util/docfields.py
  sphinx/util/docutils.py
  sphinx/util/math.py
  sphinx/util/nodes.py
  sphinx/util/smartypants.py
Labels: refactoring

#5689 Refactor metadata collector
  sphinx/environment/collectors/metadata.py
  tests/roots/test-metadata/conf.py
  tests/roots/test-metadata/index.rst
  tests/roots/test-root/index.txt
  tests/test_metadata.py
Labels: environment, refactoring

#5690 Refactor sphinx.search
  CHANGES
  doc/extdev/index.rst
  sphinx/search/__init__.py
Labels: refactoring

#5691 Fix annotations for extensions
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/autosummary/generate.py
  sphinx/ext/doctest.py
  sphinx/ext/graphviz.py
  sphinx/ext/inheritance_diagram.py
  sphinx/ext/intersphinx.py
  sphinx/ext/todo.py
Labels: refactoring
