Repository sphinx-doc/sphinx, pull requests merged in 2018-06, with the labels that each got.

#5043 doc: Fix widths of table
  sphinx/application.py
Labels: docs

#5044 docs: Fix location of attributes
  doc/extdev/appapi.rst
Labels: bug, docs

#5025 Fix #5017: old displaymath node makes writers crashed
  sphinx/transforms/post_transforms/compat.py
Labels: bug, extensions

#5031 Fix script tag for old styled JS file
  sphinx/builders/html.py
Labels: bug, html, html theme

#5040 Fix: #5037
  sphinx/writers/latex.py
  tests/test_build_latex.py
Labels: bug, latex

#5030 Fix sphinx.testing uses deprecated pytest API; Node.get_marker(name)
  CHANGES
  sphinx/testing/fixtures.py
  tests/test_ext_apidoc.py
  tests/test_setup_command.py
Labels: test

#5028 Fix #5016: ``character_level_inline_markup`` setting is not initialized
  CHANGES
  sphinx/environment/__init__.py
Labels: bug

#5024 Fix #5022: latex: crashed with docutils package provided by Debian/Ubuntu
  CHANGES
  sphinx/writers/latex.py
Labels: bug

#5055 Update CHANGES (reorder, fix typos)
  CHANGES
  doc/extdev/index.rst
Labels: docs

#5052 Fix #5016: crashed when recommonmark.AutoStrictify is enabled
  CHANGES
  sphinx/environment/__init__.py
  sphinx/io.py
Labels: bug, extensions

#5012 Fix #5009: latex: a label for table is vanished if table does not have a caption
  CHANGES
  sphinx/templates/latex/longtable.tex_t
  sphinx/templates/latex/tabular.tex_t
  sphinx/templates/latex/tabulary.tex_t
  tests/roots/test-latex-table/expects/longtable_having_widths.tex
  tests/roots/test-latex-table/expects/table_having_widths.tex
  tests/roots/test-latex-table/longtable.rst
  tests/roots/test-latex-table/tabular.rst
Labels: bug, latex

#5050 Fix #5048: crashed with numbered toctree
  CHANGES
  sphinx/environment/collectors/toctree.py
  tests/test_toctree.py
Labels: bug, toctree

#5049 html: Output ``canonical_url`` metadata if :confval:`html_baseurl` set
  CHANGES
  doc/usage/configuration.rst
  sphinx/builders/html.py
  sphinx/themes/basic/layout.html
  tests/test_build_html.py
Labels: config, enhancement, html

#5060 LaTeX, follow-up to PR #5012, avoid label separated by pagebreak
  sphinx/templates/latex/tabular.tex_t
  sphinx/templates/latex/tabulary.tex_t
  tests/roots/test-latex-table/expects/table_having_widths.tex
Labels: bug, latex

#5045 Remove usage of internal shorthandoff variable from LaTeX writer
  CHANGES
  doc/extdev/index.rst
  doc/usage/configuration.rst
  sphinx/writers/latex.py
  tests/test_build_latex.py
Labels: latex

#5034 Add :confval:`html_js_files`
  CHANGES
  doc/usage/configuration.rst
  sphinx/application.py
  sphinx/builders/html.py
  sphinx/registry.py
  tests/roots/test-html_assets/conf.py
  tests/test_build_html.py
Labels: config, html, proposal

#5061 Fix mypy violation
  sphinx/directives/code.py
Labels: refactoring

#5029 autosummary: expose inherited_members to template
  doc/ext/autosummary.rst
  sphinx/ext/autosummary/generate.py
Labels: autodoc, proposal

#4667 cpp domain: Fix assert when describing undefined symbol.
  sphinx/domains/cpp.py
Labels: bug, domains:cpp

#5069 Update Python 2 doc links to Python 3
  doc/conf.py
  doc/usage/restructuredtext/directives.rst
  sphinx/ext/napoleon/iterators.py
Labels: docs

#5021 Deprecate builder.script_files (refs: #4439)
  CHANGES
  sphinx/builders/html.py
  sphinx/themes/basic/search.html
  sphinx/themes/bizstyle/layout.html
  sphinx/themes/classic/layout.html
  sphinx/themes/scrolls/layout.html
Labels: api, html theme

#5065 Fix #5064: KeyError on literal_block in new Latex transform
  sphinx/builders/latex/transforms.py
Labels: bug, latex

#5068 Fix #5019: autodoc: crashed by Form Feed Character
  CHANGES
  sphinx/pycode/parser.py
  tests/test_pycode_parser.py
Labels: autodoc, bug

#5082 Fix mathjax is not loaded
  sphinx/ext/jsmath.py
  sphinx/ext/mathjax.py
Labels: bug, extensions, html

#5067 Fix #5032: autodoc loses the first staticmethod parameter for old styled classes
  CHANGES
  sphinx/util/inspect.py
  tests/test_util_inspect.py
Labels: autodoc, bug

#5086 Add PROS to Examples List
  EXAMPLES
Labels: docs

#5059 Fix #5036: quickstart: Typing Ctrl-U clears the whole of line
  CHANGES
  sphinx/cmd/quickstart.py
  sphinx/util/console.py
Labels: bug, cmdline

#5087 Update Google style guide link (previous link deprecated)
  doc/ext/autodoc.rst
Labels: docs

#5098 Update CHANGES (see #5000)
  CHANGES
Labels: docs

#5084 Close #3784: mathjax: Add :confval:`mathjax_options`
  CHANGES
  doc/ext/math.rst
  sphinx/ext/mathjax.py
  tests/test_ext_math.py
Labels: enhancement, extensions

#5083 Fixed internationalization quick guide
  doc/intl.rst
Labels: bug, cmdline, docs

#5101 Fix #5100: Fix HTML search has been broken
  sphinx/themes/basic/search.html
  sphinx/themes/bizstyle/layout.html
  sphinx/themes/classic/layout.html
  sphinx/themes/scrolls/layout.html
Labels: bug, html search

#5085 Fix #4362: latex: Don't overwrite .tex file if document not changed
  CHANGES
  sphinx/builders/latex/__init__.py
  sphinx/util/docutils.py
  tests/test_util_docutils.py
Labels: enhancement, latex

#5094 Fix #5066: html: "relations" sidebar is not shown by default
  CHANGES
  sphinx/builders/html.py
  tests/test_build_html.py
Labels: bug, html theme

#5095 Fix #5091: latex: curly braces in index entries are not handled correctly
  CHANGES
  sphinx/writers/latex.py
  tests/test_build_latex.py
Labels: bug, latex

#5108 Alabaster 0.711
  CHANGES
  doc/make.bat
  sphinx/builders/html.py
  sphinx/writers/latex.py
  tests/test_build_html.py
  tests/test_build_latex.py
  tests/test_theming.py
Labels: test

#5102 doc: Use badge to show latest release
  doc/_templates/indexsidebar.html
  doc/_themes/sphinx13/static/sphinx13.css
Labels: docs

#5097 Close #5035: qthelp builder allows dashes in :confval:`qthelp_namespace`
  CHANGES
  sphinx/builders/qthelp.py
  tests/test_build_qthelp.py
Labels: builder

#5107 Fix #5070: epub: Wrong internal href fragment links
  CHANGES
  sphinx/builders/_epub_base.py
  tests/roots/test-epub-anchor-id/conf.py
  tests/roots/test-epub-anchor-id/index.rst
  tests/test_build_epub.py
Labels: bug, epub

#5106 Fix #5104: apidoc: Interface of ``sphinx.apidoc:main()`` has changed
  CHANGES
  sphinx/apidoc.py
Labels: api, apidoc, bug

#5096 doc: update URL of PDF and EPUB
  doc/_templates/index.html
Labels: docs

#5001 Close #1431: latex: Add alphanumeric enumerated list support
  CHANGES
  sphinx/writers/latex.py
  tests/test_build_latex.py
Labels: enhancement, latex, markup

#5115 Update napoleon docs with features from #4613
  AUTHORS
  CHANGES
  doc/ext/napoleon.rst
Labels: docs, extensions:napoleon

#5123 doc: fix func/meth references to Sphinx
  doc/extdev/parserapi.rst
  doc/usage/configuration.rst
  doc/usage/restructuredtext/roles.rst
  sphinx/application.py
Labels: docs

#5120 doc: fix list with add_object_type
  sphinx/application.py
Labels: bug, docs

#5111 Run everything but unit tests under Python 3
  .travis.yml
  Makefile
  doc/Makefile
  sphinx/builders/qthelp.py
  sphinx/directives/other.py
  sphinx/writers/latex.py
  tox.ini
Labels: test
