Repository sphinx-doc/sphinx, pull requests merged in 2018-02, with the labels that each got.

#4571 Fix i18n: message catalogs are not compiled when specific build (refs: #4560)
  CHANGES
  sphinx/builders/__init__.py
  tests/test_catalogs.py
Labels: bug, builder, i18n

#4589 Fix condition for deprecation warning
  sphinx/application.py
Labels: api, bug

#4592 Fix #4581: apidoc: Excluded modules still included
  CHANGES
  sphinx/ext/apidoc.py
  tests/test_ext_apidoc.py
Labels: apidoc, bug

#4597 Fix #4596: TypeError: issubclass() arg 1 must be a class
  sphinx/application.py
Labels: api, bug

#4610 Fix #4608: epub: Invalid meta tag is generated
  CHANGES
  sphinx/builders/epub3.py
  sphinx/themes/basic/layout.html
Labels: bug, epub

#4607 fix broken contributor page links on pypi page
  README.rst
Labels: docs

#4603 Fix indentation
  sphinx/application.py
Labels: bug, docs

#4601 docs: protect and unprotect the stable branch on releasing
  utils/release-checklist
Labels: docs

#4599 Fix #4260: autodoc: keyword only argument separator is not disappeared
  CHANGES
  sphinx/util/inspect.py
  tests/conftest.py
  tests/py3/test_util_inspect_py3.py
Labels: autodoc, bug

#4387 Napoleon: custom section headers
  CHANGES
  sphinx/ext/napoleon/__init__.py
  sphinx/ext/napoleon/docstring.py
  tests/test_ext_napoleon_docstring.py
Labels: extensions:napoleon

#4622 key changes to 'scheme' in epub3 opf template
  sphinx/templates/epub3/content.opf_t
Labels: bug, epub

#4612 Use roots/basic for test_latex_logo_if_not_found
  tests/test_build_latex.py
Labels: latex, test

#4633 Docs: Templating: Small wording fix
  doc/templating.rst
Labels: docs

#4629 test: allows to drop 0.05% coverages
  .codecov.yml
Labels: test

#4621 Fix #4617: quickstart: PROJECT_DIR argument is required
  CHANGES
  sphinx/cmd/quickstart.py
Labels: bug, cmdline

#4626 docs: Use literal for commands
  utils/release-checklist
Labels: bug, docs

#4638 doc: Fix markup
  utils/release-checklist
Labels: bug, docs

#4624 Fix #4623: sphinx.build_main no longer exists in 1.7.0
  CHANGES
  sphinx/__init__.py
  sphinx/apidoc.py
  sphinx/quickstart.py
Labels: bug, cmdline

#4636 autosummary: Fix compatibility of get_documenter() API (refs: #4366)
  CHANGES
  sphinx/application.py
  sphinx/ext/autosummary/__init__.py
  sphinx/util/compat.py
Labels: autodoc, bug

#4634 Fix #4630: Have order on msgids in sphinx.pot deterministic
  sphinx/builders/gettext.py
  tests/roots/test-gettext-template/_templates/template1.html
  tests/roots/test-gettext-template/_templates/template2.html
  tests/roots/test-gettext-template/conf.py
  tests/roots/test-gettext-template/contents.rst
  tests/test_build_gettext.py
Labels: bug, builder, i18n

#4637 Fix #4563: autosummary: Incorrect end of line punctuation detection
  CHANGES
  sphinx/ext/autosummary/__init__.py
  tests/test_ext_autosummary.py
Labels: autodoc, bug

#4639 Fix #4577: Enumerated sublists with explicit start with wrong number
  CHANGES
  sphinx/writers/latex.py
  tests/roots/test-nested-enumerated-list/conf.py
  tests/roots/test-nested-enumerated-list/index.rst
  tests/test_build_latex.py
Labels: bug, latex

#4647 doc: Fix markup
  utils/release-checklist
Labels: docs

#4646 doc: create htmlhelp section
  doc/config.rst
Labels: docs

#4642 test: Run epubcheck as a testing
  tests/test_build.py
  tests/test_build_epub.py
Labels: epub, test

#4650 Use typing.TYPE_CHECKING (in master)
  sphinx/__init__.py
  sphinx/apidoc.py
  sphinx/ext/autosectionlabel.py
  sphinx/ext/extlinks.py
  sphinx/ext/githubpages.py
  sphinx/ext/jsmath.py
  sphinx/ext/mathjax.py
  sphinx/quickstart.py
  sphinx/search/da.py
  sphinx/search/de.py
  sphinx/search/es.py
  sphinx/search/fi.py
  sphinx/search/fr.py
  sphinx/search/hu.py
  sphinx/search/it.py
  sphinx/search/nl.py
  sphinx/search/no.py
  sphinx/search/pt.py
  sphinx/search/ru.py
  sphinx/search/sv.py
  sphinx/testing/path.py
Labels: refactoring

#4625 Add app.phase to let components know the current build phase
  sphinx/application.py
  sphinx/builders/__init__.py
  sphinx/util/build_phase.py
Labels: refactoring

#4644 Fix #4641: A external link in TOC cannot contain "?" with ``:glob:`` option
  CHANGES
  sphinx/directives/other.py
  tests/roots/test-toctree-glob/index.rst
  tests/test_environment_toctree.py
Labels: bug, toctree

#4657 Adjust .codecov.yml (again)
  .codecov.yml
Labels: test

#4652 Fix flake8 violations
  tests/test_ext_napoleon_docstring.py
Labels: refactoring

#4658 Fix incomplete localization strings in Polish (refs: #4655)
  sphinx/locale/pl/LC_MESSAGES/sphinx.po
Labels: bug, i18n

#4661 Typo: cocstring => docstring
  doc/ext/autodoc.rst
Labels: bug, docs

#4594 Change interface of add_source_parser() and add add_source_suffix()
  CHANGES
  doc/extdev/appapi.rst
  doc/extdev/parserapi.rst
  sphinx/application.py
  sphinx/parsers.py
  sphinx/registry.py
  sphinx/transforms/i18n.py
  tests/roots/test-add_source_parser-conflicts-with-users-setting/conf.py
  tests/roots/test-add_source_parser-conflicts-with-users-setting/source_parser.py
  tests/roots/test-add_source_parser/conf.py
  tests/roots/test-add_source_parser/source_parser.py
  tests/roots/test-prolog/prolog_markdown_parser.py
  tests/roots/test-root/conf.py
  tests/test_application.py
Labels: api, refactoring

#4605 Migrate registry
  CHANGES
  sphinx/application.py
  sphinx/builders/__init__.py
  sphinx/builders/latex.py
  sphinx/domains/std.py
  sphinx/registry.py
  sphinx/util/docutils.py
  sphinx/util/typing.py
  tests/test_domain_std.py
  tests/test_util_docutils.py
Labels: refactoring

#4640 Show opt:scheme attribute only for EPUB3.1 (refs: #4622)
  sphinx/builders/epub3.py
  sphinx/templates/epub3/content.opf_t
Labels: bug, epub

#4665 Fix #4664: Reading objects.inv fails again
  CHANGES
  sphinx/ext/intersphinx.py
  tests/test_ext_intersphinx.py
Labels: bug, extensions

#4666 Fix #4662: any refs with term targets crash when an ambiguity is encountered
  CHANGES
  sphinx/transforms/post_transforms/__init__.py
Labels: bug, domains:std

#4620 Proposal: Add a mention for sphinx-users group to ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE.md
Labels: docs, proposal

#4631 Move sphinx.cmdline to sphinx.cmd.build
  CHANGES
  sphinx/__init__.py
  sphinx/__main__.py
  sphinx/cmd/build.py
  sphinx/cmdline.py
Labels: refactoring

#4673 #4188 update quickstart doc
  doc/man/sphinx-quickstart.rst
Labels: docs

#4671 Document: showing links & targets of Intersphinx mapping file
  doc/ext/intersphinx.rst
Labels: docs

#4668 Move env.update() to Builder class
  CHANGES
  sphinx/builders/__init__.py
  sphinx/environment/__init__.py
  tests/test_builder.py
  tests/test_environment.py
  tests/test_intl.py
Labels: environment, refactoring
