Repository sphinx-doc/sphinx, pull requests merged in 2019-11, with the labels that each got.

#6790 :art: Fixed issue #6789
  doc/_static/Makefile
  doc/_static/translation.png
  doc/_static/translation.puml
  doc/usage/advanced/intl.rst
Labels: bug, docs

#6775 Close #6762: latex: Allow to load additonal LaTeX packages
  CHANGES
  doc/latex.rst
  sphinx/templates/latex/latex.tex_t
  sphinx/writers/latex.py
  tests/test_build_latex.py
Labels: enhancement, latex

#6756 Close #1331: Change default User-Agent header
  CHANGES
  doc/usage/configuration.rst
  sphinx/builders/linkcheck.py
  sphinx/config.py
  sphinx/ext/intersphinx.py
  sphinx/util/requests.py
Labels: bug

#6799 LaTeX: Allow linebreaks at \ (in literals, code-blocks, parsed-literal)
  CHANGES
  doc/latex.rst
  sphinx/texinputs/sphinx.sty
Labels: bug, latex

#6822 add urls to Code and Issue tracker for PyPi
  setup.py
Labels: proposal

#6802 gettext: Use template file to generate message catalog
  CHANGES
  doc/extdev/deprecated.rst
  sphinx/builders/gettext.py
  sphinx/templates/gettext/message.pot_t
Labels: i18n, refactoring

#6807 LaTeX: fix #6804
  CHANGES
  sphinx/texinputs/sphinx.sty
Labels: bug, latex

#6810 LaTeX: fix #6809
  CHANGES
  sphinx/texinputs/sphinx.sty
Labels: bug, latex

#6825 Fetch `intersphinx` inventories concurrently
  AUTHORS
  CHANGES
  sphinx/ext/intersphinx.py
Labels: enhancement, extensions

#6750 Fix #6738: Do not replace unicode characters by LaTeX macros on unicode supported LaTeX engine
  CHANGES
  sphinx/util/template.py
  sphinx/util/texescape.py
  sphinx/writers/latex.py
  tests/roots/test-latex-unicode/conf.py
  tests/roots/test-latex-unicode/index.rst
  tests/test_build_latex.py
Labels: bug, latex

#6832 Fix #6738: latex: literal_block does not support raw unicode characters
  sphinx/highlighting.py
  sphinx/util/texescape.py
  sphinx/writers/latex.py
  tests/test_markup.py
Labels: bug, latex

#6833 Fix #6738: Use get_encode_func in todo extension
  sphinx/ext/todo.py
Labels: bug, extensions, latex

#6835 LaTeX: escape fewer Unicode chars if engine is lualatex or xelatex
  CHANGES
  sphinx/util/texescape.py
Labels: bug, latex

#6814 Shorten message on search page
  sphinx/themes/basic/search.html
Labels: html search

#6795 Fix #6793: texinfo: Code examples broken following "sidebar"
  CHANGES
  sphinx/writers/texinfo.py
Labels: bug, texinfo

#6801 Close #2546: apidoc: .so file support
  CHANGES
  sphinx/ext/apidoc.py
Labels: apidoc, enhancement

#6784 Close #4683: i18n: make explicit titles in toctree translatable
  CHANGES
  sphinx/addnodes.py
  tests/roots/test-intl/toctree.txt
  tests/roots/test-intl/xx/LC_MESSAGES/toctree.po
  tests/test_intl.py
Labels: enhancement, i18n

#6840 Fix link to pygments lexer in docs
  doc/usage/restructuredtext/directives.rst
Labels: bug, docs

#6836 Fix #6813: An orphan warning is emitted for included document on Windows
  CHANGES
  sphinx/project.py
Labels: bug, markup

#6834 Reconsider public APIs of sphinx.util.texescape
  CHANGES
  doc/extdev/deprecated.rst
  sphinx/builders/latex/__init__.py
  sphinx/ext/todo.py
  sphinx/highlighting.py
  sphinx/util/template.py
  sphinx/util/texescape.py
  sphinx/writers/latex.py
  tests/test_build_latex.py
Labels: latex, refactoring

#6846 LaTeX: Do not escape € wrongly (refs: 0103ff2a2b6, #6835)
  sphinx/writers/latex.py
Labels: bug, latex

#6845 LaTeX: stop escaping | to LaTeX macro, except if in an index entry
  sphinx/util/texescape.py
  sphinx/writers/latex.py
  tests/test_build_latex.py
Labels: latex

#6851 Fix the URL to https://pygments.org/docs/lexers.html
  doc/usage/configuration.rst
Labels: docs

#6849 README: remove stray "__"
  README.rst
Labels: bug, docs

#6850 Fix misplaced flags in re.sub() call
  sphinx/util/smartypants.py
Labels: bug

#6841 Fix #4186: LaTeX: Support upLaTeX as a new latex_engine (experimental)
  CHANGES
  doc/usage/configuration.rst
  sphinx/builders/latex/__init__.py
  sphinx/texinputs/Makefile_t
  sphinx/texinputs/latexmkjarc_t
  sphinx/writers/latex.py
Labels: enhancement, latex

#6839 Fix #6806: linkcheck: Failure on parsing content
  CHANGES
  sphinx/builders/linkcheck.py
Labels: bug, builder

#6844 6824 fix search js bug
  CHANGES
  sphinx/themes/basic/static/searchtools.js
Labels: bug, html search

#6817 Close #6798: autosummary: emit ``autodoc-skip-member`` event on generating stub file
  CHANGES
  doc/usage/extensions/autosummary.rst
  sphinx/ext/autosummary/generate.py
  tests/roots/test-ext-autosummary-skip-member/conf.py
  tests/roots/test-ext-autosummary-skip-member/index.rst
  tests/roots/test-ext-autosummary-skip-member/target.py
  tests/test_ext_autosummary.py
Labels: autosummary, enhancement

#6854 DOC: add Greek to list of supported languages
  doc/usage/configuration.rst
Labels: docs

#6816 Add linkcheck_auth option
  CHANGES
  doc/usage/configuration.rst
  sphinx/builders/linkcheck.py
  tests/test_build_linkcheck.py
Labels: builder, enhancement

#6735 Migrate to py3 style type annotation: sphinx.writers
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
  sphinx/writers/xml.py
Labels: refactoring

#6862 Update supported languages (refs: #6854)
  doc/usage/configuration.rst
Labels: docs, i18n

#6852 Fix #6848: config.py shouldn't pop extensions from overrides
  CHANGES
  sphinx/config.py
Labels: bug, config

#6866 doc: URL of numpydoc has changed
  doc/usage/extensions/napoleon.rst
Labels: api, docs, extensions:napoleon

#6874 Fix mypy violations (for mypy-0.750)
  setup.py
  sphinx/pycode/parser.py
Labels: refactoring

#6869 Fix #6867: text: extra spaces are inserted to hyphenated words on folding lines
  CHANGES
  sphinx/writers/text.py
  tests/test_build_text.py
  tests/test_intl.py
Labels: bug, text
