Repository sphinx-doc/sphinx, pull requests merged in 2019-08, with the labels that each got.

#6621 Fix #6620: i18n: classifiers of definition list are not translated with docutils-0.15
  CHANGES
  sphinx/util/nodes.py
Labels: bug, i18n

#6578 Fix autodoc: autodoc_member_order_does not refer order of imports (refs: #6574)
  CHANGES
  sphinx/pycode/parser.py
  tests/test_pycode_parser.py
Labels: autodoc, bug, enhancement

#6609 Fix #6606: Update jQuery to 3.4.1
  sphinx/themes/basic/static/jquery-3.4.1.js
  sphinx/themes/basic/static/jquery.js
  tests/test_theming.py
Labels: bug, html theme

#6593 Test with docutils-0.14 (previous release)
  .travis.yml
  tox.ini
Labels: test

#6592 Fix #6589: autodoc: Formatting issues with autodoc_typehints='none'
  CHANGES
  sphinx/util/inspect.py
  tests/test_ext_autodoc_configs.py
  tests/test_util_inspect.py
Labels: autodoc, bug

#6576 Fix autodoc: missing type annotation for variadic and keyword parameters (refs: #6574)
  CHANGES
  sphinx/util/inspect.py
  tests/test_util_inspect.py
  tests/typing_test_data.py
Labels: autodoc, bug

#6649 Update configuration.rst
  doc/usage/configuration.rst
Labels: docs

#6624 Fix #6474: ``DocFieldTransformer`` raises AttributeError
  CHANGES
  sphinx/util/docfields.py
Labels: bug, markup

#6419 ENH: Explain rebuilds
  sphinx/builders/__init__.py
  sphinx/environment/__init__.py
  tests/test_environment.py
Labels: cmdline, proposal

#6657 Fix #6605: autodoc: crashed when target code contains custom method-like objects
  CHANGES
  sphinx/util/inspect.py
Labels: autodoc, bug

#6625 Fix field lists after switch to HTML5 writer
  sphinx/themes/basic/static/basic.css_t
  sphinx/themes/bizstyle/static/bizstyle.css_t
  sphinx/themes/classic/static/classic.css_t
Labels: bug, html theme

#6309 refactor: SphinxStandaloneReader should not hold an application object
  CHANGES
  doc/extdev/deprecated.rst
  sphinx/io.py
  sphinx/testing/restructuredtext.py
  sphinx/transforms/i18n.py
Labels: refactoring
