Repository sphinx-doc/sphinx, pull requests merged in 2019-07, with the labels that each got.

#6541 Migrate to py3 style type annotation: sphinx.ext (Part 2)
  sphinx/ext/autosectionlabel.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/autosummary/generate.py
  sphinx/ext/doctest.py
  sphinx/ext/ifconfig.py
  sphinx/ext/imgmath.py
  sphinx/ext/inheritance_diagram.py
  sphinx/ext/jsmath.py
  sphinx/ext/napoleon/__init__.py
  sphinx/ext/napoleon/docstring.py
  sphinx/ext/napoleon/iterators.py
  sphinx/ext/todo.py
  sphinx/ext/viewcode.py
Labels: refactoring

#6552 Migrate to py3 style type annotation: sphinx.environment
  sphinx/environment/__init__.py
  sphinx/environment/adapters/asset.py
  sphinx/environment/adapters/indexentries.py
  sphinx/environment/adapters/toctree.py
  sphinx/environment/collectors/__init__.py
  sphinx/environment/collectors/asset.py
  sphinx/environment/collectors/dependencies.py
  sphinx/environment/collectors/indexentries.py
  sphinx/environment/collectors/metadata.py
  sphinx/environment/collectors/title.py
  sphinx/environment/collectors/toctree.py
  sphinx/util/__init__.py
Labels: refactoring

#6542 refactor: Separate HTMLBuilder.copy_static_files() to sub methods
  sphinx/builders/html.py
Labels: html, refactoring

#6540 Fix #736: Invalid sort in pair index
  CHANGES
  sphinx/environment/adapters/indexentries.py
  tests/test_environment_indexentries.py
Labels: bug, html, i18n

#6554 Migrate to py3 style type annotation: sphinx.pycode
  sphinx/pycode/__init__.py
  sphinx/pycode/parser.py
Labels: refactoring

#6555 Migrate to py3 style type annotation: sphinx.testing
  sphinx/testing/fixtures.py
  sphinx/testing/path.py
  sphinx/testing/restructuredtext.py
  sphinx/testing/util.py
Labels: refactoring

#6529 format_date(): use "aware" local datetime by default (refs: #6528)
  sphinx/util/i18n.py
Labels: bug, i18n

#6422 Fix #247: autosummary: Add autosummary_generate_option to overwrite old stub file
  CHANGES
  doc/usage/extensions/autosummary.rst
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/autosummary/generate.py
  tests/test_ext_autosummary.py
Labels: autosummary, enhancement

#6494 Close #5592: option directive registers an index entry for each comma separated option
  CHANGES
  sphinx/domains/std.py
  tests/test_domain_std.py
Labels: domains:std, enhancement

#6557 docs: Update FAQ for github pages
  doc/faq.rst
Labels: docs

#6553 Fix #6549: sphinx-build: Escaped characters in error messages
  CHANGES
  sphinx/cmd/build.py
Labels: bug, cmdline

#6547 Fix #6545. Strip doctests for doctest_block nodes.
  sphinx/transforms/post_transforms/code.py
  tests/roots/test-trim_doctest_flags/index.rst
  tests/test_transforms_post_transforms_code.py
Labels: bug

#6575 Fix mypy violations (for mypy-0.720)
  setup.py
  sphinx/ext/doctest.py
  sphinx/ext/intersphinx.py
  sphinx/pycode/parser.py
  sphinx/roles.py
  sphinx/testing/util.py
  sphinx/util/__init__.py
  sphinx/util/docutils.py
  sphinx/util/inspect.py
  sphinx/writers/text.py
Labels: refactoring

#6571 Fix #6567: autodoc: autodoc_inherit_docstrings does not effect to __init__()
  CHANGES
  sphinx/ext/autodoc/__init__.py
  tests/roots/test-ext-autodoc/target/autoclass_content.py
  tests/test_ext_autodoc_configs.py
Labels: autodoc, bug

#6563 Fix #6561: glossary: Wrong hyperlinks are generated for non alphanumeric terms
  CHANGES
  sphinx/domains/std.py
  tests/test_domain_std.py
  tests/test_environment_indexentries.py
Labels: bug, domains:std

#6579 Fix type annotation for python 3.5.1
  sphinx/application.py
  sphinx/builders/__init__.py
  sphinx/builders/gettext.py
  sphinx/builders/html.py
  sphinx/builders/xml.py
  sphinx/deprecation.py
  sphinx/domains/__init__.py
  sphinx/domains/python.py
  sphinx/domains/std.py
  sphinx/environment/collectors/toctree.py
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autodoc/directive.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/autosummary/generate.py
  sphinx/ext/doctest.py
  sphinx/ext/napoleon/docstring.py
  sphinx/io.py
  sphinx/parsers.py
  sphinx/project.py
  sphinx/registry.py
  sphinx/roles.py
  sphinx/search/__init__.py
  sphinx/transforms/i18n.py
  sphinx/util/__init__.py
  sphinx/util/docfields.py
  sphinx/util/docutils.py
  sphinx/util/logging.py
  sphinx/util/nodes.py
  sphinx/util/osutil.py
Labels: bug, refactoring

#6577 Update npm packages
  package-lock.json
  package.json
Labels: test

#6580 refactor: sphinx.util.inspect:Signature.format_annotation_old()
  sphinx/util/inspect.py
Labels: autodoc, refactoring
