Repository sphinx-doc/sphinx, pull requests merged in 2019-03, with the labels that each got.

#6116 Fix #6067: latexpdf image :target: changes output
  CHANGES
  sphinx/writers/latex.py
  tests/roots/test-images/index.rst
  tests/test_build_latex.py
Labels: bug, latex

#6122 Fix texinfo: ``make install-info`` fails
  CHANGES
  sphinx/templates/texinfo/Makefile
Labels: bug, texinfo

#6128 test: replace emph_literal_role() by EmphasizedLiteral
  tests/test_roles.py
Labels: test

#6126 Fix #5391: A cross reference in heading is rendered as literal
  CHANGES
  sphinx/transforms/__init__.py
Labels: bug, toctree

#6123 Fix #3079: texinfo: image files are not copied on ``make install-info``
  CHANGES
  sphinx/builders/texinfo.py
  sphinx/templates/texinfo/Makefile
  sphinx/writers/texinfo.py
Labels: bug, texinfo

#6133 Clean up import for annotations
  sphinx/builders/__init__.py
  sphinx/builders/_epub_base.py
  sphinx/builders/epub3.py
  sphinx/builders/latex/__init__.py
  sphinx/builders/latex/transforms.py
  sphinx/builders/linkcheck.py
  sphinx/config.py
  sphinx/directives/__init__.py
  sphinx/directives/other.py
  sphinx/domains/javascript.py
  sphinx/domains/math.py
  sphinx/domains/python.py
  sphinx/environment/__init__.py
  sphinx/environment/collectors/asset.py
  sphinx/environment/collectors/metadata.py
  sphinx/environment/collectors/title.py
  sphinx/environment/collectors/toctree.py
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autodoc/directive.py
  sphinx/ext/autodoc/importer.py
  sphinx/ext/autosectionlabel.py
  sphinx/ext/autosummary/generate.py
  sphinx/ext/coverage.py
  sphinx/ext/doctest.py
  sphinx/ext/imgmath.py
  sphinx/ext/inheritance_diagram.py
  sphinx/ext/intersphinx.py
  sphinx/ext/mathbase.py
  sphinx/highlighting.py
  sphinx/io.py
  sphinx/jinja2glue.py
  sphinx/locale/__init__.py
  sphinx/pycode/parser.py
  sphinx/setup_command.py
  sphinx/testing/util.py
  sphinx/theming.py
  sphinx/transforms/post_transforms/compat.py
  sphinx/util/__init__.py
  sphinx/util/docfields.py
  sphinx/util/docutils.py
  sphinx/util/images.py
  sphinx/util/inventory.py
  sphinx/util/logging.py
  sphinx/util/nodes.py
  sphinx/util/osutil.py
  sphinx/util/pycompat.py
  sphinx/writers/xml.py
Labels: refactoring

#6137 Fix #6136: ``:name:`` option for ``math`` directive causes a crash
  CHANGES
  sphinx/directives/patches.py
Labels: bug, markup

#6130 docs: JS domain does not support reset current module
  doc/usage/restructuredtext/domains.rst
Labels: docs

#6129 Refactor util.nodes
  CHANGES
  doc/extdev/index.rst
  sphinx/directives/code.py
  sphinx/directives/other.py
  sphinx/directives/patches.py
  sphinx/domains/changeset.py
  sphinx/ext/doctest.py
  sphinx/ext/ifconfig.py
  sphinx/ext/todo.py
  sphinx/util/docutils.py
  sphinx/util/nodes.py
Labels: refactoring

#6141 C++, fix alias declarations, causing problems in Latex and singlehtml
  CHANGES
  sphinx/domains/cpp.py
Labels: bug, domains:cpp, latex

#6144 Fix AttributeError in sphinx.builders.latex
  sphinx/builders/latex/__init__.py
Labels: bug, latex

#6143 Fix #6140: Use unittest.mock instead of mock
  CHANGES
  setup.py
  sphinx/domains/cpp.py
  tests/test_build.py
  tests/test_config.py
  tests/test_domain_js.py
  tests/test_domain_py.py
  tests/test_domain_std.py
  tests/test_environment_indexentries.py
  tests/test_ext_autosummary.py
  tests/test_ext_intersphinx.py
  tests/test_ext_napoleon.py
  tests/test_ext_napoleon_docstring.py
  tests/test_highlighting.py
  tests/test_roles.py
  tests/test_util.py
  tests/test_util_fileutil.py
Labels: refactoring, test

#6148 Fixed a bug in intersphinx failure reporting
  sphinx/ext/intersphinx.py
Labels: bug, extensions

#6135 Fix UnboundLocalError when building changes (1.8)
  sphinx/builders/changes.py
  tests/roots/test-changes/base.rst
  tests/roots/test-changes/c-api.rst
  tests/roots/test-changes/conf.py
  tests/roots/test-changes/contents.rst
  tests/roots/test-changes/library/utils.rst
  tests/test_build.py
  tests/test_build_changes.py
Labels: bug, builder

#6151 Fix AssertionError is raised for custom citation_reference node (refs: #6147)
  CHANGES
  sphinx/transforms/__init__.py
  tests/test_build_html.py
Labels: bug

#6153 Use bionic (py36) on Circle CI
  .circleci/config.yml
  tests/roots/test-ext-imgconverter/svgimg.svg
  tests/roots/test-images/subdir/svgimg.svg
  tests/roots/test-images/subdir/svgimg.xx.svg
  tests/roots/test-root/svgimg.svg
  tests/roots/test-warnings/svgimg.svg
Labels: test

#6155 Move list of deprecated API to extdev/deprecated.rst
  doc/extdev/deprecated.rst
  doc/extdev/index.rst
Labels: docs

#6142 Fix doc typo.
  doc/usage/restructuredtext/domains.rst
Labels: docs

#6156 Update comment for patch to Element.copy()
  sphinx/util/nodes.py
Labels: docs

#6125 doc: Enhance documentation about internalization of external extension (refs: #5991)
  doc/extdev/i18n.rst
  doc/extdev/index.rst
  sphinx/locale/__init__.py
Labels: docs, i18n

#5991 doc: Enhance documentation about internalization of external extension.
  doc/extdev/index.rst
  sphinx/locale/__init__.py
Labels: docs

#6152 Fix #6149: LaTeX: :index: role titles causes build error of LaTeX
  CHANGES
  sphinx/builders/latex/__init__.py
  sphinx/builders/latex/transforms.py
  tests/roots/test-index_on_title/conf.py
  tests/roots/test-index_on_title/contents.rst
  tests/test_build_latex.py
Labels: bug, latex

#6132 Closes #2155: Support ``code`` directive
  CHANGES
  sphinx/directives/__init__.py
  sphinx/directives/patches.py
  sphinx/testing/restructuredtext.py
  tests/test_directive_other.py
  tests/test_directive_patch.py
Labels: bug, markup

#6159 Fix #3859: manpage: code-block captions are not displayed correctly
  CHANGES
  sphinx/writers/manpage.py
  tests/test_build_manpage.py
Labels: bug, man

#6160 pretty changes for 2.0
  sphinx/writers/manpage.py
  tests/test_build_latex.py
Labels: refactoring

#6158 refactor CitationReferences transform
  sphinx/io.py
  sphinx/transforms/__init__.py
Labels: refactoring

#6162 Add long description content type
  setup.py
  utils/release-checklist
Labels: refactoring

#6176 docs: drop mention to deprecated method (refs: #6174)
  sphinx/application.py
Labels: bug, docs

#6183 C++, fix parsing of initializers
  CHANGES
  sphinx/domains/cpp.py
  tests/test_domain_cpp.py
Labels: domains:cpp

#6157 refactor: Remove lists of transforms from SphinxStandalonReader
  sphinx/application.py
  sphinx/io.py
  sphinx/transforms/__init__.py
  sphinx/transforms/compact_bullet_list.py
  sphinx/transforms/i18n.py
  sphinx/transforms/references.py
  sphinx/versioning.py
Labels: refactoring

#6180 Support --keep-going with BuildDoc setup command
  sphinx/cmd/build.py
  sphinx/setup_command.py
Labels: proposal

#6154 Add SphinxPostTransform class
  CHANGES
  doc/extdev/deprecated.rst
  doc/extdev/utils.rst
  sphinx/builders/latex/__init__.py
  sphinx/builders/latex/transforms.py
  sphinx/transforms/post_transforms/__init__.py
Labels: api, proposal

#6161 Deprecate imports for compatibility
  CHANGES
  doc/extdev/deprecated.rst
  sphinx/directives/__init__.py
Labels: refactoring

#6177 Fix #6172: AttributeError is raised for old styled index nodes
  CHANGES
  sphinx/util/compat.py
Labels: bug

#6184 Fix #6178: i18n: Captions missing in translations for hidden TOCs
  CHANGES
  sphinx/builders/gettext.py
  tests/roots/test-intl/index.po
  tests/roots/test-intl/index.txt
  tests/test_intl.py
Labels: bug, i18n, toctree

#6194 Add testcase for sphinx.domains.python
  tests/test_domain_py.py
Labels: domains:py, test

#6192 Add ObjectDescription.get_field_type_map()
  CHANGES
  doc/extdev/deprecated.rst
  sphinx/directives/__init__.py
  sphinx/util/docfields.py
Labels: domain, refactoring

#6195 Add an incompatible change entry (refs: #6186)
  CHANGES
Labels: docs

#6198 Fix #6196: py domain: unexpected prefix is generated
  CHANGES
  sphinx/domains/python.py
  tests/test_domain_py.py
Labels: bug, domains:py

#6197 ``math`` directive does not support ``:class:`` option
  CHANGES
  sphinx/directives/patches.py
Labels: enhancement, markup

#6199 refactor PyObject class
  sphinx/domains/python.py
Labels: refactoring

#6205 Drop tests for deprecated modules
  tests/roots/test-changes/c-api.rst
  tests/test_util_i18n.py
Labels: refactoring, test

#6204 ``todo`` directive now supports ``:name:`` option
  CHANGES
  sphinx/ext/todo.py
  tests/test_ext_todo.py
Labels: extensions

#6215 Clarify MathJax extension usage
  doc/usage/extensions/math.rst
Labels: docs

#6206 Refactoring glossary directive
  sphinx/domains/std.py
  tests/test_domain_std.py
Labels: domains:std, markup, refactoring

#6224 Show deprecation warnings
  CHANGES
  sphinx/application.py
  sphinx/ext/viewcode.py
  sphinx/util/osutil.py
  tests/test_ext_inheritance_diagram.py
Labels: bug

#6223 Drop features and APIs deprecated in 1.8
  CHANGES
  doc/extdev/appapi.rst
  sphinx/addnodes.py
  sphinx/application.py
  sphinx/builders/html.py
  sphinx/builders/latex/util.py
  sphinx/cmdline.py
  sphinx/config.py
  sphinx/deprecation.py
  sphinx/domains/changeset.py
  sphinx/domains/math.py
  sphinx/domains/python.py
  sphinx/domains/std.py
  sphinx/environment/__init__.py
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autodoc/importer.py
  sphinx/ext/autodoc/mock.py
  sphinx/ext/mathbase.py
  sphinx/ext/viewcode.py
  sphinx/highlighting.py
  sphinx/io.py
  sphinx/locale/__init__.py
  sphinx/make_mode.py
  sphinx/registry.py
  sphinx/search/ja.py
  sphinx/transforms/post_transforms/compat.py
  sphinx/util/__init__.py
  sphinx/util/compat.py
  sphinx/util/docutils.py
  sphinx/util/i18n.py
  sphinx/util/images.py
  sphinx/util/inspect.py
  sphinx/util/osutil.py
  sphinx/versioning.py
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
  tests/roots/test-add_source_parser/conf.py
  tests/roots/test-ext-math-compat/conf.py
  tests/test_application.py
  tests/test_autodoc.py
  tests/test_ext_autodoc_mock.py
  tests/test_util_images.py
Labels: refactoring

#6230 refactor: test_environment_indexentries
  tests/test_environment_indexentries.py
Labels: refactoring, test

#6232 Enable CLI override of Makefile variables.
  sphinx/templates/quickstart/Makefile.new_t
Labels: cmdline, enhancement

#6234 Update type annotations for python domain
  sphinx/directives/__init__.py
  sphinx/domains/python.py
Labels: domains:py, refactoring

#6231 Fix #6230: Inappropriate node_id has been generated by glossary directive
  CHANGES
  sphinx/domains/std.py
  tests/test_environment_indexentries.py
Labels: bug, markup
