Repository sphinx-doc/sphinx, pull requests merged in 2019-01, with the labels that each got.

#5875 A happy new year! (for master branch)
  sphinx/project.py
  tests/test_parser.py
  tests/test_project.py
  tests/test_util_pycompat.py
Labels: refactoring

#5873 Update annotations for autosummary
  sphinx/ext/autosummary/__init__.py
Labels: refactoring

#5879 encoding keyword for path.text() and path.write_text() is no longer needed
  tests/test_build_gettext.py
  tests/test_build_html.py
  tests/test_build_text.py
  tests/test_config.py
  tests/test_directive_code.py
  tests/test_docutilsconf.py
  tests/test_ext_viewcode.py
  tests/test_intl.py
  tests/test_templating.py
  tests/test_toctree.py
Labels: refactoring, test

#5878 refactor: Add compat module to avoid recursive import
  sphinx/builders/latex/__init__.py
  sphinx/builders/latex/compat.py
  sphinx/deprecation.py
  sphinx/writers/latex.py
Labels: latex, refactoring

#5747 Remove unused `except UnicodeDecodeError` block
  sphinx/environment/__init__.py
Labels: refactoring

#5883 Remove use of deprecated APIs
  sphinx/builders/changes.py
  sphinx/ext/autosummary/__init__.py
  sphinx/testing/util.py
  tests/test_ext_apidoc.py
  tests/test_io.py
  tests/test_markup.py
Labels: refactoring

#5882 Fix HTML: Invalid HTML5 file is generated for glossary (refs: #4611)
  CHANGES
  sphinx/writers/html.py
  sphinx/writers/html5.py
  tests/test_markup.py
Labels: bug, html

#5516 Move labels related with numfig_format to sphinxmessage.sty
  CHANGES
  doc/extdev/index.rst
  sphinx/builders/latex/__init__.py
  sphinx/builders/latex/compat.py
  sphinx/builders/latex/util.py
  sphinx/templates/latex/latex.tex_t
  sphinx/templates/latex/sphinxmessages.sty_t
  sphinx/writers/latex.py
  tests/test_build_latex.py
  tests/test_markup.py
Labels: latex, refactoring

#5891 LaTeX: obey spaces from `numfig_format` (figure and table only)
  CHANGES
  sphinx/writers/latex.py
  tests/test_build_latex.py
Labels: bug, latex

#5895 Fix warning message when a node class is already registered
  sphinx/application.py
Labels: api

#5894 LaTeX: fix ``addtocaptions`` for sphinxmessages.sty_t if 'babel' empty
  sphinx/builders/latex/__init__.py
  tests/test_build_latex.py
Labels: bug, latex

#5896 C++ fixes
  CHANGES
  sphinx/domains/cpp.py
  tests/test_domain_cpp.py
Labels: domains:cpp

#5899 Remove outdated fallback to 'import Image'
  doc/usage/configuration.rst
  sphinx/builders/_epub_base.py
  sphinx/util/images.py
Labels: refactoring

#5881 refactor: Use repr() to make escaped string in template for conf.py
  sphinx/cmd/quickstart.py
  sphinx/templates/quickstart/conf.py_t
Labels: config, refactoring

#5904 Update CONTRIBUTING.rst
  CONTRIBUTING.rst
Labels: docs

#5907 Fix #5906: LaTeX Builder is not initialized correctly on test_markup
  tests/test_markup.py
Labels: bug, test

#5903 refactor: deprecate some pycompat functions
  CHANGES
  doc/extdev/index.rst
  sphinx/transforms/i18n.py
  sphinx/util/pycompat.py
Labels: refactoring

#5384 quickstart: Simplify generated conf.py (for latex)
  CHANGES
  sphinx/builders/latex/__init__.py
  sphinx/templates/quickstart/conf.py_t
  tests/roots/test-builder-gettext-dont-rebuild-mo/conf.py
  tests/roots/test-epub-anchor-id/conf.py
  tests/roots/test-ext-graphviz/conf.py
  tests/roots/test-ext-math-simple/conf.py
  tests/roots/test-ext-math/conf.py
  tests/roots/test-ext-todo/conf.py
  tests/roots/test-glossary/conf.py
  tests/roots/test-latex-labels/conf.py
  tests/roots/test-latex-table/conf.py
  tests/roots/test-maxlistdepth/conf.py
  tests/roots/test-nested-enumerated-list/conf.py
  tests/roots/test-refonly_bullet_list/conf.py
  tests/roots/test-root/conf.py
  tests/roots/test-smartquotes/conf.py
  tests/roots/test-toctree/conf.py
  tests/roots/test-trim_doctest_flags/conf.py
  tests/roots/test-warnings/conf.py
  tests/test_build_latex.py
  tests/test_directive_code.py
  tests/test_ext_autosummary.py
  tests/test_ext_graphviz.py
  tests/test_ext_imgconverter.py
  tests/test_ext_inheritance_diagram.py
  tests/test_ext_math.py
  tests/test_ext_todo.py
  tests/test_quickstart.py
  tests/test_smartquotes.py
  tests/test_transforms_post_transforms_code.py
Labels: config, latex, proposal

#5912 Make info messages more translatable
  sphinx/builders/__init__.py
  sphinx/builders/_epub_base.py
  sphinx/builders/changes.py
  sphinx/builders/html.py
  sphinx/builders/latex/__init__.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/intersphinx.py
  sphinx/ext/viewcode.py
  sphinx/writers/latex.py
Labels: i18n, refactoring

#5918 LaTeX: no need for \sphinxVerbatimEnvironment (refactoring)
  sphinx/texinputs/sphinx.sty
Labels: latex, refactoring

#5917 Fix ToC: Move "Intro" to first entry
  doc/contents.rst
Labels: docs

#5926 Fix doc: html_baseurl was added in 1.8.0
  doc/usage/configuration.rst
Labels: bug, docs

#5922 Fix recursive import when importing sphinx.writers.latex directly
  sphinx/builders/latex/compat.py
  sphinx/writers/latex.py
Labels: bug, latex

#5920 Refactor applehelp builder
  sphinx/builders/applehelp.py
  sphinx/templates/applehelp/_access.html_t
Labels: builder, refactoring

#5910 Refactor epub builder: deprecate arguments of build_* method.
  CHANGES
  doc/extdev/index.rst
  sphinx/builders/_epub_base.py
  sphinx/builders/epub3.py
Labels: refactoring

#5919 [DOC] Move description of latex_elements to latex.rst
  doc/latex.rst
  doc/usage/configuration.rst
Labels: docs, latex, refactoring

#5901 C++, alias directive
  CHANGES
  doc/usage/restructuredtext/domains.rst
  sphinx/domains/cpp.py
Labels: domains:cpp

#5932 Fix an error with pytest-4.x
  tests/test_websupport.py
Labels: bug, test

#5921 Move SingleFileHTMLBuilder to sphinx.builders.singlehtml package
  CHANGES
  doc/extdev/index.rst
  sphinx/application.py
  sphinx/builders/html.py
  sphinx/builders/singlehtml.py
Labels: html, refactoring

#5931 Fix #5928: KeyError: 'DOCUTILSCONFIG' when running build
  CHANGES
  sphinx/util/docutils.py
Labels: bug, cmdline

#5937 Fix QtHelp: OS dependent path separator is used in .qhp file
  CHANGES
  sphinx/builders/qthelp.py
Labels: bug, builder

#5886 Separate jsmath to sphinxcontrib package
  CHANGES
  doc/extdev/index.rst
  setup.py
  sphinx/ext/jsmath.py
  tests/roots/test-root/conf.py
  tests/test_build_html.py
  tests/test_ext_math.py
Labels: extensions, refactoring

#5933 Fix parse eggfile on windows
  CHANGES
  sphinx/pycode/__init__.py
Labels: autodoc, bug

#5911 env.set_versioning_method() allows callable object as a method
  sphinx/environment/__init__.py
Labels: environment, proposal

#5944 Fix test: NamedTemporaryFile causes errors on Windows
  tests/test_util_pycompat.py
Labels: bug, test

#5935 Add progress_message() as a helper for progress messages
  sphinx/application.py
  sphinx/util/__init__.py
Labels: cmdline, proposal

#5939 LaTeX: \sphinxsafeincludegraphics for sphinxShadowBox/sphinxheavybox
  CHANGES
  sphinx/texinputs/sphinx.sty
Labels: bug, latex

#5945 Fix #5231: "make html" does not read and build "po" files in "locale" dir
  CHANGES
  sphinx/util/matching.py
Labels: bug, i18n

#5265 WIP: 5258 fix search highlight svg ff
  package-lock.json
  sphinx/themes/basic/static/doctools.js
  tests/js/doctools.js
Labels: bug

#5930 Use subprocess.run() instead of Popen()
  sphinx/__init__.py
  sphinx/ext/graphviz.py
  sphinx/ext/imgconverter.py
  sphinx/ext/imgmath.py
  sphinx/testing/fixtures.py
  tests/test_build_epub.py
  tests/test_build_gettext.py
  tests/test_build_latex.py
  tests/test_build_texinfo.py
Labels: refactoring

#5902 Stop to use $SPHINX_TEST_TEMPDIR envvar
  CHANGES
  sphinx/testing/fixtures.py
  tests/conftest.py
  tox.ini
Labels: refactoring, test

#5949 Remove assets for websupport (refs: #4064)
  sphinx/themes/basic/static/ajax-loader.gif
  sphinx/themes/basic/static/comment-bright.png
  sphinx/themes/basic/static/comment-close.png
  sphinx/themes/basic/static/comment.png
  sphinx/themes/basic/static/down-pressed.png
  sphinx/themes/basic/static/down.png
  sphinx/themes/basic/static/up-pressed.png
  sphinx/themes/basic/static/up.png
  tests/test_build_qthelp.py
Labels: bug, websupport

#5951 Drop feature: websupport
  CHANGES
  setup.py
  sphinx/application.py
  sphinx/builders/websupport.py
  sphinx/environment/__init__.py
  sphinx/themes/basic/static/websupport.js
  sphinx/util/websupport.py
  sphinx/writers/websupport.py
Labels: refactoring

#5955 LaTeX: remove usage of \scalebox by incorporating scale in height/width
  CHANGES
  sphinx/writers/latex.py
  tests/test_build_latex.py
Labels: bug, latex

#5969 refactoring progress messages
  sphinx/builders/__init__.py
  sphinx/builders/gettext.py
  sphinx/builders/html.py
  sphinx/builders/latex/__init__.py
  sphinx/builders/linkcheck.py
  sphinx/builders/singlehtml.py
  sphinx/builders/texinfo.py
  sphinx/ext/viewcode.py
  sphinx/util/__init__.py
  sphinx/util/nodes.py
  tests/test_util.py
Labels: refactoring

#5972 applehelp: refactor with progress_message()
  sphinx/builders/applehelp.py
Labels: refactoring

#5975 Fix #5966: mathjax has not been loaded on incremental build
  CHANGES
  sphinx/ext/mathjax.py
Labels: bug, extensions

#5976 Fix #5959: classifier delimiter is not shown
  sphinx/themes/basic/static/basic.css_t
Labels: bug, html

#5978 Fix #5958: versionadded directive causes crash with Python 3.5.0
  CHANGES
  sphinx/domains/changeset.py
Labels: bug

#5971 refactor: compile .mo file only if needed on testing
  tests/test_intl.py
Labels: refactoring, test

#3944 add support for partial matches in js search
  CHANGES
  sphinx/themes/basic/static/documentation_options.js_t
  sphinx/themes/basic/static/searchtools.js
Labels: html search, proposal

#5979 #4649
  CHANGES
  sphinx/themes/basic/static/searchtools.js
Labels: html search
