Repository sphinx-doc/sphinx, pull requests merged in 2021-12, with the labels that each got.

#9928 doc: Fix autodoc extension example
  doc/development/tutorials/examples/autodoc_intenum.py
Labels: bug, docs

#9910 Fix typos
  CHANGES
  EXAMPLES
  tests/test_extension.py
Labels: bug, docs

#9852 New Sphinx tutorial, part IV
  doc/conf.py
  doc/tutorial/deploying.rst
  doc/tutorial/index.rst
Labels: enhancement, docs

#9929 Prevent line wrapping in literals
  CHANGES
  sphinx/themes/basic/static/basic.css_t
Labels: bug, html theme

#9937 Fixes statement typo
  doc/usage/installation.rst
Labels: bug, api

#9918 C, C++: fundamental type parsing
  CHANGES
  sphinx/domains/c.py
  sphinx/domains/cpp.py
  tests/test_domain_c.py
  tests/test_domain_cpp.py
Labels: bug, domains:c, domains:cpp

#9948 doc: Improve autodoc extension example
  doc/development/tutorials/examples/autodoc_intenum.py
Labels: docs, refactoring

#9894 Proof on principle: linkcheck exclude matched documents
  CHANGES
  doc/usage/configuration.rst
  sphinx/builders/linkcheck.py
  tests/roots/test-linkcheck-documents_exclude/br0ken_link.rst
  tests/roots/test-linkcheck-documents_exclude/broken_link.rst
  tests/roots/test-linkcheck-documents_exclude/conf.py
  tests/roots/test-linkcheck-documents_exclude/index.rst
  tests/test_build_linkcheck.py
Labels: proposal, linkcheck

#9942 tox: support coverage on win32
  tox.ini
Labels: bug, test

#9949 LaTeX: prohibit also with xelatex linebreaks at dashes in literal text (not code-blocks) (fixes #9925)
  CHANGES
  sphinx/texinputs/sphinxlatexliterals.sty
  sphinx/texinputs/sphinxlatexstyletext.sty
Labels: bug, latex

#9391 texinfo: improve variable in :samp: directives
  sphinx/writers/texinfo.py
  tests/test_build_texinfo.py
Labels: proposal, texinfo

#9578 texinfo: simplify reference emission.
  doc/_static/conf.py.txt
  doc/faq.rst
  doc/usage/configuration.rst
  sphinx/builders/texinfo.py
  sphinx/writers/texinfo.py
  tests/test_build_texinfo.py
Labels: enhancement, texinfo

#9931 Close #9075: autodoc: Add a config variable autodoc_unqualified_typehints
  CHANGES
  doc/usage/extensions/autodoc.rst
  sphinx/domains/python.py
  sphinx/ext/autodoc/__init__.py
  sphinx/util/inspect.py
  sphinx/util/typing.py
  tests/test_domain_py.py
  tests/test_ext_autodoc_configs.py
  tests/test_util_inspect.py
  tests/test_util_typing.py
Labels: enhancement, autodoc

#9953 Fix #9947: i18n: topic directive having a bullet list can't be translatable
  CHANGES
  sphinx/transforms/__init__.py
  sphinx/util/nodes.py
Labels: bug, i18n

#9793 Set multiprocessing start method to `fork`
  sphinx/application.py
  sphinx/util/parallel.py
  tests/test_util_logging.py
Labels: cmdline, proposal

#9958 Fix #9108: docs: Use default pygments_theme to get accessiblity
  doc/_themes/sphinx13/theme.conf
Labels: bug, docs

#9390 texinfo: fix emission of @footnote directives.
  sphinx/writers/texinfo.py
  tests/test_build_texinfo.py
Labels: bug, texinfo

#9941 Fix Multi-function declaration in Python domain has cramped vertical spacing in latexpdf output (#9940)
  CHANGES
  sphinx/texinputs/sphinxlatexobjects.sty
Labels: bug, latex

#9287 Document new irc channel location
  doc/_templates/indexsidebar.html
  doc/internals/contributing.rst
Labels: docs

#9963 doc: Use "console" for the highlight language of console output
  doc/development/theming.rst
  doc/man/sphinx-autogen.rst
  doc/usage/advanced/setuptools.rst
  doc/usage/installation.rst
  doc/usage/quickstart.rst
  doc/usage/theming.rst
Labels: docs

#9957 Reduce DeprecationWarnings
  tests/test_theming.py
  tests/utils.py
Labels: refactoring

#9983 Fix mypy violations (with mypy-0.920)
  setup.py
  sphinx/builders/gettext.py
  sphinx/util/__init__.py
  sphinx/util/inspect.py
  sphinx/util/logging.py
Labels: refactoring

#9966 refactor: Remove RemovedInSphinx50Warning (partially)
  sphinx/builders/latex/__init__.py
  sphinx/directives/__init__.py
  sphinx/domains/c.py
  sphinx/domains/python.py
  sphinx/domains/std.py
  sphinx/util/__init__.py
  sphinx/util/inspect.py
  sphinx/util/osutil.py
  sphinx/util/requests.py
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
  sphinx/writers/texinfo.py
Labels: refactoring

#9982 Fix #9979: Error level messages were displayed as warning messages
  CHANGES
  sphinx/util/logging.py
  tests/test_util_logging.py
Labels: bug

#9986 doc: Update explanation of autodoc_unqualified_typehints (ref: #9931)
  doc/usage/extensions/autodoc.rst
Labels: bug, docs

#9978 Deprecate sphinx.writers.latex.LaTeXWriter.docclasses
  CHANGES
  doc/extdev/deprecated.rst
  sphinx/deprecation.py
  sphinx/writers/latex.py
Labels: refactoring

#9987 Fix #9968: autodoc: ivars are not shown if __init__ has posonlyargs
  CHANGES
  sphinx/pycode/parser.py
  tests/test_pycode.py
Labels: bug, autodoc

#9992 test: Remove debug print
  tests/test_domain_py.py
Labels: bug, test

#10006 Fix a spelling typo in tests (s/änhlich/ähnlich)
  tests/roots/test-glossary/index.rst
  tests/roots/test-root/markup.txt
  tests/test_build_latex.py
Labels: test

#9990 Close #9961: html: Support nested <kbd> HTML elements in other HTML builders
  CHANGES
  sphinx/builders/html/transforms.py
Labels: enhancement, html

#9991 Fix #9962: texinfo: Do not use @definfoenclose to empasize string
  CHANGES
  doc/faq.rst
  sphinx/writers/texinfo.py
Labels: bug, texinfo

#9998 Close #9993: std domain: Allow to refer an inline target via ref role
  CHANGES
  sphinx/domains/std.py
  tests/test_domain_std.py
Labels: enhancement, markup, domains:std

#10010 Fix mypy violations (with mypy-0.930)
  setup.py
  sphinx/environment/__init__.py
  sphinx/util/inspect.py
  sphinx/writers/manpage.py
Labels: refactoring

#9943 drop translator-specific unknown_visit calls
  sphinx/util/docutils.py
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
Labels: proposal, builder

#9999 LaTeX: separate terms from their definitions by a CR (close #9985)
  sphinx/texinputs/sphinxlatexlists.sty
  sphinx/writers/latex.py
  tests/test_build_latex.py
Labels: bug, enhancement, latex

#10007 Replace pkg_resources with importlib.metadata
  setup.py
  sphinx/registry.py
  sphinx/theming.py
Labels: refactoring

#10012 autodoc: Rename autodoc_unqualified_typehints to autodoc_typehints_format (refs: #9931)
  CHANGES
  doc/usage/extensions/autodoc.rst
  sphinx/ext/autodoc/__init__.py
  tests/test_ext_autodoc_configs.py
Labels: autodoc, refactoring

#10019 Fix docs: docs for show_return_annotation param for stringify_signature() is not explained
  sphinx/util/inspect.py
Labels: bug, autodoc, docs

#10017 refactor: docs: Use :param: fields for add_js_file() and add_css_file()
  sphinx/application.py
Labels: docs, refactoring

#9997 Fix #9194: autodoc: types in typing module are not hyperlinked
  CHANGES
  sphinx/domains/python.py
  sphinx/util/inspect.py
  sphinx/util/typing.py
  tests/test_domain_py.py
  tests/test_ext_autodoc_autofunction.py
  tests/test_ext_autodoc_automodule.py
  tests/test_ext_autodoc_configs.py
  tests/test_ext_autodoc_preserve_defaults.py
  tests/test_util_inspect.py
  tests/test_util_typing.py
Labels: bug, autodoc

#10018 Close #10013: html: Allow to change the loading method of JavaScript
  CHANGES
  sphinx/application.py
  tests/test_build_html.py
Labels: bug, enhancement, html, api

#10022 Fix some messages are still not translated
  sphinx/roles.py
  sphinx/util/docfields.py
Labels: bug, i18n

#10011 Fix #10009: autodoc: Crashes if subject raises an error on getdoc()
  CHANGES
  sphinx/ext/autodoc/__init__.py
Labels: bug, autodoc

#10021 Fix #10015: autodoc: autodoc_typehints_format='short' does not work when autodoc_typehints='description'
  CHANGES
  sphinx/domains/python.py
  sphinx/ext/autodoc/typehints.py
  tests/test_domain_py.py
  tests/test_ext_autodoc_configs.py
Labels: bug, autodoc, domains:py, refactoring
