Repository sphinx-doc/sphinx, pull requests merged in 2021-08, with the labels that each got.

#9515 Fix #9504: autodoc: generate incorrect reference to the parent class
  CHANGES
  sphinx/util/typing.py
Labels: autodoc, bug

#9518 Fix autodoc_docstring_signature support for __init__ and __new__
  sphinx/ext/autodoc/__init__.py
  tests/roots/test-ext-autodoc/target/__init__.py
  tests/test_ext_autodoc_configs.py
Labels: autodoc, bug

#9507 Fix #9479: autodoc: Emit a warning if target is a mocked object
  CHANGES
  sphinx/ext/autodoc/__init__.py
Labels: autodoc, enhancement

#9495 Fix #9456: html search: abbreation marks are inserted to the search
  CHANGES
  sphinx/themes/basic/static/searchtools.js
Labels: bug, html search

#9447 HTML Templates: Expose full sphinx version tuple
  doc/templating.rst
  sphinx/builders/html/__init__.py
Labels: html theme, proposal

#9522 Recursively resolve PEP 585 builtins in restify
  sphinx/util/typing.py
  tests/test_util_typing.py
Labels: autodoc, bug

#9538 Fix #9537: autodoc: Some typing.* objects are broken
  CHANGES
  sphinx/util/typing.py
Labels: bug, autodoc

#9528 Fix typo
  doc/usage/installation.rst
Labels: bug, docs

#9527 Fix #9525: tutorial: Wrong condition in recipe.py
  doc/development/tutorials/examples/recipe.py
Labels: bug, docs

#9530 FIX: do not try to compute the boolean value of a numpy array
  sphinx/util/inspect.py
Labels: bug, autodoc

#9542 refactor: Fix typehint for HTMLBuilder.css_files
  sphinx/builders/html/__init__.py
Labels: refactoring

#9541 Updated EXAMPLES
  EXAMPLES
Labels: docs

#9540 Split tutorial in several files
  doc/tutorial/end.rst
  doc/tutorial/first-steps.rst
  doc/tutorial/getting-started.rst
  doc/tutorial/index.rst
  doc/tutorial/more-sphinx-customization.rst
  doc/tutorial/narrative-documentation.rst
Labels: docs

#9543 Fix typo in numfig_format documentation
  doc/usage/configuration.rst
Labels: bug, docs

#9545 Update link to OpenSearch.
  doc/usage/configuration.rst
Labels: docs

#9546 Fix #9267: html theme: CSS and JS files added by theme were loaded twice
  CHANGES
  sphinx/builders/html/__init__.py
Labels: bug, html, html theme

#9547 C, update fundamental types, including GNU extensions
  CHANGES
  sphinx/domains/c.py
  sphinx/domains/cpp.py
  tests/test_domain_c.py
  tests/test_domain_cpp.py
Labels: enhancement, domains:c, domains:cpp

#9553 C++, fix parsing of defaulted function parameters that are function pointers
  CHANGES
  sphinx/domains/cpp.py
  tests/test_domain_cpp.py
Labels: bug, domains:cpp

#9557 Fix test: Tests has been broken with pygments-2.10+
  tests/test_intl.py
Labels: bug, test

#9590 Fix #9589: autodoc: typing.Annotated has wrongly been rendered
  CHANGES
  sphinx/util/typing.py
Labels: bug, autodoc

#9581 Fix typo in autodoc documentation
  doc/usage/extensions/autodoc.rst
Labels: bug, docs

#9565 Check complete ancestry of text nodes for smartquotes eligibility.
  CHANGES
  sphinx/util/nodes.py
  tests/roots/test-smartquotes/index.rst
  tests/roots/test-smartquotes/literals.rst
  tests/test_smartquotes.py
Labels: bug

#9569 Fix #9568: autosummary: summarise overlined sectioned headings correctly
  CHANGES
  sphinx/ext/autosummary/__init__.py
  tests/test_ext_autosummary.py
Labels: bug, autosummary

#9549 Close #9524: test: SphinxTestApp can take ``builddir`` as an argument
  CHANGES
  sphinx/testing/util.py
Labels: enhancement, test

#9591 Fix #9585: py:property directive does not create a hyperlink for types
  CHANGES
  sphinx/domains/python.py
  tests/test_domain_py.py
Labels: bug, domains:py
