Repository sphinx-doc/sphinx, pull requests merged in 2021-07, with the labels that each got.

#9396 Document Python version support
  doc/internals/release-process.rst
Labels: docs

#9398 Update docs for theming
  doc/development/theming.rst
Labels: docs

#9392 Fix quotes in docstring in ext.napoleon
  doc/usage/extensions/napoleon.rst
Labels: bug, docs

#9386 Fix #9384: autodoc_typehints='none' supports typehints for attributes
  CHANGES
  sphinx/ext/autodoc/__init__.py
  tests/roots/test-ext-autodoc/target/typehints.py
  tests/test_ext_autodoc_configs.py
Labels: autodoc, enhancement

#9399 doc: Fix the default value of napoleon_preprocess_types is True
  doc/usage/extensions/napoleon.rst
Labels: bug, docs, extensions:napoleon

#9174 Add `Sphinx.add_html_assets_in_all_pages`
  CHANGES
  sphinx/application.py
  sphinx/ext/mathjax.py
  sphinx/registry.py
  tests/test_ext_math.py
Labels: api, html, proposal

#9353 Fix link to third-party extensions in front page
  doc/_templates/index.html
Labels: docs

#9405 doclinter: Allow anonymous hyperlink target having long URL
  utils/doclinter.py
Labels: docs

#9166 Support containers in LaTeX output.
  sphinx/texinputs/sphinx.sty
  sphinx/texinputs/sphinxlatexcontainers.sty
  sphinx/writers/latex.py
  tests/roots/test-latex-container/conf.py
  tests/roots/test-latex-container/index.rst
  tests/test_build_latex.py
Labels: latex, proposal

#9406 Migrate GitHub issue form with using new bug-report.yml
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: task

#9410 doc: Fix typo in sphinx.locale.get_translation docstring
  sphinx/locale/__init__.py
Labels: bug, docs

#9401 Fix #9387: xml: XML Builder ignores custom visitors
  CHANGES
  sphinx/writers/xml.py
Labels: bug, builder

#9340 Update example to use recommended usage
  doc/usage/restructuredtext/domains.rst
Labels: bug, docs

#9358 Provide more semantic structure for screen-readers
  sphinx/writers/html.py
  sphinx/writers/html5.py
  tests/test_intl.py
Labels: html, proposal, toctree

#9234 Close #6525: linkcheck: Add linkcheck_ignore_redirects and linkcheck_warn_redirects
  CHANGES
  doc/usage/configuration.rst
  sphinx/builders/linkcheck.py
  tests/roots/test-linkcheck-localserver-warn-redirects/conf.py
  tests/roots/test-linkcheck-localserver-warn-redirects/index.rst
  tests/test_build_linkcheck.py
Labels: enhancement, linkcheck

#9417 Lock closed issues and pull requests after a period of inactivity
  .github/workflows/lock.yml
Labels: proposal, task

#9415 Fix #9362: autodoc: AttributeError is raised for a subclass of Tuple[()]
  CHANGES
  sphinx/util/typing.py
  tests/test_util_typing.py
Labels: autodoc, bug

#9425 Fix link to NumPy Docstring Standard
  doc/usage/extensions/autodoc.rst
  doc/usage/extensions/example_numpy.py
  sphinx/ext/napoleon/__init__.py
Labels: bug, docs, extensions:napoleon

#9419 Add xeCJKVerbAddon to default fvset config for Chinese documents
  doc/latex.rst
  sphinx/builders/latex/constants.py
Labels: bug, latex

#9411 Fix #9404: autodoc: autoclass raises TypeError for dict-like object
  CHANGES
  sphinx/util/typing.py
Labels: autodoc, bug

#9225 Add HTML markup to method/function return typehint
  sphinx/writers/html.py
  sphinx/writers/html5.py
  tests/roots/test-html_signaturereturn_icon/conf.py
  tests/roots/test-html_signaturereturn_icon/index.rst
  tests/test_build_html.py
Labels: domains:py, html, proposal

#9299 Allow case-insensitive match of :term: references through intersphinx
  sphinx/ext/intersphinx.py
Labels: bug, extensions:intersphinx

#9440 Fix handling of local paths in html_logo/html_favicon directorives in conf.py
  sphinx/builders/html/__init__.py
  tests/roots/test-local-logo/conf.py
  tests/roots/test-local-logo/images/img.png
  tests/roots/test-local-logo/index.rst
  tests/test_build_html.py
Labels: bug, html

#9448 Fix #9434: Update dependencies for bundled builders
  CHANGES
  setup.py
Labels: bug

#9462 fix link of code of conduct
  doc/_templates/index.html
Labels: docs, usaturned

#9478 Fix testcases that failed in python3.10.0b4
  tests/test_ext_autodoc.py
  tests/test_util_inspect.py
  tests/test_util_typing.py
Labels: bug, test

#9443 Fix test_enum_class with Python 3.10-beta4
  tests/test_ext_autodoc.py
Labels: autodoc, bug, test

#9476 Remove mark-up in Sphinx own docs breaking building it into PDF output
  doc/tutorial/index.rst
Labels: bug, docs, latex, markup

#9474 LaTeX: add some documentation for container support (#9166)
  doc/latex.rst
Labels: docs, latex

#9461 Close #9445: Support class properties
  CHANGES
  doc/usage/restructuredtext/domains.rst
  sphinx/domains/python.py
  sphinx/ext/autodoc/__init__.py
  sphinx/util/inspect.py
  tests/roots/test-ext-autodoc/target/properties.py
  tests/test_domain_py.py
  tests/test_ext_autodoc_autoclass.py
  tests/test_ext_autodoc_autoproperty.py
Labels: autodoc, domains:py, enhancement

#9464 Add support for PEP 585 generics
  sphinx/util/typing.py
  tests/test_util_typing.py
Labels: autodoc, bug

#9467 Fix #9435: linkcheck: Failed to check anchors in github.com
  CHANGES
  sphinx/builders/linkcheck.py
  tests/roots/test-linkcheck/links.txt
  tests/test_build_linkcheck.py
Labels: bug, linkcheck

#9491 Bugfix for HEAD of python-3.10
  CHANGES
  sphinx/util/inspect.py
  sphinx/util/typing.py
Labels: autodoc, bug

#9470 Reviewed all docstrings to improve readability and correctness
  sphinx/application.py
  sphinx/config.py
  sphinx/errors.py
  sphinx/ext/apidoc.py
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autodoc/directive.py
  sphinx/ext/autodoc/importer.py
  sphinx/ext/autosummary/__init__.py
  sphinx/io.py
  sphinx/parsers.py
  sphinx/project.py
  sphinx/pycode/ast.py
  sphinx/pycode/parser.py
  sphinx/registry.py
  sphinx/search/__init__.py
  sphinx/setup_command.py
  sphinx/testing/fixtures.py
  sphinx/theming.py
  sphinx/transforms/__init__.py
  sphinx/transforms/post_transforms/__init__.py
  sphinx/transforms/post_transforms/images.py
  sphinx/util/__init__.py
  sphinx/util/console.py
  sphinx/util/inventory.py
  sphinx/util/logging.py
  sphinx/util/matching.py
  sphinx/util/nodes.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
  sphinx/writers/manpage.py
  sphinx/writers/text.py
Labels: bug, docs

#9488 Fix #9487: autodoc: typehint for cached_property is not shown
  CHANGES
  sphinx/ext/autodoc/__init__.py
  tests/test_ext_autodoc.py
  tests/test_ext_autodoc_autoproperty.py
Labels: autodoc, bug

#9492 doc: Add document for autoproperty directive (refs: #9486)
  doc/usage/extensions/autodoc.rst
Labels: autodoc, bug, docs

#9493 Fix #9436, #9471: autodoc: crashed if autodoc_class_signature = "separated"
  CHANGES
  sphinx/ext/autodoc/__init__.py
Labels: autodoc, bug

#9494 Fix #9456: html search: html_copy_source can't control the search summaries
  CHANGES
  sphinx/themes/basic/static/searchtools.js
Labels: bug, html search

#9503 doc: :manpage: is a role, not a directive
  doc/usage/configuration.rst
Labels: bug, docs

#9498 Fix #9481: autosummary: some warnings contain non-existing filenames
  CHANGES
  sphinx/domains/c.py
  sphinx/domains/cpp.py
  sphinx/ext/autosummary/__init__.py
  sphinx/util/cfamily.py
  sphinx/util/docutils.py
Labels: autosummary, bug, domains:c, domains:cpp

#9513 Fix #9512: sphinx-build: crashed with the HEAD of Python 3.10
  CHANGES
  sphinx/util/typing.py
Labels: autodoc, bug, cmdline

#9509 [autodoc] Fix uncatched exception in get type hints
  sphinx/util/typing.py
Labels: autodoc, bug
