Repository sphinx-doc/sphinx, pull requests merged in 2021-03, with the labels that each got.

#8943 Spanish translation: fix bad substitution templates
  sphinx/locale/es/LC_MESSAGES/sphinx.mo
  sphinx/locale/es/LC_MESSAGES/sphinx.po
Labels: bug, i18n

#8937 Use explicit title instead of <no title> in the title bar of subpages
  sphinx/environment/collectors/title.py
Labels: enhancement, markup

#8951 C++, support spaceship operator
  CHANGES
  sphinx/domains/cpp.py
  tests/test_domain_cpp.py
Labels: domains:cpp, enhancement

#8955 BUG: Fix rebuild regression
  sphinx/builders/html/__init__.py
Labels: bug, html

#8947 Deprecate SphinxComponentRegistry.get_source_input()
  CHANGES
  doc/extdev/deprecated.rst
  sphinx/io.py
  sphinx/registry.py
Labels: refactoring

#8962 Fix py.typed file not being included in source archive
  MANIFEST.in
Labels: bug

#8961 C and C++, fix nested params
  CHANGES
  sphinx/domains/c.py
  sphinx/domains/cpp.py
  tests/test_domain_c.py
  tests/test_domain_cpp.py
Labels: bug, domains:c, domains:cpp

#8957 Fix #8952: Exceptions raised in a Directive cause parallel builds to hang
  CHANGES
  sphinx/util/parallel.py
Labels: bug

#8432 Fix #7119: Show type hint names unqualified when resolving succeeded
  CHANGES
  doc/extdev/nodes.rst
  doc/usage/configuration.rst
  sphinx/addnodes.py
  sphinx/domains/python.py
  sphinx/ext/intersphinx.py
  sphinx/transforms/post_transforms/__init__.py
  sphinx/util/nodes.py
  tests/roots/test-domain-py-python_use_unqualified_type_names/conf.py
  tests/roots/test-domain-py-python_use_unqualified_type_names/index.rst
  tests/test_domain_py.py
  tests/test_ext_intersphinx.py
Labels: domain, domains:py, enhancement

#8958 Fix #8936: LaTeX: A custom LaTeX builder fails with unknown node error
  CHANGES
  sphinx/builders/latex/transforms.py
Labels: bug, latex

#8771 Fix #759: autodoc: Add sphinx.ext.autodoc.preserve_defaults extension
  CHANGES
  doc/usage/extensions/autodoc.rst
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autodoc/preserve_defaults.py
  tests/roots/test-ext-autodoc/target/preserve_defaults.py
  tests/test_ext_autodoc_preserve_defaults.py
Labels: autodoc, enhancement

#8956 i18n: Fix wrong substitution message catalog for el and hr (refs: #8943)
  CHANGES
  sphinx/locale/el/LC_MESSAGES/sphinx.po
  sphinx/locale/hr/LC_MESSAGES/sphinx.po
Labels: bug, i18n

#8965 doc: Update document for autodoc
  doc/usage/extensions/autodoc.rst
Labels: docs, refactoring

#8966 doc: Fix indentation
  doc/usage/extensions/autodoc.rst
Labels: bug, docs

#8968 Fix wrong directive name in warning messages
  sphinx/directives/patches.py
Labels: bug

#8970 Sphinx is available on Chocolatey
  doc/usage/installation.rst
Labels: docs

#8969 Close #8487: csv-table now considers abspath as relpath from srcdir
  CHANGES
  doc/extdev/deprecated.rst
  sphinx/directives/patches.py
  tests/roots/test-directive-csv-table/conf.py
  tests/roots/test-directive-csv-table/example.csv
  tests/roots/test-directive-csv-table/subdir/example.csv
  tests/test_directive_patch.py
Labels: bug, enhancement, markup, proposal

#8976 refactor: Use PEP-526 based variable annotation (sphinx.util)
  sphinx/util/__init__.py
  sphinx/util/cfamily.py
  sphinx/util/console.py
  sphinx/util/docfields.py
  sphinx/util/docstrings.py
  sphinx/util/docutils.py
  sphinx/util/inventory.py
  sphinx/util/jsdump.py
  sphinx/util/logging.py
  sphinx/util/matching.py
  sphinx/util/nodes.py
  sphinx/util/osutil.py
  sphinx/util/parallel.py
  sphinx/util/rst.py
  sphinx/util/texescape.py
Labels: refactoring

#8879 LaTeX: better workaround for a Pygments LaTeXFormatter issue (with Pygments up to 2.7.4)
  CHANGES
  sphinx/builders/latex/__init__.py
  sphinx/highlighting.py
  sphinx/texinputs/sphinx.sty
Labels: bug, latex

#8907 LaTeX: let bookmarks use high default depth
  CHANGES
  doc/changes.rst
  doc/conf.py
  doc/latex.rst
  sphinx/templates/latex/latex.tex_t
  sphinx/texinputs/sphinx.sty
Labels: bug, latex

#8986 Make `conf.py` template use new-style interpshinx
  sphinx/templates/quickstart/conf.py_t
Labels: cmdline, extensions:intersphinx, refactoring

#8984 refactor: Use PEP-526 based variable annotation (sphinx.writers)
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
Labels: refactoring

#7298 py domain: Add py:property directive to describe a property (refs: #7068)
  CHANGES
  doc/usage/restructuredtext/domains.rst
  sphinx/domains/python.py
  tests/roots/test-domain-py/module.rst
  tests/test_domain_py.py
Labels: domains:py, enhancement, refactoring

#8999 C, C++ render fixes
  CHANGES
  sphinx/domains/c.py
  sphinx/domains/cpp.py
Labels: bug, domains:c, domains:cpp

#8996 Fix #7119: autodoc: Broken doctree was generated by builtin_resolver
  sphinx/domains/python.py
Labels: autodoc, bug

#9000 Refactor some internal LaTeX code
  sphinx/texinputs/sphinxlatexliterals.sty
Labels: latex

#8997 LaTeX: improve behavious of `\pysigline` and `\pysiglinewithargsret` in case of multi-line signature
  CHANGES
  sphinx/texinputs/sphinxlatexobjects.sty
Labels: bug, latex

#9002 DOC: Minor cleanup of sphinx-build doc
  doc/man/sphinx-build.rst
Labels: docs

#8990 refactor: Use PEP-526 based variable annotation (sphinx.builders)
  sphinx/builders/__init__.py
  sphinx/builders/_epub_base.py
  sphinx/builders/changes.py
  sphinx/builders/epub3.py
  sphinx/builders/gettext.py
  sphinx/builders/html/__init__.py
  sphinx/builders/latex/__init__.py
  sphinx/builders/latex/constants.py
  sphinx/builders/latex/theming.py
  sphinx/builders/latex/transforms.py
  sphinx/builders/linkcheck.py
  sphinx/builders/manpage.py
  sphinx/builders/singlehtml.py
  sphinx/builders/texinfo.py
  sphinx/builders/text.py
  sphinx/builders/xml.py
Labels: refactoring

#8991 refactor: Add a type alias for the option_spec of directives; OptionSpec
  CHANGES
  doc/extdev/deprecated.rst
  sphinx/directives/__init__.py
  sphinx/directives/code.py
  sphinx/directives/other.py
  sphinx/directives/patches.py
  sphinx/domains/c.py
  sphinx/domains/changeset.py
  sphinx/domains/cpp.py
  sphinx/domains/index.py
  sphinx/domains/javascript.py
  sphinx/domains/python.py
  sphinx/domains/rst.py
  sphinx/domains/std.py
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/doctest.py
  sphinx/ext/graphviz.py
  sphinx/ext/ifconfig.py
  sphinx/ext/inheritance_diagram.py
  sphinx/ext/todo.py
  sphinx/util/typing.py
Labels: refactoring

#8983 Fix #7383: autodoc: Support typehints for properties
  CHANGES
  sphinx/ext/autodoc/__init__.py
  tests/roots/test-ext-autodoc/target/properties.py
  tests/test_ext_autodoc.py
  tests/test_ext_autodoc_autoclass.py
  tests/test_ext_autodoc_autoproperty.py
  tests/test_ext_autodoc_configs.py
Labels: autodoc, enhancement

#9006 LaTeX: partially revert #8997 for \pysigline
  sphinx/texinputs/sphinxlatexobjects.sty
Labels: latex

#9010 Fix #9008: Fix typo
  doc/usage/quickstart.rst
Labels: bug, docs

#9004 refactor: Use PEP-526 based variable annotation (sphinx.ext)
  sphinx/ext/apidoc.py
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autodoc/directive.py
  sphinx/ext/autodoc/importer.py
  sphinx/ext/autodoc/mock.py
  sphinx/ext/autodoc/typehints.py
  sphinx/ext/autosummary/generate.py
  sphinx/ext/coverage.py
  sphinx/ext/graphviz.py
  sphinx/ext/inheritance_diagram.py
  sphinx/ext/intersphinx.py
  sphinx/ext/linkcode.py
  sphinx/ext/napoleon/__init__.py
  sphinx/ext/napoleon/docstring.py
  sphinx/ext/napoleon/iterators.py
Labels: refactoring

#9011 Fix #9009: LaTeX: "release" value with underscore leads to invalid LaTeX
  CHANGES
  sphinx/templates/latex/latex.tex_t
  tests/test_build_latex.py
Labels: bug, latex

#9015 Fix #8992: autodoc: Failed to resolve types.TracebackType type annotation
  CHANGES
  sphinx/util/typing.py
  tests/test_util_typing.py
Labels: autodoc, bug

#8967 Fix #8959: using UNIX path separator confuses Sphinx on Windows
  CHANGES
  sphinx/environment/__init__.py
  tests/test_build.py
Labels: bug

#9021 Rename DocumenterBridge.filename_set to record_dependencies
  CHANGES
  doc/extdev/deprecated.rst
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autodoc/directive.py
  tests/test_ext_autodoc.py
Labels: autodoc, refactoring

#9022 Deprecate DocumenterBridge.warn()
  CHANGES
  doc/extdev/deprecated.rst
  sphinx/ext/autodoc/directive.py
Labels: autodoc, refactoring

#9017 refactor: Use PEP-526 based variable annotation (sphinx.domains)
  sphinx/domains/__init__.py
  sphinx/domains/c.py
  sphinx/domains/changeset.py
  sphinx/domains/cpp.py
  sphinx/domains/javascript.py
  sphinx/domains/math.py
  sphinx/domains/python.py
  sphinx/domains/rst.py
  sphinx/domains/std.py
Labels: refactoring

#9028 refactor: Use PEP-526 based variable annotation (sphinx.directives)
  sphinx/directives/__init__.py
  sphinx/directives/code.py
  sphinx/directives/other.py
  sphinx/directives/patches.py
Labels: refactoring

#9031 refactor: Use PEP-526 based variable annotation (sphinx.environment)
  sphinx/environment/__init__.py
  sphinx/environment/adapters/indexentries.py
  sphinx/environment/adapters/toctree.py
  sphinx/environment/collectors/__init__.py
  sphinx/environment/collectors/asset.py
  sphinx/environment/collectors/toctree.py
Labels: refactoring

#9033 Fix some local parameter names
  sphinx/builders/html/__init__.py
  sphinx/util/i18n.py
Labels: bug, refactoring

#9038 Fix the testcase for linkcheck refers removed URLs
  tests/roots/test-linkcheck/links.txt
  tests/test_build_linkcheck.py
Labels: bug, test

#9026 Close #5603: autodoc: Allow to refer to a python object using canonical name
  CHANGES
  sphinx/ext/autodoc/__init__.py
  tests/roots/test-ext-autodoc/target/canonical/__init__.py
  tests/roots/test-ext-autodoc/target/canonical/original.py
  tests/test_ext_autodoc.py
Labels: autodoc, enhancement
