Repository sphinx-doc/sphinx, pull requests merged in 2021-04, with the labels that each got.

#9042 Docs: fix typo in env-merge-info
  doc/extdev/appapi.rst
Labels: bug, docs

#9048 Fix testcase: the signature of Enum class has been changed since HEAD of 3.10
  tests/test_ext_autodoc.py
Labels: bug, test

#9041 Fix typo in docs
  doc/usage/restructuredtext/domains.rst
Labels: bug, docs

#9034 refactor: Use PEP-526 based variable annotation (sphinx.pycode)
  sphinx/pycode/__init__.py
  sphinx/pycode/ast.py
  sphinx/pycode/parser.py
Labels: refactoring

#9035 refactor: Use PEP-526 based variable annotation (sphinx.search)
  sphinx/search/__init__.py
  sphinx/search/ja.py
  sphinx/search/ro.py
  sphinx/search/tr.py
  sphinx/search/zh.py
Labels: refactoring

#8539 Make autodoc_typehints="description" work with autoclass_content="class"
  doc/usage/extensions/autodoc.rst
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autodoc/typehints.py
  tests/roots/test-ext-autodoc/target/typehints.py
  tests/test_ext_autodoc_configs.py
Labels: autodoc, proposal

#8870 test: Do test with docutils-0.17b1
  .github/workflows/main.yml
  tests/test_build_html.py
  tests/test_ext_autosummary.py
  tests/test_ext_graphviz.py
  tests/test_ext_inheritance_diagram.py
  tests/test_intl.py
  tox.ini
Labels: test

#9036 HTML Templates: Add blocks to search page
  sphinx/themes/basic/search.html
Labels: html theme, proposal

#8841 Overloaded function signatures do not require a separating backslash
  doc/usage/extensions/autodoc.rst
  sphinx/ext/autodoc/__init__.py
  tests/roots/test-ext-autodoc/target/docstring_signature.py
  tests/test_ext_autodoc_configs.py
Labels: autodoc, proposal

#9059 CSS: support for aside.sidebar (from docutils 0.17+)
  sphinx/themes/basic/static/basic.css_t
Labels: bug, html theme

#9054 refactor: Lazy loading is not needed for type annotations
  sphinx/util/docfields.py
Labels: refactoring

#9055 refactor: use raw Type for type annotations
  sphinx/application.py
  sphinx/builders/__init__.py
  sphinx/builders/html/__init__.py
  sphinx/deprecation.py
  sphinx/domains/std.py
  sphinx/environment/collectors/toctree.py
  sphinx/ext/autodoc/directive.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/napoleon/docstring.py
  sphinx/io.py
  sphinx/parsers.py
  sphinx/registry.py
  sphinx/roles.py
  sphinx/util/__init__.py
  sphinx/util/docfields.py
  sphinx/util/docutils.py
  sphinx/util/inspect.py
  sphinx/util/nodes.py
  sphinx/util/osutil.py
  sphinx/util/typing.py
Labels: refactoring

#9057 refactor: Use PEP-526 based variable annotation
  sphinx/addnodes.py
  sphinx/application.py
  sphinx/builders/texinfo.py
  sphinx/config.py
  sphinx/events.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/autosummary/generate.py
  sphinx/ext/doctest.py
  sphinx/ext/todo.py
  sphinx/ext/viewcode.py
  sphinx/highlighting.py
  sphinx/io.py
  sphinx/locale/__init__.py
  sphinx/project.py
  sphinx/registry.py
  sphinx/roles.py
  sphinx/setup_command.py
  sphinx/testing/fixtures.py
  sphinx/testing/util.py
  sphinx/theming.py
Labels: refactoring

#9064 refactor: Add Optional to type annotations
  sphinx/application.py
  sphinx/builders/_epub_base.py
  sphinx/ext/autosummary/generate.py
  sphinx/registry.py
  sphinx/util/inspect.py
Labels: refactoring

#9053 Fix #8870: Use title node for the caption of toctree
  CHANGES
  sphinx/environment/adapters/toctree.py
  sphinx/writers/html.py
  sphinx/writers/html5.py
  tests/test_environment_toctree.py
  tests/test_intl.py
Labels: bug

#9073 Depart method for node is optional
  sphinx/application.py
Labels: bug

#9079 Fix autodoc: Async staticmethods/ classmethods are considered as not async
  CHANGES
  sphinx/util/inspect.py
Labels: autodoc, bug

#9081 Fix CI for docutils
  .github/workflows/main.yml
  tox.ini
Labels: bug, refactoring, test

#9077 Fix #9051: html theme: The style for figure are not applied
  CHANGES
  sphinx/themes/agogo/static/agogo.css_t
  sphinx/themes/basic/static/basic.css_t
  sphinx/themes/epub/static/epub.css_t
  sphinx/themes/nonav/static/nonav.css
  sphinx/themes/scrolls/static/scrolls.css_t
  sphinx/themes/traditional/static/traditional.css_t
Labels: bug, html theme

#9083 test: Disable testing with python3.10
  .github/workflows/main.yml
Labels: test

#8898 sphinx.ext.extlinks: Allow ``%s`` in link caption string
  doc/usage/extensions/extlinks.rst
  sphinx/ext/extlinks.py
Labels: extensions, proposal

#9086 docs: Add versionchanged tag to extlinks (refs: #8898)
  doc/usage/extensions/extlinks.rst
Labels: docs, extensions

#9084 doc: Add docs for napoleon_preprocess_types
  doc/usage/extensions/napoleon.rst
  sphinx/ext/napoleon/__init__.py
Labels: docs, extensions:napoleon

#9023 Flexible declaration styling
  CHANGES
  doc/extdev/nodes.rst
  sphinx/addnodes.py
  sphinx/directives/__init__.py
  sphinx/domains/c.py
  sphinx/domains/cpp.py
  sphinx/themes/basic/static/basic.css_t
  sphinx/transforms/post_transforms/__init__.py
  sphinx/writers/html.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
  tests/roots/test-root/objects.txt
  tests/test_build_html.py
  tests/test_domain_cpp.py
  tests/test_ext_intersphinx.py
Labels: domain, domains:c, domains:cpp, enhancement

#9100 doc: Fix grammar in documentation for `autodoc_typehints`
  doc/usage/extensions/autodoc.rst
Labels: bug, docs

#9097 Remove unnecesary sleep when submitting parallel tasks
  sphinx/util/parallel.py
Labels: cmdline, refactoring

#9104 Fix #8127: py domain: Ellipsis in info-field-list causes nit-picky warning
  CHANGES
  sphinx/domains/python.py
  tests/test_domain_py.py
Labels: bug, domains:py

#9107 Fix #8818: autodoc: Super class having ``Any`` arguments causes nit-picky warning
  CHANGES
  sphinx/util/typing.py
  tests/test_ext_autodoc.py
  tests/test_ext_autodoc_autoclass.py
  tests/test_util_typing.py
Labels: autodoc, bug

#9106 Fix #9103: LaTeX: imgconverter: conversion runs even if not needed
  CHANGES
  sphinx/transforms/post_transforms/images.py
  tests/roots/test-ext-imgconverter/img.pdf
  tests/roots/test-ext-imgconverter/index.rst
  tests/test_ext_imgconverter.py
Labels: bug, extensions

#9050 Close #8829: doc: Update description of paralle-read-safe
  doc/extdev/index.rst
Labels: docs

#9113 C, C++, alias fix
  CHANGES
  sphinx/domains/c.py
  sphinx/domains/cpp.py
Labels: bug, domains:c, domains:cpp

#9112 Recommend MyST-Parser for Markdown usage
  doc/usage/markdown.rst
Labels: docs

#9101 Fix `user-selection` in Safari and Internet Explorer
  doc/usage/extensions/autodoc.rst
  sphinx/themes/basic/static/basic.css_t
Labels: bug, html theme

#9109 Fix #9095: autodoc: TypeError is raised on processing broken metaclass
  CHANGES
  sphinx/ext/autodoc/importer.py
Labels: autodoc, bug

#9111 Fix #9110: autodoc: metadata of GenericAlias is not rendered as a reference in py37+
  CHANGES
  sphinx/ext/autodoc/__init__.py
  tests/test_ext_autodoc.py
  tests/test_ext_autodoc_autoattribute.py
  tests/test_ext_autodoc_autodata.py
Labels: autodoc, bug

#9117 doc: Fix typo
  doc/usage/configuration.rst
Labels: bug, docs

#9122 C++, add internal API for setting name in ASTType
  sphinx/domains/cpp.py
Labels: domains:cpp, refactoring

#9128 Fix #9121: py domain: duplicated warning for canonical and alias
  CHANGES
  sphinx/domains/python.py
  tests/test_domain_py.py
Labels: bug, domains:py

#9118 🐛 FIX: `Config.__getitem__` typing
  sphinx/config.py
  sphinx/domains/python.py
Labels: bug

#9094 Add `mathjax3_config` config option
  CHANGES
  doc/usage/extensions/math.rst
  sphinx/ext/mathjax.py
Labels: extensions, proposal

#9132 doc: Fix minor mark-up misses up
  doc/latex.rst
Labels: bug, docs

#9134 refactor: Add testcase for mathjax3_config (refs: #9094)
  sphinx/builders/html/__init__.py
  tests/test_ext_math.py
Labels: refactoring, test

#9139 Add unicode multiplication to texescape
  sphinx/util/texescape.py
Labels: latex, proposal

#9138 Add doc and testcase for program directive (refs: #9137)
  doc/usage/restructuredtext/domains.rst
  tests/test_domain_std.py
Labels: docs, test

#9125 Support docutils-0.17
  .github/workflows/main.yml
  CHANGES
  setup.py
Labels: proposal

#9150 Mention that aiohttp uses its own custom theme
  EXAMPLES
Labels: docs

#9144 refactor: linkcheck: Call write_linkstat() at the top of process_result()
  sphinx/builders/linkcheck.py
Labels: linkcheck, refactoring
