Repository sphinx-doc/sphinx, pull requests merged in 2022-01, with the labels that each got.

#10031 Close #9555: autosummary: Improve error messages on failure to load target object
  CHANGES
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/autosummary/generate.py
Labels: enhancement, refactoring, autosummary

#10039 A happy new year! (again)
  sphinx/locale/__init__.py
Labels: refactoring

#10034 Fix #10027: autodoc_typehints_format does not work with :show-inheritance:
  sphinx/ext/autodoc/__init__.py
  sphinx/util/typing.py
  tests/roots/test-ext-autodoc/target/genericalias.py
  tests/roots/test-ext-autodoc/target/typevar.py
  tests/test_ext_autodoc.py
  tests/test_ext_autodoc_autoattribute.py
  tests/test_ext_autodoc_autodata.py
  tests/test_ext_autodoc_configs.py
  tests/test_util_typing.py
Labels: bug, autodoc

#10038 CHANGES: Fix the location of the deprecation entry
  CHANGES
Labels: bug, docs

#10042 refactor: Reduce usages of distutils (refs: #9820)
  setup.py
  tests/roots/test-setup/setup.py
Labels: refactoring

#10043 i18n: meta strings are not translated with docutils-0.18
  sphinx/addnodes.py
  sphinx/directives/patches.py
  sphinx/search/__init__.py
  sphinx/transforms/i18n.py
  sphinx/util/nodes.py
Labels: i18n, refactoring, docutils

#10036 autosummary: autosummary: import_by_name() now raises ImportExceptionGroup
  CHANGES
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/autosummary/generate.py
Labels: refactoring, autosummary

#10037 autodoc: The default of autodoc_typehints_format becomes to 'smart'
  CHANGES
  doc/usage/extensions/autodoc.rst
  sphinx/ext/autodoc/__init__.py
  tests/test_ext_autodoc.py
  tests/test_ext_autodoc_autoattribute.py
  tests/test_ext_autodoc_autoclass.py
  tests/test_ext_autodoc_autodata.py
  tests/test_ext_autodoc_autofunction.py
  tests/test_ext_autodoc_automodule.py
  tests/test_ext_autodoc_configs.py
  tests/test_ext_autodoc_preserve_defaults.py
Labels: enhancement, autodoc

#10047 CI: Remove unused no longer needed PYTHONWARNINGS
  tox.ini
Labels: test, refactoring

#10044 Migrate to Node.findall() from Node.traverse()
  sphinx/builders/__init__.py
  sphinx/builders/_epub_base.py
  sphinx/builders/gettext.py
  sphinx/builders/html/__init__.py
  sphinx/builders/html/transforms.py
  sphinx/builders/latex/__init__.py
  sphinx/builders/latex/transforms.py
  sphinx/builders/linkcheck.py
  sphinx/builders/manpage.py
  sphinx/builders/singlehtml.py
  sphinx/builders/texinfo.py
  sphinx/builders/xml.py
  sphinx/directives/patches.py
  sphinx/domains/c.py
  sphinx/domains/citation.py
  sphinx/domains/cpp.py
  sphinx/domains/index.py
  sphinx/domains/math.py
  sphinx/domains/std.py
  sphinx/environment/__init__.py
  sphinx/environment/adapters/toctree.py
  sphinx/environment/collectors/asset.py
  sphinx/environment/collectors/title.py
  sphinx/environment/collectors/toctree.py
  sphinx/ext/autosectionlabel.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/doctest.py
  sphinx/ext/extlinks.py
  sphinx/ext/ifconfig.py
  sphinx/ext/linkcode.py
  sphinx/ext/todo.py
  sphinx/ext/viewcode.py
  sphinx/transforms/__init__.py
  sphinx/transforms/compact_bullet_list.py
  sphinx/transforms/i18n.py
  sphinx/transforms/post_transforms/__init__.py
  sphinx/transforms/post_transforms/code.py
  sphinx/transforms/post_transforms/images.py
  sphinx/util/docutils.py
  sphinx/util/nodes.py
  sphinx/versioning.py
  sphinx/writers/latex.py
  sphinx/writers/manpage.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
  tests/test_directive_code.py
  tests/test_domain_js.py
  tests/test_domain_std.py
  tests/test_ext_doctest.py
Labels: refactoring, docutils

#10048 Change "headline" to "heading"
  sphinx/themes/basic/static/doctools.js
  sphinx/writers/html.py
  sphinx/writers/html5.py
  tests/test_build_html.py
Labels: html, proposal

#10050 test: Migrate to Node.findall() from Node.traverse()
  tests/test_domain_py.py
  tests/test_domain_std.py
  tests/test_markup.py
  tests/test_util_nodes.py
  tests/test_versioning.py
Labels: test, refactoring, docutils

#10051 test: manpage: double quotes are escaped since docutils-0.18
  tests/test_smartquotes.py
Labels: man, test, docutils

#10040 Close #9595: Deprecate setuptools integration
  CHANGES
  doc/extdev/deprecated.rst
  doc/usage/advanced/setuptools.rst
  sphinx/setup_command.py
Labels: refactoring

#10064 CI: refactor tox.ini; Install HEAD of docutils directly
  tox.ini
Labels: test, refactoring

#10063 doc: Linkify issue numbers in changelog to GitHub
  doc/conf.py
Labels: docs, proposal

#10065 Fix mypy violations (with mypy-0.931)
  setup.py
  sphinx/directives/patches.py
  sphinx/util/requests.py
Labels: refactoring

#10066 Fix mypy violations (with mypy-0.931)
  sphinx/directives/patches.py
Labels: refactoring

#10075 merge 'isinstance' calls (SIM101)
  sphinx/util/docfields.py
  sphinx/writers/latex.py
Labels: refactoring

#10083 use class-style syntax for 'NamedTuple's
  sphinx/builders/linkcheck.py
Labels: refactoring, linkcheck

#10081 use 'callable' to check if object is callable (B004)
  sphinx/config.py
  sphinx/util/inspect.py
  tests/test_build_html.py
Labels: refactoring

#10085 Fix #10058: autosummary: Imported members are not shown
  CHANGES
  sphinx/ext/autosummary/__init__.py
Labels: bug, autosummary

#10080 simplify some set comparisons (SIM109)
  sphinx/builders/_epub_base.py
  sphinx/builders/changes.py
  sphinx/domains/c.py
  sphinx/domains/cpp.py
  sphinx/ext/napoleon/__init__.py
  sphinx/util/logging.py
  sphinx/util/stemmer/porter.py
Labels: refactoring

#10079 Fix #10061: html theme: Confvals added by themes are not initialized
  CHANGES
  sphinx/config.py
  sphinx/theming.py
Labels: bug, html theme

#10069 Close #10055: sphinx-build: Create directories when `-w` option given
  CHANGES
  sphinx/cmd/build.py
Labels: enhancement, cmdline

#10068 Fix #10057: Failed to scan documents on the root directory
  CHANGES
  sphinx/util/__init__.py
Labels: bug, cmdline

#10067 Close #10062: Change the default language to 'en'
  CHANGES
  doc/extdev/deprecated.rst
  sphinx/application.py
  sphinx/builders/html/__init__.py
  sphinx/builders/latex/__init__.py
  sphinx/builders/latex/util.py
  sphinx/config.py
  sphinx/environment/__init__.py
  sphinx/environment/collectors/asset.py
  sphinx/util/i18n.py
  sphinx/writers/latex.py
  tests/test_build_latex.py
  tests/test_util_i18n.py
Labels: enhancement, i18n, config, refactoring

#10091 In translated docs, sort glossaries by translated terms
  doc/usage/restructuredtext/directives.rst
  sphinx/domains/std.py
  sphinx/transforms/__init__.py
  tests/roots/test-intl/glossary_terms.txt
  tests/roots/test-intl/xx/LC_MESSAGES/glossary_terms.po
  tests/test_intl.py
Labels: markup, i18n

#9551 "Hide Search Matches" removes "highlight" parameter from URL
  sphinx/themes/basic/static/doctools.js
Labels: enhancement, html search

#10099 Skip "data:" URIs in ImageConverter
  sphinx/transforms/post_transforms/images.py
Labels: bug

#9661 code-block: Fix handling of :dedent: and add unit tests
  CHANGES
  doc/usage/restructuredtext/directives.rst
  sphinx/directives/code.py
  tests/roots/test-directive-code/dedent.rst
  tests/test_directive_code.py
Labels: bug, markup

#10101 Fix empty returns section
  sphinx/ext/napoleon/docstring.py
  tests/test_ext_napoleon_docstring.py
Labels: bug, extensions:napoleon

#10097 Fix #9981: std domain: Strip value part of the option directive from genindex
  CHANGES
  sphinx/domains/std.py
  tests/test_domain_std.py
Labels: proposal, domains:std

#10078 address some unused loop control variables
  doc/development/tutorials/examples/recipe.py
  sphinx/addnodes.py
  sphinx/builders/__init__.py
  sphinx/builders/_epub_base.py
  sphinx/builders/gettext.py
  sphinx/builders/html/__init__.py
  sphinx/builders/linkcheck.py
  sphinx/directives/__init__.py
  sphinx/directives/other.py
  sphinx/domains/c.py
  sphinx/domains/changeset.py
  sphinx/domains/citation.py
  sphinx/domains/cpp.py
  sphinx/domains/javascript.py
  sphinx/domains/math.py
  sphinx/domains/rst.py
  sphinx/environment/adapters/indexentries.py
  sphinx/environment/collectors/toctree.py
  sphinx/ext/apidoc.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/autosummary/generate.py
  sphinx/ext/extlinks.py
  sphinx/ext/imgmath.py
  sphinx/ext/napoleon/__init__.py
  sphinx/setup_command.py
  sphinx/testing/path.py
  sphinx/testing/util.py
  sphinx/transforms/i18n.py
  sphinx/util/__init__.py
  sphinx/util/osutil.py
  sphinx/writers/latex.py
  sphinx/writers/texinfo.py
  sphinx/writers/text.py
  tests/test_domain_c.py
  tests/test_ext_napoleon.py
  tests/test_intl.py
  utils/doclinter.py
Labels: refactoring

#10100 Fix #9413: xml: Invalid XML was generated when cross referencing python objects
  CHANGES
  sphinx/builders/xml.py
Labels: bug, builder

#9822 Intersphinx role (2)
  CHANGES
  doc/usage/extensions/intersphinx.rst
  sphinx/ext/intersphinx.py
  sphinx/util/docutils.py
  tests/roots/test-ext-intersphinx-role/conf.py
  tests/roots/test-ext-intersphinx-role/index.rst
  tests/test_ext_intersphinx.py
Labels: enhancement, extensions:intersphinx

#10109 Revert typo change
  EXAMPLES
Labels: bug, docs

#10119 Documentation: Mention `nitpick_ignore(_regex)` in docs of `warn-missing-reference`
  doc/extdev/appapi.rst
Labels: enhancement, docs

#10140 Docs: Fix typos in autosummary.rst
  doc/usage/extensions/autosummary.rst
Labels: bug, docs

#10135 Fix #10121: html: <div> tag for admonition is not closed w/ docutils-0.18
  sphinx/writers/html.py
  sphinx/writers/html5.py
Labels: bug, docutils

#10131 Close #10125: extlinks: Improve suggestion message for a reference having title
  CHANGES
  sphinx/ext/extlinks.py
  tests/test_ext_extlinks.py
Labels: enhancement, extensions

#10136 Fix #10133: autodoc: Crashed when mocked module is used for type annotation
  CHANGES
  sphinx/ext/autodoc/mock.py
  sphinx/util/typing.py
  tests/test_util_typing.py
Labels: bug, autodoc

#10148 Fix the order of CHANGES
  CHANGES
Labels: bug, docs

#10132 Fix #10122: make.bat should check the installation before help
  CHANGES
  sphinx/templates/quickstart/make.bat.new_t
Labels: bug, cmdline

#9337 Implement new search shortcuts.
  CHANGES
  doc/usage/theming.rst
  sphinx/themes/basic/static/doctools.js
  sphinx/themes/basic/static/documentation_options.js_t
  sphinx/themes/basic/theme.conf
Labels: html, proposal

#10028 Drop JavaScript Frameworks
  .github/workflows/nodejs.yml
  AUTHORS
  CHANGES
  doc/_templates/indexsidebar.html
  doc/_themes/sphinx13/layout.html
  karma.conf.js
  package-lock.json
  package.json
  sphinx/builders/html/__init__.py
  sphinx/themes/basic/layout.html
  sphinx/themes/basic/searchbox.html
  sphinx/themes/basic/static/_sphinx_javascript_frameworks_compat.js
  sphinx/themes/basic/static/doctools.js
  sphinx/themes/basic/static/searchtools.js
  sphinx/themes/bizstyle/static/bizstyle.js_t
  sphinx/themes/classic/layout.html
  sphinx/themes/classic/static/classic.css_t
  sphinx/themes/classic/static/sidebar.js_t
  sphinx/themes/scrolls/static/theme_extras.js
  tests/js/doctools.js
Labels: html search
