Repository sphinx-doc/sphinx, pull requests merged in 2022-06, with the labels that each got.

#10492 Spelling (language)
  sphinx/config.py
  tests/test_config.py
Labels: bug, config

#10503 `gettext`: Ensure positions always sort
  sphinx/builders/gettext.py
Labels: bug, i18n

#10504 Fix `findall` usage in `KeyboardTransform`
  sphinx/builders/html/transforms.py
  tests/roots/test-transforms-post_transforms-keyboard/conf.py
  tests/roots/test-transforms-post_transforms-keyboard/index.rst
  tests/test_transforms_post_transforms.py
Labels: bug, markup

#10510 Fix #10509: autosummary: autosummary fails with a shared library
  CHANGES
  sphinx/ext/autosummary/generate.py
Labels: bug, autosummary

#10523 Fix double brackets
  CHANGES
  doc/templating.rst
  sphinx/builders/html/__init__.py
  sphinx/themes/basic/static/basic.css_t
Labels: bug, html theme

#10519 Add Changelog to project_urls
  setup.py
Labels: enhancement

#10490 Close #9820: Use setuptools.Command if available
  sphinx/setup_command.py
Labels: cmdline, refactoring

#10488 Close #10483: Fix type annotations for Sphinx.__init__()
  sphinx/application.py
Labels: bug, api

#10539 Fix inherited attribute docstrings
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autodoc/importer.py
  tests/roots/test-ext-autodoc/target/inheritance.py
  tests/test_ext_autodoc.py
  tests/test_ext_autodoc_automodule.py
  tests/test_ext_autodoc_configs.py
Labels: bug, autodoc

#10535 Fix `nav.contents` CSS for Docutils 0.18
  doc/_themes/sphinx13/static/sphinx13.css
  sphinx/themes/basic/static/basic.css_t
  sphinx/themes/bizstyle/static/bizstyle.css_t
  sphinx/themes/classic/static/classic.css_t
  sphinx/themes/epub/static/epub.css_t
  sphinx/themes/nature/static/nature.css_t
  sphinx/themes/nonav/static/nonav.css_t
  sphinx/themes/pyramid/static/epub.css_t
  sphinx/themes/pyramid/static/pyramid.css_t
  sphinx/themes/sphinxdoc/static/sphinxdoc.css_t
  sphinx/themes/traditional/static/traditional.css_t
Labels: bug, html theme, docutils

#10557 Move Adam Turner to co-maintainers
  AUTHORS
Labels: task

#10389 Replace doclinter with sphinx-lint
  .github/workflows/lint.yml
  Makefile
  doc/development/index.rst
  doc/development/tutorials/autodoc_ext.rst
  doc/extdev/deprecated.rst
  doc/latex.rst
  doc/templating.rst
  doc/tutorial/describing-code.rst
  doc/usage/extensions/intersphinx.rst
  doc/usage/extensions/napoleon.rst
  doc/usage/installation.rst
  setup.py
  tox.ini
  utils/doclinter.py
Labels: proposal, test

#10468 Drop python 3.6 support
  .github/workflows/builddoc.yml
  .github/workflows/lint.yml
  .github/workflows/main.yml
  CHANGES
  doc/internals/contributing.rst
  doc/internals/release-process.rst
  doc/usage/installation.rst
  setup.py
  sphinx/ext/extlinks.py
  sphinx/util/inspect.py
  sphinx/util/typing.py
  tests/test_build.py
  tests/test_errors.py
  tests/test_ext_autodoc.py
  tests/test_ext_autodoc_autoattribute.py
  tests/test_ext_autodoc_autoclass.py
  tests/test_ext_autodoc_autodata.py
  tests/test_ext_autodoc_autofunction.py
  tests/test_ext_autodoc_automodule.py
  tests/test_ext_autodoc_configs.py
  tests/test_ext_autodoc_mock.py
  tests/test_ext_napoleon.py
  tests/test_util_inspect.py
  tests/test_util_typing.py
Labels: refactoring

#10467 Simplify Sphinx's Stemmer
  AUTHORS
  CHANGES
  doc/extdev/deprecated.rst
  sphinx/search/en.py
  sphinx/search/zh.py
  sphinx/util/stemmer/__init__.py
  sphinx/util/stemmer/porter.py
Labels: html search, refactoring

#10530 Increase static typing strictness
  setup.cfg
  sphinx/application.py
  sphinx/builders/__init__.py
  sphinx/builders/html/__init__.py
  sphinx/cmd/quickstart.py
  sphinx/registry.py
  sphinx/util/console.py
  sphinx/util/logging.py
  sphinx/util/parallel.py
  tests/test_application.py
  tests/test_environment.py
  tests/test_environment_toctree.py
  tests/test_markup.py
Labels: refactoring

#10460 logging: always show source locations as absolute paths
  sphinx/util/logging.py
  tests/test_util_logging.py
Labels: cmdline, proposal

#10520 agogo theme: Wrong use of sidebar* configs
  CHANGES
  sphinx/themes/agogo/static/agogo.css_t
Labels: bug, html theme

#10366 Allow emphasising placeholders in `option` directives
  CHANGES
  doc/usage/configuration.rst
  doc/usage/restructuredtext/domains.rst
  sphinx/config.py
  sphinx/domains/std.py
  tests/roots/test-root/objects.txt
  tests/test_build_html.py
Labels: enhancement, domains:std

#10471 Remove deprecated items for Sphinx 6.0
  CHANGES
  LICENSE
  doc/conf.py
  doc/usage/configuration.rst
  sphinx/application.py
  sphinx/builders/html/__init__.py
  sphinx/cmd/quickstart.py
  sphinx/deprecation.py
  sphinx/directives/patches.py
  sphinx/domains/c.py
  sphinx/domains/python.py
  sphinx/environment/__init__.py
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autodoc/directive.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/extlinks.py
  sphinx/ext/napoleon/docstring.py
  sphinx/io.py
  sphinx/registry.py
  sphinx/themes/basic/static/_sphinx_javascript_frameworks_compat.js
  sphinx/themes/basic/static/jquery-3.6.0.js
  sphinx/themes/basic/static/jquery.js
  sphinx/themes/basic/static/underscore-1.13.1.js
  sphinx/themes/basic/static/underscore.js
  sphinx/theming.py
  sphinx/transforms/__init__.py
  sphinx/util/docstrings.py
  sphinx/util/pycompat.py
  sphinx/util/smartypants.py
  sphinx/util/typing.py
  sphinx/writers/html.py
  sphinx/writers/html5.py
  tests/test_build_html.py
  tests/test_theming.py
Labels: refactoring

#10439 Show the repr of the value in some warnings.
  CHANGES
  sphinx/domains/std.py
  tests/test_build_html.py
  tests/test_build_latex.py
  tests/test_build_texinfo.py
  tests/test_domain_py.py
  tests/test_ext_autosectionlabel.py
Labels: proposal

#6679 agogo theme: ensure hidden toctree is show on Table of Contents
  sphinx/themes/agogo/layout.html
Labels: bug, html theme

#10560 Remove traces of Python 2 and 3.5
  doc/usage/extensions/napoleon.rst
  doc/usage/restructuredtext/roles.rst
  sphinx/ext/autodoc/importer.py
  sphinx/util/inspect.py
  sphinx/util/typing.py
  tests/test_pycode_parser.py
Labels: refactoring

#10561 Update GitHub Actions versions
  .github/workflows/builddoc.yml
  .github/workflows/coverage.yml
  .github/workflows/create-release.yml
  .github/workflows/docutils-latest.yml
  .github/workflows/lint.yml
  .github/workflows/main.yml
  .github/workflows/nodejs.yml
  .github/workflows/transifex.yml
  doc/tutorial/deploying.rst
Labels: refactoring

#10563 requests.packages is deprecated, import from urllib3
  sphinx/util/requests.py
Labels: refactoring

#10558 Remove `ru_RU` translation, it is empty and duplicates `ru`
  sphinx/locale/ru_RU/LC_MESSAGES/sphinx.js
  sphinx/locale/ru_RU/LC_MESSAGES/sphinx.mo
  sphinx/locale/ru_RU/LC_MESSAGES/sphinx.po
Labels: bug, i18n

#10566 Fix usage of enable_search_shortcuts theme config value.
  sphinx/themes/basic/static/documentation_options.js_t
  tests/test_build_html.py
Labels: bug, html search, html theme

#10582 Fix #10574: Failed to search on sphinx-doc.org
  doc/conf.py
Labels: docs

#10583 Fix #10574: Failed to search on sphinx-doc.org (again)
  doc/_themes/sphinx13/static/_sphinx_javascript_frameworks_compat.js
  doc/conf.py
Labels: bug, docs

#10584 Fix #10574: Failed to search on sphinx-doc.org (again)
  doc/_themes/sphinx13/static/_sphinx_javascript_frameworks_compat.js
Labels: bug, docs

#10565 Fix parsing of options with enabled option_emphasise_placeholders
  sphinx/domains/std.py
  tests/test_build_html.py
Labels: bug, domains:std

#10573 doc linting: Re-enable a check
  tox.ini
Labels: docs, test

#10249 Ensure ObjectDescription signature nodes include line numbers
  sphinx/directives/__init__.py
  tests/test_domain_py.py
Labels: bug, domain

#10571 Reduce content in the `sphinx-quickstart` `conf.py` file
  CHANGES
  sphinx/templates/quickstart/conf.py_t
Labels: enhancement, cmdline, config

#10595 Fix #10594: HTML: field term colons are doubled if using Docutils 0.18+
  CHANGES
  sphinx/themes/basic/static/basic.css_t
Labels: bug, html theme

#10597 Fix build failure for Docutils 0.18.0
  CHANGES
  sphinx/util/docutils.py
Labels: bug

#10598 Test with Docutils 0.19 prereleases
  .github/workflows/main.yml
  tox.ini
Labels: docutils, dependencies

#10581 Fix #10579: i18n: UnboundLocalError is raised on translating raw directive
  CHANGES
  sphinx/transforms/i18n.py
Labels: bug, i18n

#10577 LaTeX: fix #8686 Text can fall out of code-block at end of page
  CHANGES
  sphinx/texinputs/sphinxlatexliterals.sty
Labels: bug, latex

#9856 Replace `napoleon.iterators` by simpler stack implementation
  CHANGES
  doc/extdev/deprecated.rst
  sphinx/ext/napoleon/docstring.py
  sphinx/ext/napoleon/iterators.py
  tests/test_ext_napoleon_iterators.py
Labels: proposal, extensions:napoleon, refactoring

#10089 py domain: Ignore aliases for resolving `:any:` cross-references
  CHANGES
  sphinx/domains/python.py
  tests/roots/test-domain-py/canonical.rst
Labels: bug, autodoc, domains:py

#10562 Remove more deprecated items in Sphinx 6.0
  doc/templating.rst
  doc/usage/restructuredtext/domains.rst
  sphinx/application.py
  sphinx/builders/html/__init__.py
  sphinx/domains/python.py
  sphinx/util/compat.py
  tests/test_domain_py.py
Labels: refactoring

#10616 LaTeX: partially fix color issues for wrapped code lines with pagebreak
  sphinx/texinputs/sphinxlatexliterals.sty
  sphinx/texinputs/sphinxlatexstyletext.sty
Labels: bug, latex
