Repository sphinx-doc/sphinx, pull requests merged in 2022-04, with the labels that each got.

#10315 Fix #10279: autodoc: Default values are rendered as a string literal
  CHANGES
  sphinx/util/inspect.py
Labels: bug, autodoc

#10324 i18n: Change translation target branch from 4.x to 5.x
  .github/workflows/transifex.yml
Labels: i18n, task

#10311 Fix #10214: html: invalid language tag was generated for zh_CN
  CHANGES
  sphinx/builders/html/__init__.py
Labels: bug, html

#10320 Fix #10280: autodoc_docstring_signature generates needless return typehint
  CHANGES
  sphinx/ext/autodoc/__init__.py
  tests/roots/test-ext-autodoc/target/docstring_signature.py
  tests/test_ext_autodoc_configs.py
Labels: bug, autodoc

#10313 Support mocked decorator for class methods
  sphinx/ext/autodoc/mock.py
  sphinx/util/inspect.py
  tests/test_ext_autodoc_mock.py
Labels: bug, autodoc

#10321 Fix #10266: autodoc_preserve_defaults crashes on kwonlyargs w/o defaults
  CHANGES
  sphinx/ext/autodoc/preserve_defaults.py
  tests/roots/test-ext-autodoc/target/preserve_defaults.py
  tests/test_ext_autodoc_preserve_defaults.py
Labels: bug, autodoc

#10323 Fix #10318: literalinclude: :prepend: option working with :dedent:
  CHANGES
  sphinx/directives/code.py
  tests/test_directive_code.py
Labels: bug, markup

#10325 Close #8417: autodoc: :inherited-members: option now takes multiple classes
  CHANGES
  doc/usage/extensions/autodoc.rst
  sphinx/ext/autodoc/__init__.py
  tests/roots/test-ext-autodoc/target/inheritance.py
  tests/test_ext_autodoc_automodule.py
Labels: enhancement, autodoc

#9792 add option for autodoc to hide undocumented parameters but show undocumented return types
  CHANGES
  doc/usage/extensions/autodoc.rst
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autodoc/typehints.py
  tests/test_ext_autodoc_configs.py
Labels: autodoc, proposal

#10285 Fixed singledispatch documentation
  sphinx/ext/autodoc/__init__.py
  tests/roots/test-ext-autodoc/target/singledispatch.py
  tests/roots/test-ext-autodoc/target/singledispatchmethod.py
  tests/test_ext_autodoc.py
  tests/test_ext_autodoc_autofunction.py
Labels: bug, autodoc

#10153 Searchtools: don't assume that all themes define some elements
  sphinx/themes/basic/static/searchtools.js
Labels: bug, html search

#10336 Fix `test_restify`
  sphinx/util/typing.py
Labels: bug, autodoc

#10335 Fix search highlighting
  sphinx/themes/basic/static/doctools.js
Labels: bug, html search

#10191 LaTeX: fix footnote marks for multiple references
  CHANGES
  sphinx/texinputs/sphinx.sty
  sphinx/texinputs/sphinxlatexobjects.sty
  sphinx/texinputs/sphinxpackagefootnote.sty
  sphinx/writers/latex.py
  tests/test_build_latex.py
Labels: bug, latex

#10355 Move `babel` support to a dedicated utility file
  .github/workflows/transifex.yml
  doc/internals/contributing.rst
  setup.cfg
  setup.py
  utils/babel_runner.py
Labels: proposal, i18n

#10352 Don't use deprecated `setup.py build_sphinx`
  doc/conf.py
  setup.cfg
  tox.ini
Labels: bug, docs

#10357 Remove deprecated code for Sphinx 5.0
  sphinx/deprecation.py
  sphinx/domains/javascript.py
  sphinx/domains/python.py
  sphinx/domains/rst.py
  sphinx/domains/std.py
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/autodoc/deprecated.py
  sphinx/ext/autodoc/directive.py
  sphinx/ext/autodoc/importer.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/autosummary/generate.py
  sphinx/ext/viewcode.py
  sphinx/parsers.py
  sphinx/pycode/__init__.py
  sphinx/testing/path.py
  sphinx/util/docstrings.py
Labels: refactoring

#10354 Enable the opt-in EncodingWarning
  Makefile
  tox.ini
Labels: proposal, test

#10302 C++, conditional expression (update of #10270)
  CHANGES
  sphinx/domains/cpp.py
  tests/test_domain_cpp.py
Labels: enhancement, domains:cpp

#10360 C and C++, support attributes on enumerators
  sphinx/domains/c.py
  sphinx/domains/cpp.py
  sphinx/util/cfamily.py
  tests/test_domain_c.py
  tests/test_domain_cpp.py
Labels: enhancement, domains:c, domains:cpp

#10364 Fix `highlightSearchWords`'s terms check in `doctools.js`
  sphinx/themes/basic/static/doctools.js
Labels: bug, html search

#10369 Correct autodoc docstrings
  sphinx/ext/autodoc/__init__.py
Labels: docs, proposal

#10382 CI: Fix "Sync translation" task
  .github/workflows/transifex.yml
Labels: i18n

#10401 Fix mypy violations (with mypy-0.950)
  setup.py
  sphinx/domains/python.py
  sphinx/locale/__init__.py
Labels: refactoring

#10398 Changelog: fix typo in role
  CHANGES
Labels: bug, docs

#10399 Fix enable_search_shortcuts option
  sphinx/themes/basic/static/documentation_options.js_t
Labels: bug, html search
