Repository sphinx-doc/sphinx, pull requests merged in 2024-11, with the labels that each got.

#13080 Add James Addison to AUTHORS.rst
  AUTHORS.rst
Labels: type:docs, priority:low

#13079 Use default locale_dirs value
  doc/conf.py
Labels: type:docs, i18n

#13106 Format autosummary options in docs
  doc/usage/extensions/autosummary.rst
Labels: type:docs

#13123 Document ``Sphinx.set_html_assets_policy``
  doc/extdev/appapi.rst
Labels: type:docs

#13107 Format options for doctest directives
  doc/usage/extensions/doctest.rst
Labels: type:docs, extensions:doctest

#13108 Add a graph illustrating the build phases to the docs
  doc/_static/diagrams/sphinx_build_phases.dot
  doc/extdev/index.rst
Labels: type:docs, internals:other

#13037 singlehtml: deprecate the 'fix_refuris' helper function
  CHANGES.rst
  doc/extdev/deprecated.rst
  sphinx/builders/singlehtml.py
Labels: builder:singlehtml

#13150 Ensure `changeset.descname` is a string when not None
  sphinx/builders/changes.py
  sphinx/directives/__init__.py
Labels: internals:refactoring

#13143 Remove unnecessary parentheses in meth role
  sphinx/builders/__init__.py
Labels: type:docs

#13016 Use debug log level for AttributeErrors in viewcode
  sphinx/ext/viewcode.py
Labels: type:proposal, internals:other

#13152 LaTeX: fix a `7.4.0` typo in a default for `\sphinxboxsetup`
  CHANGES.rst
  sphinx/texinputs/sphinx.sty
Labels: type:bug, builder:latex
