Repository sphinx-doc/sphinx, pull requests merged in 2024-09, with the labels that each got.

#12879 Intersphinx: resolve type-check failures in inventory loading module
  AUTHORS.rst
  pyproject.toml
  sphinx/ext/intersphinx/_load.py
  sphinx/util/inventory.py
  sphinx/util/typing.py
  tests/test_builders/test_build_linkcheck.py
Labels: extensions:intersphinx, internals:typing

#12884 Resolve a `mypy --strict` `comparison-overlap` error
  sphinx/ext/apidoc.py
Labels: internals:typing

#12876 [doc] Clearly specify latex_engine defaults
  doc/usage/configuration.rst
Labels: builder:latex, type:docs, i18n

#12897 Fix tests for Docutils revision 9928
  tests/test_builders/test_build_html_image.py
Labels: docutils

#12796 Enable parallel reading if requested, even if there are few documents
  CHANGES.rst
  sphinx/builders/__init__.py
Labels: internals:parallel

#12830 Add PhaseFieldX to Sphinx projects list
  EXAMPLES.rst
Labels: type:docs

#12844 Restore 'noindex' support for JS, Python domains
  CHANGES.rst
  sphinx/domains/javascript.py
  sphinx/domains/python/__init__.py
Labels: domains:py, domains:js, internals:other

#12815 HTML search: adjustments to type-dependent CSS classnames and defaults
  doc/_themes/sphinx13/static/sphinx13.css
  doc/development/html_themes/index.rst
  sphinx/themes/basic/static/searchtools.js
Labels: html search

#12783 Add ``_DomainsContainer`` for better static typing
  sphinx/builders/changes.py
  sphinx/builders/html/__init__.py
  sphinx/builders/latex/transforms.py
  sphinx/builders/xml.py
  sphinx/directives/__init__.py
  sphinx/directives/patches.py
  sphinx/domains/__init__.py
  sphinx/domains/_domains_container.py
  sphinx/domains/c/__init__.py
  sphinx/domains/changeset.py
  sphinx/domains/citation.py
  sphinx/domains/cpp/__init__.py
  sphinx/domains/index.py
  sphinx/domains/javascript.py
  sphinx/domains/math.py
  sphinx/domains/python/__init__.py
  sphinx/domains/python/_object.py
  sphinx/domains/rst.py
  sphinx/domains/std/__init__.py
  sphinx/environment/__init__.py
  sphinx/environment/adapters/indexentries.py
  sphinx/environment/collectors/toctree.py
  sphinx/ext/autosectionlabel.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/coverage.py
  sphinx/ext/duration.py
  sphinx/ext/inheritance_diagram.py
  sphinx/ext/intersphinx/_resolve.py
  sphinx/ext/mathjax.py
  sphinx/ext/todo.py
  sphinx/search/__init__.py
  sphinx/testing/util.py
  sphinx/transforms/__init__.py
  sphinx/transforms/post_transforms/__init__.py
  sphinx/transforms/references.py
  sphinx/util/docutils.py
  sphinx/util/inventory.py
  sphinx/writers/html5.py
  sphinx/writers/latex.py
  sphinx/writers/texinfo.py
  tests/js/fixtures/cpp/searchindex.js
  tests/js/fixtures/multiterm/searchindex.js
  tests/js/fixtures/partial/searchindex.js
  tests/js/fixtures/titles/searchindex.js
  tests/test_domains/test_domain_c.py
  tests/test_domains/test_domain_js.py
  tests/test_domains/test_domain_py.py
  tests/test_domains/test_domain_py_canonical.py
  tests/test_domains/test_domain_py_pyfunction.py
  tests/test_domains/test_domain_py_pyobject.py
  tests/test_domains/test_domain_std.py
  tests/test_environment/test_environment.py
  tests/test_environment/test_environment_indexentries.py
  tests/test_extensions/test_ext_autosummary.py
  tests/test_search.py
Labels: internals:typing

#12907 Allow using GMT in the HTML last updated format
  CHANGES.rst
  doc/conf.py
  doc/usage/configuration.rst
  sphinx/builders/html/__init__.py
  sphinx/util/i18n.py
  tests/test_util/test_util_i18n.py
Labels: type:enhancement

#12908 Use pathlib for ``copy_asset_file``
  sphinx/util/fileutil.py
Labels: internals:refactoring

#12912 Resolve a few mypy issues in tests
  tests/test_extensions/test_ext_autosummary.py
  tests/test_extensions/test_ext_napoleon.py
  tests/test_util/test_util_nodes.py
Labels: type:tests, internals:typing

#12875 Disable default smartquotes for zh_CN and zh_TW
  CHANGES.rst
  sphinx/config.py
  tests/test_markup/test_smartquotes.py
Labels: internals:config, i18n

#12924 Add an initial pyright configuration
  .github/workflows/lint.yml
  pyproject.toml
  tox.ini
Labels: internals:typing

#12868 text builder: resolve an ordering conflict between two section-number-related tests
  tests/test_builders/test_build_text.py
Labels: builder:text, type:tests
