Repository sphinx-doc/sphinx, pull requests merged in 2024-01, with the labels that each got.

#11855 Defer computation of configuration values
  sphinx/application.py
  sphinx/config.py
  sphinx/ext/autosummary/generate.py
  sphinx/theming.py
  tests/test_build_latex.py
  tests/test_build_manpage.py
  tests/test_build_texinfo.py
  tests/test_config.py
Labels: internals:config

#11735 Fix typos newly found by codespell
  doc/index.rst
  doc/latex.rst
  doc/usage/domains/python.rst
  doc/usage/extensions/coverage.rst
  doc/usage/quickstart.rst
  doc/usage/restructuredtext/roles.rst
  sphinx/domains/cpp.py
  sphinx/environment/__init__.py
  sphinx/ext/autosummary/__init__.py
  sphinx/registry.py
  sphinx/texinputs/sphinxlatextables.sty
  sphinx/themes/agogo/layout.html
  tests/roots/test-versioning/insert_beginning.txt
  tests/test_ext_autosectionlabel.py
Labels: i18n

#11836 Apply refrub/ruff rule FURB109
  sphinx/builders/html/__init__.py
  sphinx/domains/c.py
  sphinx/domains/cpp.py
  sphinx/ext/imgmath.py
  sphinx/pycode/ast.py
  sphinx/util/inspect.py
  sphinx/writers/latex.py
Labels: internals:refactoring

#11837 Apply refurb/ruff rule FURB111
  sphinx/util/cfamily.py
Labels: internals:refactoring

#11838 Apply refurb/ruff rule FURB115
  sphinx/directives/code.py
Labels: internals:refactoring

#11839 Apply refurb/ruff rule FURB116
  sphinx/writers/texinfo.py
Labels: internals:refactoring

#11842 Apply refurb/ruff rule FURB123
  sphinx/environment/collectors/toctree.py
  sphinx/ext/autodoc/importer.py
  sphinx/ext/napoleon/docstring.py
  sphinx/jinja2glue.py
Labels: internals:refactoring

#11840 Apply refurb/ruff rule FURB124
  sphinx/domains/c.py
  sphinx/domains/cpp.py
  sphinx/ext/apidoc.py
  sphinx/pycode/parser.py
Labels: internals:refactoring

#11841 Apply refurb/ruff rule FURB125
  sphinx/directives/__init__.py
  sphinx/search/__init__.py
Labels: internals:refactoring

#11843 Apply refurb/ruff rule FURB131
  sphinx/ext/apidoc.py
  sphinx/ext/napoleon/docstring.py
Labels: internals:refactoring

#11845 Apply refurb/ruff rule FURB134
  sphinx/search/__init__.py
Labels: internals:refactoring

#11846 Apply refurb/ruff rule FURB138
  sphinx/builders/html/__init__.py
  sphinx/domains/c.py
  sphinx/domains/cpp.py
  sphinx/ext/inheritance_diagram.py
  sphinx/pycode/ast.py
  sphinx/transforms/compact_bullet_list.py
Labels: internals:refactoring

#11848 Apply refurb/ruff rule FURB145
  sphinx/domains/changeset.py
  sphinx/events.py
  sphinx/ext/apidoc.py
  sphinx/ext/autodoc/__init__.py
  sphinx/ext/napoleon/__init__.py
  sphinx/testing/fixtures.py
  sphinx/testing/util.py
  sphinx/util/fileutil.py
  sphinx/writers/latex.py
Labels: internals:refactoring

#11850 Apply refurb/ruff rule FURB170
  sphinx/transforms/post_transforms/images.py
Labels: internals:refactoring

#11851 Apply refurb/ruff rule FURB171
  sphinx/environment/collectors/metadata.py
  sphinx/ext/autosummary/generate.py
Labels: internals:refactoring

#11852 Apply refurb/ruff rule FURB173
  sphinx/builders/html/_assets.py
Labels: internals:refactoring

#11825 Allow custom target in manpage role
  doc/usage/restructuredtext/roles.rst
  sphinx/roles.py
  sphinx/transforms/__init__.py
  sphinx/writers/html5.py
  tests/roots/test-manpage_url/index.rst
  tests/test_build_html.py
Labels: markup

#11892 Small tweaks with big performance gains
  CHANGES.rst
  sphinx/domains/c.py
  sphinx/domains/cpp.py
  sphinx/util/cfamily.py
Labels: domains:cpp, type:performance

#11895 Various C++ domain performance improvements
  sphinx/domains/cpp.py
  tests/roots/test-domain-cpp/operator-lookup.rst
  tests/test_domains/test_domain_cpp.py
Labels: domains:cpp, type:performance

#11856 Apply refurb/ruff rule FURB113
  .ruff.toml
  doc/development/tutorials/examples/todo.py
  sphinx/builders/latex/__init__.py
  sphinx/builders/texinfo.py
  sphinx/ext/inheritance_diagram.py
  sphinx/roles.py
  sphinx/search/ja.py
  sphinx/util/cfamily.py
Labels: internals:refactoring
