Repository sphinx-doc/sphinx, pull requests merged in 2024-08, with the labels that each got.

#12730 [rst] Improve unreferenced footnote warnings
  CHANGES.rst
  sphinx/transforms/__init__.py
  tests/test_transforms/test_unreferenced_footnotes.py
Labels: internals:other

#12746 Tell users when a template causes build invalidation
  sphinx/builders/html/__init__.py
  sphinx/jinja2glue.py
Labels: type:enhancement, builder:html, html theme

#12724 Slightly simplify toctree code
  sphinx/directives/other.py
Labels: internals:toctree, internals:refactoring

#12754 Tests: migrate JavaScript tests from karma to jasmine framework
  .github/workflows/nodejs.yml
  CHANGES.rst
  doc/internals/contributing.rst
  karma.conf.js
  package-lock.json
  package.json
  tests/js/jasmine-browser.mjs
  tests/js/searchtools.js
Labels: type:tests

#12756 Add lower-bounds to the ``sphinxcontrib-*`` dependencies
  .github/workflows/main.yml
  CHANGES.rst
  pyproject.toml
Labels: type:tests, dependencies

#12757 Reduce the formatter's target line length to 88
  .ruff.toml
  doc/conf.py
  doc/development/tutorials/examples/recipe.py
  doc/development/tutorials/examples/todo.py
  sphinx/__init__.py
  sphinx/builders/__init__.py
  sphinx/builders/html/__init__.py
  sphinx/builders/latex/__init__.py
  sphinx/deprecation.py
  sphinx/environment/__init__.py
  sphinx/errors.py
  sphinx/events.py
  sphinx/ext/apidoc.py
  sphinx/ext/autosummary/generate.py
  sphinx/highlighting.py
  sphinx/jinja2glue.py
  sphinx/locale/__init__.py
  sphinx/parsers.py
  sphinx/project.py
  sphinx/roles.py
  sphinx/theming.py
  sphinx/versioning.py
  tests/test_environment/test_environment.py
  tests/test_util/test_util_docstrings.py
  tests/test_util/test_util_docutils_sphinx_directive.py
  tests/test_util/test_util_inspect.py
  utils/babel_runner.py
  utils/bump_version.py
Labels: internals:refactoring

#12758 Improve string concatenation
  sphinx/domains/c/_parser.py
  sphinx/domains/cpp/_parser.py
  sphinx/ext/apidoc.py
  sphinx/ext/autosummary/generate.py
  sphinx/ext/coverage.py
  sphinx/transforms/i18n.py
  tests/test_builders/test_build_html_code.py
  tests/test_builders/test_build_latex.py
  tests/test_builders/test_build_warnings.py
  tests/test_directives/test_directive_code.py
  tests/test_directives/test_directive_object_description.py
  tests/test_domains/test_domain_cpp.py
  tests/test_domains/test_domain_js.py
  tests/test_domains/test_domain_py.py
  tests/test_extensions/test_ext_apidoc.py
  tests/test_extensions/test_ext_autosummary.py
  tests/test_extensions/test_ext_ifconfig.py
  tests/test_extensions/test_ext_viewcode.py
  tests/test_intl/test_intl.py
Labels: internals:refactoring

#12759 HTML search: add test coverage, and introduce test module file suffix
  tests/js/fixtures/partial/searchindex.js
  tests/js/fixtures/titles/searchindex.js
  tests/js/jasmine-browser.mjs
  tests/js/roots/partial/index.rst
  tests/js/roots/titles/index.rst
  tests/js/searchtools.spec.js
  tests/js/sphinx_highlight.spec.js
Labels: html search, type:tests, internals:refactoring, javascript

#12725 Restructure toctree documentation
  doc/usage/restructuredtext/directives.rst
Labels: type:docs, internals:toctree

#12726 misc: Mention dynamically-evaluated templates during static file copying
  CHANGES.rst
  sphinx/builders/html/__init__.py
  sphinx/util/fileutil.py
  tests/test_util/test_util_fileutil.py
Labels: builder, internals:other

#12587 intersphinx: Reduce log message severity when ambiguous target resolves to a duplicate
  CHANGES.rst
  sphinx/ext/intersphinx/_resolve.py
  tests/test_extensions/test_ext_intersphinx.py
Labels: extensions:intersphinx, internals:other

#12762 Add ``sphinx.util._importer``
  CHANGES.rst
  doc/extdev/deprecated.rst
  sphinx/builders/__init__.py
  sphinx/search/ja.py
  sphinx/util/__init__.py
  sphinx/util/_importer.py
  tests/test_util/test_util.py
  tests/test_util/test_util_importer.py
Labels: internals:refactoring

#12763 Remove ``sphinx.util.Tee``
  CHANGES.rst
  sphinx/util/__init__.py
Labels: internals:refactoring

#12766 Add ``sphinx.util._files``
  CHANGES.rst
  doc/extdev/deprecated.rst
  sphinx/environment/__init__.py
  sphinx/util/__init__.py
  sphinx/util/_files.py
Labels: internals:refactoring

#12720 Fix warning on not finding documents in toctree glob
  sphinx/directives/other.py
Labels: internals:toctree

#12639 Fix singular and plural search results text
  CHANGES.rst
  sphinx/themes/basic/static/searchtools.js
Labels: html search

#12474 Support type-dependent search result highlighting via CSS
  CHANGES.rst
  doc/_themes/sphinx13/static/sphinx13.css
  doc/development/html_themes/index.rst
  sphinx/themes/basic/static/basic.css.jinja
  sphinx/themes/basic/static/searchtools.js
  tests/js/searchtools.spec.js
Labels: type:enhancement, type:proposal, html search

#12645 Correctly support custom gettext output templates
  CHANGES.rst
  doc/usage/advanced/intl.rst
  sphinx/builders/gettext.py
  tests/roots/test-gettext-custom-output-template/_templates/message.pot.jinja
  tests/roots/test-gettext-custom-output-template/conf.py
  tests/roots/test-gettext-custom-output-template/index.rst
  tests/test_builders/test_build_gettext.py
Labels: i18n, builder:gettext

#12729 LaTeX: let latexpdf implement '-q' and '-Q' sphinx-build options
  CHANGES.rst
  sphinx/cmd/make_mode.py
Labels: type:enhancement, help wanted, builder:latex

#12768 Refactor ``BuildInfo`` and move to a new module
  sphinx/builders/_epub_base.py
  sphinx/builders/html/__init__.py
  sphinx/builders/html/_build_info.py
Labels: internals:refactoring

#12551 singlehtml: Use same-document hyperlinks for internal project references
  CHANGES.rst
  sphinx/builders/singlehtml.py
  tests/test_builders/test_build_html_tocdepth.py
  tests/test_builders/test_build_html_toctree.py
  tests/test_builders/xpath_html_util.py
Labels: builder:html, priority:low

#12772 Short-circuit HTTP requests in tests
  sphinx/environment/__init__.py
  sphinx/environment/adapters/asset.py
  sphinx/transforms/post_transforms/images.py
  tests/conftest.py
  tests/test_builders/test_build.py
  tests/test_builders/test_build_epub.py
  tests/test_builders/test_build_html.py
  tests/test_builders/test_build_html_image.py
  tests/test_builders/test_build_latex.py
  tests/test_builders/test_build_texinfo.py
  tests/test_extensions/test_ext_math.py
  tests/test_intl/test_intl.py
Labels: type:tests

#12773 i18n: restore relative path output by babel runner
  utils/babel_runner.py
Labels: i18n, internals:other

#12776 Increase test independence by using the basic theme
  sphinx/testing/util.py
  tests/test_builders/test_build_html.py
  tests/test_builders/test_build_html_assets.py
  tests/test_builders/test_build_html_highlight.py
  tests/test_domains/test_domain_std.py
  tests/test_intl/test_intl.py
Labels: type:tests

#12784 Add per-event overloads to ``Sphinx.connect()``
  doc/conf.py
  doc/extdev/event_callbacks.rst
  sphinx/application.py
  sphinx/config.py
Labels: internals:typing

#12787 Add per-event overloads to ``EventManager.connect()``
  .flake8
  sphinx/events.py
Labels: internals:typing

#12788 Improve typing for ``mocksvgconverter.py``
  tests/roots/test-ext-imgmockconverter/mocksvgconverter.py
Labels: internals:typing

#12794 Use ``headlessFirefox`` and update to Node 20
  .github/workflows/nodejs.yml
  tests/js/jasmine-browser.mjs
Labels: type:tests

#12795 Test command line argument parsing
  sphinx/cmd/build.py
  sphinx/cmd/make_mode.py
  tests/test_command_line.py
Labels: type:tests

#12745 LaTeX: fix mark-up when \DUrole is used with multiple classes
  CHANGES.rst
  doc/latex.rst
  sphinx/writers/latex.py
  tests/roots/test-latex-table/expects/longtable_having_widths.tex
  tests/roots/test-latex-table/expects/table_having_widths.tex
  tests/test_builders/test_build_latex.py
  tests/test_directives/test_directive_code.py
Labels: type:bug, builder:latex

#12733 LaTeX: avoid "Overfull \hbox" reports when solved by verbatimforcewraps
  CHANGES.rst
  sphinx/texinputs/sphinxlatexliterals.sty
Labels: type:bug, builder:latex

#12798 Test on free-threaded builds of Python
  .github/workflows/main.yml
Labels: type:tests

#12652 LaTeX: Add `math_numsep` support to latex builder
  CHANGES.rst
  doc/latex.rst
  sphinx/texinputs/sphinx.sty
  sphinx/texinputs/sphinxlatexnumfig.sty
  sphinx/writers/latex.py
  tests/test_builders/test_build_latex.py
Labels: type:enhancement, builder:latex

#12704 LaTeX: make contents, topic, and sidebar separately customizable
  CHANGES.rst
  doc/latex.rst
  sphinx/texinputs/sphinx.sty
  sphinx/texinputs/sphinxlatexadmonitions.sty
  sphinx/texinputs/sphinxlatexshadowbox.sty
  sphinx/texinputs/sphinxlatexstyletext.sty
  sphinx/writers/latex.py
  tests/roots/test-latex-contents-topic-sidebar/conf.py
  tests/roots/test-latex-contents-topic-sidebar/index.rst
  tests/roots/test-root/conf.py
  tests/test_builders/test_build_latex.py
Labels: type:enhancement, builder:latex

#12737 LaTeX: Fix #12735 about siglines with typing but no parameter list
  CHANGES.rst
  sphinx/writers/latex.py
  tests/test_builders/test_build_latex.py
Labels: type:bug, builder:latex

#12697 typecheck docs/conf.py
  doc/conf.py
  pyproject.toml
  sphinx/ext/autodoc/__init__.py
Labels: internals:config, internals:typing

#12823 simplify mypy config
  pyproject.toml
Labels: internals:typing
