Repository sphinx-doc/sphinx, pull requests merged in 2025-03, with the labels that each got.

#13430 Add an introduction to HTML templating
  AUTHORS.rst
  doc/development/html_themes/templating.rst
Labels: type:docs

#13422 Remove mypy overrides for ``tests.test_events``
  pyproject.toml
  tests/test_events.py
Labels: internals:typing

#13073 Use the PEP 735 ``[dependency-groups]`` table
  .github/workflows/builddoc.yml
  .github/workflows/create-release.yml
  .github/workflows/lint.yml
  .github/workflows/main.yml
  .github/workflows/transifex.yml
  pyproject.toml
  tox.ini
Labels: dependencies, python

#13446 Allow ignoring type stub files for native modules
  sphinx/ext/autodoc/importer.py
Labels: extensions:autodoc

#13452 Warn on all redirects if ``linkcheck_allowed_redirects`` is an empty dictionary
  CHANGES.rst
  doc/usage/configuration.rst
  sphinx/builders/linkcheck.py
  tests/test_builders/test_build_linkcheck.py
Labels: builder:linkcheck
