Repository sphinx-doc/sphinx, pull requests merged in 2025-06, with the labels that each got.

#13610 Tests: update LaTeX label test expectations from docutils r10151
  tests/test_builders/test_build_latex.py
Labels: type:tests

#13623 Fix #13619 about possibly duplicated footnotes from signatures in PDF
  CHANGES.rst
  sphinx/texinputs/sphinxlatexobjects.sty
Labels: builder:latex

#13625 Extract nested function definitions
  doc/conf.py
  sphinx/builders/_epub_base.py
  sphinx/domains/c/_parser.py
  sphinx/domains/c/_symbol.py
  sphinx/domains/cpp/__init__.py
  sphinx/domains/cpp/_parser.py
  sphinx/domains/cpp/_symbol.py
  sphinx/domains/python/_annotations.py
  sphinx/domains/std/__init__.py
  sphinx/ext/doctest.py
  sphinx/transforms/post_transforms/__init__.py
  sphinx/writers/latex.py
Labels: internals:refactoring

#13627 Deprecate public ``app`` attributes
  CHANGES.rst
  doc/extdev/deprecated.rst
  sphinx/builders/__init__.py
  sphinx/environment/__init__.py
  sphinx/events.py
  sphinx/transforms/__init__.py
  sphinx/util/logging.py
  tests/test_events.py
  tests/test_versioning.py
Labels: internals:refactoring

#13628 Avoid ``self.app`` in transforms
  sphinx/application.py
  sphinx/builders/linkcheck.py
  sphinx/environment/__init__.py
  sphinx/ext/extlinks.py
  sphinx/ext/viewcode.py
  sphinx/io.py
  sphinx/transforms/__init__.py
  sphinx/transforms/i18n.py
  sphinx/transforms/post_transforms/__init__.py
  sphinx/transforms/post_transforms/images.py
  tests/test_transforms/test_transforms_post_transforms_images.py
Labels: internals:refactoring

#13591 autosummary: add 'vs.' to the well-known abbreviations
  sphinx/ext/autosummary/__init__.py
Labels: extensions:autosummary

#13615 Use anonymous references for links with embedded URLs
  doc/usage/restructuredtext/basics.rst
Labels: type:docs

#13596 Document autolink role for autosummary
  doc/usage/extensions/autosummary.rst
Labels: type:docs, extensions:autosummary

#13631 Use an explicit tags parameter for ``global_toctree_for_doc()``
  sphinx/builders/__init__.py
  sphinx/builders/_epub_base.py
  sphinx/builders/epub3.py
  sphinx/builders/html/__init__.py
  sphinx/builders/singlehtml.py
  sphinx/environment/__init__.py
  sphinx/environment/adapters/toctree.py
  tests/test_environment/test_environment_toctree.py
  tests/test_extensions/test_ext_inheritance_diagram.py
  tests/test_extensions/test_ext_math.py
Labels: internals:refactoring

#13632 Avoid self.app in builder
  sphinx/application.py
  sphinx/builders/__init__.py
  sphinx/builders/_epub_base.py
  sphinx/builders/changes.py
  sphinx/builders/gettext.py
  sphinx/builders/html/__init__.py
  sphinx/builders/latex/__init__.py
  sphinx/builders/latex/theming.py
  sphinx/builders/linkcheck.py
  sphinx/builders/texinfo.py
  sphinx/config.py
  sphinx/ext/coverage.py
  sphinx/ext/doctest.py
  sphinx/theming.py
  sphinx/transforms/__init__.py
  tests/test_extensions/test_ext_coverage.py
  tests/test_theming/test_theming.py
Labels: internals:refactoring

#13633 Extract ``_read_conf_py()`` from ``Config.read()``
  sphinx/application.py
  sphinx/config.py
  tests/test_config/test_config.py
Labels: internals:refactoring

#13587 docs(referencing.rst): add additional data about :doc: role
  doc/usage/referencing.rst
Labels: type:docs

#13637 Deprecate ``Parser.set_application()``
  CHANGES.rst
  sphinx/parsers.py
  sphinx/registry.py
  sphinx/testing/restructuredtext.py
  tests/test_markup/test_parser.py
Labels: internals:refactoring

#13639 Stop taking ``app`` in ``create_source_parser()``
  CHANGES.rst
  sphinx/io.py
  sphinx/registry.py
  sphinx/transforms/i18n.py
Labels: internals:refactoring

#13643 Avoid passing ``app`` to ``SphinxComponentRegistry._get_publisher()``
  sphinx/builders/__init__.py
  sphinx/registry.py
Labels: internals:refactoring

#13644 Deprecate ``Parser.{config,env}``
  CHANGES.rst
  sphinx/parsers.py
  sphinx/registry.py
  sphinx/testing/restructuredtext.py
  tests/test_markup/test_parser.py
Labels: internals:refactoring

#13655 Replace ``codecs.open()`` with ``open()``
  sphinx/builders/gettext.py
Labels: internals:refactoring

#13658 Make ``_prepend_prologue()`` and ``_append_epilogue()`` private
  sphinx/parsers.py
  sphinx/util/rst.py
  tests/test_markup/test_parser.py
  tests/test_util/test_util_rst.py
Labels: internals:refactoring

#13664 Refactor ``render_partial()`` to do less work
  sphinx/builders/html/__init__.py
Labels: builder:html, internals:refactoring

#13669 Prefer ``current_document.docname``
  doc/development/tutorials/examples/recipe.py
  doc/development/tutorials/examples/todo.py
  sphinx/builders/latex/transforms.py
  sphinx/builders/linkcheck.py
  sphinx/directives/other.py
  sphinx/directives/patches.py
  sphinx/domains/c/__init__.py
  sphinx/domains/changeset.py
  sphinx/domains/citation.py
  sphinx/domains/cpp/__init__.py
  sphinx/domains/index.py
  sphinx/domains/javascript.py
  sphinx/domains/python/__init__.py
  sphinx/domains/rst.py
  sphinx/domains/std/__init__.py
  sphinx/environment/__init__.py
  sphinx/environment/collectors/asset.py
  sphinx/environment/collectors/metadata.py
  sphinx/environment/collectors/title.py
  sphinx/environment/collectors/toctree.py
  sphinx/ext/autodoc/directive.py
  sphinx/ext/autosectionlabel.py
  sphinx/ext/autosummary/__init__.py
  sphinx/ext/duration.py
  sphinx/ext/graphviz.py
  sphinx/ext/intersphinx/_resolve.py
  sphinx/ext/todo.py
  sphinx/ext/viewcode.py
  sphinx/io.py
  sphinx/roles.py
  sphinx/transforms/i18n.py
  sphinx/transforms/post_transforms/__init__.py
  sphinx/transforms/post_transforms/images.py
  sphinx/transforms/references.py
  sphinx/util/i18n.py
  sphinx/versioning.py
Labels: internals:refactoring

#13673 Add ``_parse_str_to_doctree()`` helper method
  sphinx/testing/restructuredtext.py
  sphinx/transforms/__init__.py
  sphinx/util/docutils.py
  tests/test_directives/test_directive_object_description.py
Labels: internals:refactoring

#13663 Restore support for nested ``only`` nodes in toctrees
  sphinx/environment/adapters/toctree.py
  sphinx/util/tags.py
  tests/roots/test-toctree-only/conf.py
  tests/roots/test-toctree-only/index.rst
  tests/test_environment/test_environment_toctree.py
Labels: internals:toctree

#13676 Use ``_parse_str_to_doctree()`` in ``Builder.read_doc()``
  sphinx/builders/__init__.py
  sphinx/util/docutils.py
  tests/test_directives/test_directive_object_description.py
Labels: internals:refactoring

#13681 Extract change detection into ``_has_doc_changed()`` function
  sphinx/environment/__init__.py
  tests/js/fixtures/cpp/searchindex.js
  tests/js/fixtures/multiterm/searchindex.js
  tests/js/fixtures/partial/searchindex.js
  tests/js/fixtures/titles/searchindex.js
  tests/test_environment/test_environment_record_dependencies.py
Labels: internals:refactoring

#13686 Ignore trailing backslashes in `gettext`
  CHANGES.rst
  sphinx/util/nodes.py
  tests/roots/test-intl/backslashes.txt
  tests/roots/test-intl/index.txt
  tests/test_builders/test_build_gettext.py
Labels: builder:gettext

#13691 Refresh the list of third-party domains
  doc/usage/domains/index.rst
Labels: type:docs

#13709 Update CHANGES to indicate fix of #1327
  CHANGES.rst
Labels: builder:latex
