Repository sphinx-doc/sphinx, pull requests merged in 2025-05, with the labels that each got.

#13537 Tests: linkcheck: ensure Python clock timezone is reset during test teardown
  tests/test_builders/test_build_linkcheck.py
Labels: type:tests

#13536 Support annotations and default values in `_pseudo_parse_arglist`
  sphinx/domains/javascript.py
  sphinx/domains/python/_annotations.py
  sphinx/domains/python/_object.py
  tests/test_domains/test_domain_py.py
  tests/test_domains/test_domain_py_pyfunction.py
Labels: domains:py

#13548 Fix ``test_util`` for Docutils 0.22+
  tests/test_util/test_util_docutils_sphinx_directive.py
Labels: type:tests, docutils

#13562 Merge ``SearchLanguage.init()`` into ``__init__()``
  sphinx/search/__init__.py
  sphinx/search/da.py
  sphinx/search/de.py
  sphinx/search/en.py
  sphinx/search/es.py
  sphinx/search/fi.py
  sphinx/search/fr.py
  sphinx/search/hu.py
  sphinx/search/it.py
  sphinx/search/ja.py
  sphinx/search/nl.py
  sphinx/search/no.py
  sphinx/search/pt.py
  sphinx/search/ro.py
  sphinx/search/ru.py
  sphinx/search/sv.py
  sphinx/search/tr.py
  sphinx/search/zh.py
Labels: internals:refactoring

#13571 Update URLs for the Snowball project
  sphinx/search/__init__.py
  sphinx/search/da.py
  sphinx/search/de.py
  sphinx/search/es.py
  sphinx/search/fi.py
  sphinx/search/fr.py
  sphinx/search/hu.py
  sphinx/search/it.py
  sphinx/search/nl.py
  sphinx/search/no.py
  sphinx/search/pt.py
  sphinx/search/ru.py
  sphinx/search/sv.py
Labels: type:docs

#13572 Pre-parse stopword lists
  .gitattributes
  sphinx/search/__init__.py
  sphinx/search/_stopwords/__init__.py
  sphinx/search/_stopwords/da.py
  sphinx/search/_stopwords/da.txt
  sphinx/search/_stopwords/de.py
  sphinx/search/_stopwords/de.txt
  sphinx/search/_stopwords/en.py
  sphinx/search/_stopwords/es.py
  sphinx/search/_stopwords/es.txt
  sphinx/search/_stopwords/fi.py
  sphinx/search/_stopwords/fi.txt
  sphinx/search/_stopwords/fr.py
  sphinx/search/_stopwords/fr.txt
  sphinx/search/_stopwords/hu.py
  sphinx/search/_stopwords/hu.txt
  sphinx/search/_stopwords/it.py
  sphinx/search/_stopwords/it.txt
  sphinx/search/_stopwords/nl.py
  sphinx/search/_stopwords/nl.txt
  sphinx/search/_stopwords/no.py
  sphinx/search/_stopwords/no.txt
  sphinx/search/_stopwords/pt.py
  sphinx/search/_stopwords/pt.txt
  sphinx/search/_stopwords/ru.py
  sphinx/search/_stopwords/ru.txt
  sphinx/search/_stopwords/sv.py
  sphinx/search/_stopwords/sv.txt
  sphinx/search/da.py
  sphinx/search/de.py
  sphinx/search/en.py
  sphinx/search/es.py
  sphinx/search/fi.py
  sphinx/search/fr.py
  sphinx/search/hu.py
  sphinx/search/it.py
  sphinx/search/nl.py
  sphinx/search/no.py
  sphinx/search/pt.py
  sphinx/search/ro.py
  sphinx/search/ru.py
  sphinx/search/sv.py
  sphinx/search/tr.py
  sphinx/search/zh.py
Labels: html search

#13561 Update stemming and Snowball
  CHANGES.rst
  doc/internals/contributing.rst
  sphinx/search/__init__.py
  sphinx/search/_stopwords/da.py
  sphinx/search/_stopwords/da.txt
  sphinx/search/_stopwords/de.py
  sphinx/search/_stopwords/de.txt
  sphinx/search/_stopwords/en.py
  sphinx/search/_stopwords/en.txt
  sphinx/search/_stopwords/es.py
  sphinx/search/_stopwords/es.txt
  sphinx/search/_stopwords/fi.py
  sphinx/search/_stopwords/fi.txt
  sphinx/search/_stopwords/fr.py
  sphinx/search/_stopwords/fr.txt
  sphinx/search/_stopwords/hu.py
  sphinx/search/_stopwords/hu.txt
  sphinx/search/_stopwords/it.py
  sphinx/search/_stopwords/it.txt
  sphinx/search/_stopwords/nl.py
  sphinx/search/_stopwords/nl.txt
  sphinx/search/_stopwords/no.py
  sphinx/search/_stopwords/no.txt
  sphinx/search/_stopwords/pt.py
  sphinx/search/_stopwords/pt.txt
  sphinx/search/_stopwords/ru.py
  sphinx/search/_stopwords/ru.txt
  sphinx/search/_stopwords/sv.py
  sphinx/search/_stopwords/sv.txt
  tests/js/fixtures/cpp/searchindex.js
  tests/js/fixtures/multiterm/searchindex.js
  tests/js/fixtures/partial/searchindex.js
  tests/js/fixtures/titles/searchindex.js
  utils/generate_snowball.py
Labels: html search

#13575 Convert stopwords to a JavaScript set
  sphinx/themes/basic/static/language_data.js.jinja
  sphinx/themes/basic/static/searchtools.js
  tests/js/language_data.js
Labels: html search, internals:refactoring

#13552 Do not override type checks for test_util_fileutil
  pyproject.toml
  tests/test_util/test_util_fileutil.py
Labels: internals:typing

#13516 Update arg lists for 2 events in ``event_callbacks.rst``
  doc/extdev/event_callbacks.rst
Labels: type:docs

#13584 Remove mypy overrides for tests/test_util/test_util.py
  pyproject.toml
  tests/test_util/test_util.py
Labels: internals:typing

#13582 Remove mypy overrides for tests/test_util/test_util_inventory.py
  pyproject.toml
  tests/test_util/test_util_inventory.py
Labels: internals:typing

#13586 Remove mypy overrides for ``tests/test_pycode/test_pycode_ast.py``
  pyproject.toml
  tests/test_pycode/test_pycode_ast.py
Labels: internals:typing

#13583 Remove mypy overrides for tests/test_util/test_util_display.py
  pyproject.toml
  tests/test_util/test_util_display.py
Labels: internals:typing

#13581 Adopt Prettier for JavaScript formatting
  .github/workflows/lint.yml
  .prettierrc.toml
  sphinx/search/__init__.py
  sphinx/themes/basic/static/doctools.js
  sphinx/themes/basic/static/searchtools.js
  sphinx/themes/basic/static/sphinx_highlight.js
  sphinx/themes/scrolls/static/theme_extras.js
  tests/js/jasmine-browser.mjs
  tests/js/language_data.js
  tests/js/searchtools.spec.js
  tests/js/sphinx_highlight.spec.js
  tox.ini
Labels: internals:refactoring

#13590 Remove unused fixture from test_config_pickle_protocol
  tests/test_config/test_config.py
Labels: type:tests
